### ISSUE TITLE
PHP Fatal error:  Maximum recursion depth exceeded

### ISSUE THREAD

**Issue by marvasDE** [phalcon/phalcon-devtools#1011]
### Expected and Actual Behavior

I just run "phalcon" and it outputs:

"Phalcon DevTools (3.1.0)

#!/usr/bin/env php
PHP Notice:  Constant COMPATIBLE_VERSION already defined in /../phalcon-devtools/bootstrap/autoload.php on line 106"

... in a loop. At the end it terminates with:
'PHP Fatal error:  Maximum recursion depth exceeded in /../phalcon-devtools/bootstrap/autoload.php on line 115'

I cloned the repository via git. It still works on [c01096a248dd306e10fff8c774cba402b9c658f2](https://github.com/phalcon/phalcon-devtools/commit/c01096a248dd306e10fff8c774cba402b9c658f2), so [41e67abbf777642ef0da766618af92b53a7ea6c1](https://github.com/phalcon/phalcon-devtools/commit/41e67abbf777642ef0da766618af92b53a7ea6c1) should be the problem.

### Details

* Phalcon Framework version: 3.1.2
* PHP Version: PHP 7.0.15-0ubuntu0.16.04.4
* Operating System: Ubuntu 16.04
* Server: Command Line

**Comment by sergeyklay** [comment]
Fixed in 3.2.x branch.

**Comment by sergeyklay** [comment]
Cc: @Jurigag
