### ISSUE TITLE
Webtools on PHP Built in Server Gives 404 error

### ISSUE THREAD

**Issue by n0nag0n** [phalcon/phalcon-devtools#1012]
Hey,

I can't seem to get webtools working for me. I'm using Phalcon 3.1.2, Devtools 3.1.2, on macOS Sierra using PHP 7.1.4.

I'm trying to get it working using PHP's built in webserver and I think it's working, but something inside webtools itself isn't working....

So I used this to see if I could get it working... https://docs.phalconphp.com/en/3.0.1/reference/built-in.html

And I get this
![screen shot 2017-04-18 at 7 39 31 am](https://cloud.githubusercontent.com/assets/2322095/25144651/52728fb2-240a-11e7-971b-a7a1d157688e.png)

You can see that the css is being loaded, and the 404 page is served through phalcon, not PHP's built in error. I haven't touched the webtools.config.php file or anything. I just created a project with `phalcon project new-project --enable-webtools` and the project created just fine. Going to localhost/ serves the file just fine, but going to localhost/webtools.php makes it show that 404 error.

I also tried making .htrouter.php look like this blogpost, but no dice either.
http://qiita.com/kazumihirose/items/9fe67b9c941889d25871

Thoughts, impressions, or feelings? ;)

**Comment by sergeyklay** [comment]
I'll try to sort out as soon as possible

**Comment by sergeyklay** [comment]
@n0nag0n  You have to configure `PTOOLS_IP` constant. See `public/webtools.config.php`.

**Comment by n0nag0n** [comment]
No luck with changing the IP to anything else. localhost, 127.0.0.1, 127, my home public IP, nothing makes it want to work. I did a `var_dump($_SERVER['REMOTE_ADDR'])` and it printed out `string '::1'`, IPv6 style. Maybe it's not configured to handle IPv6?

![image](https://cloud.githubusercontent.com/assets/2322095/25859356/236fcc5e-3493-11e7-93f3-f0788b835e62.png)

**Comment by sergeyklay** [comment]
You have to use 192.168.xxx.xxx, not 127.0.0.1.

Addresses lying in range of `127.0.0.0` to `127.255.255.255` are **Class A** addresses and are reserved for [Loopback](http://en.wikipedia.org/wiki/Loopback) functionality, data sent to Class A address only reach till Network layer, and is used for testing and experimentation. Whereas 192 series (i.e `192.0.0.0` to `223.255.255.255`) represents **Class C** addresses, reserved for Local Area Network.

**Comment by n0nag0n** [comment]
`defined('PTOOLS_IP') || define('PTOOLS_IP', '192.168.'); // also 192.` still gives me a 404 error. Here is the output from the php webserver
```
[Tue May  9 15:54:32 2017] ::1:58723 [404]: /webtools.php
[Tue May  9 15:54:32 2017] ::1:58724 [200]: /css/webtools.css?v=3.1.2
[Tue May  9 15:55:23 2017] ::1:58939 [404]: /webtools.php
[Tue May  9 15:55:23 2017] ::1:58940 [200]: /css/webtools.css?v=3.1.2
[Tue May  9 15:56:47 2017] ::1:58941 Invalid request (Unexpected EOF) # Not sure what this is, it happens 1+ minute after the request and I didn't touch/refresh the page. No request is recorded in Chrome devtools
```

Here's the view from Chrome devtools.
![image](https://cloud.githubusercontent.com/assets/2322095/25876128/1af18e40-34d0-11e7-9f25-ae91d9451fe8.png)

**Comment by sergeyklay** [comment]
Did you check your real IP? (for example by using `ifconfig`/`ipconfig`)

**Comment by n0nag0n** [comment]
So my IP is actually 10.1.10.*, but I tried that and it didn't work, I even tried 10. with no luck either. :(

**Comment by sergeyklay** [comment]
Could you please paste full output of `ifconfig`/`ipconfig`

**Comment by n0nag0n** [comment]
Interestingly enough, I just upgraded to devtools 3.2.13 on 3.3.2 of Phalcon and I still get this error. I tried diving into the webtools code to find out where PTOOLS_IP is used, and I get nowhere. I output `$_SERVER['REMOTE_ADDR']` and I get "::1" my local ip on my network at home is 10.1.10.*. I've tried all sorts of combinations of things to get it to work, partial ip addresses, blank, null, empty, commenting it out, localhost, whatever, and I can't even disable the chunk of code in the devtools codebase to not look for PTOOLS_IP and bypass it, cause it just disappears into the $this-configurable property and is used elsewhere under cloak and dagger XD.....oh well. I guess it's command line for me despite the web interface looking awesome :'(

**Comment by sergeyklay** [comment]
@n0nag0n Do you still use macOS? Did you tried something like https://kb.wisc.edu/helpdesk/page.php?id=6526

**Comment by n0nag0n** [comment]
Yeah, I've tried my real IP, the subnet, the gateway, the local ip (all with many variants), localhost, 127.0.0.1 even though I know it won't work. I just don't know where the code is that's making the IP comparison so I can figure out what it's trying to find on my local dev environment.

**Comment by sergeyklay** [comment]
@n0nag0n It is here https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Access/Policy/Ip.php#L62

Could you try to debug this function to determine the actual IP?

**Comment by n0nag0n** [comment]
Great news!!! It doesn't actually get to hit that function...... :-/ I won't output my var_dump() and exit; lines. Still gives me the 404 error.

**Comment by sergeyklay** [comment]
How about this line?

https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Access/Manager.php#L62

**Comment by n0nag0n** [comment]
```php        
var_dump($resourceName);
var_dump($data);
exit;
```

End up with this.
```
/path/to/phalcon-devtools/scripts/Phalcon/Access/Manager.php:62:string 'error' (length=5)
/path/to/phalcon-devtools/scripts/Phalcon/Access/Manager.php:63:null
```

**Comment by n0nag0n** [comment]
In ErrorController on line ~93, I added
```php
echo '<pre>';
print_r(debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS));
exit;
```

And I get the following
```
Array
(
    [0] => Array
        (
            [function] => route404Action
            [class] => WebTools\Controllers\ErrorController
            [type] => ->
        )

    [1] => Array
        (
            [function] => callActionMethod
            [class] => Phalcon\Dispatcher
            [type] => ->
        )

    [2] => Array
        (
            [function] => dispatch
            [class] => Phalcon\Dispatcher
            [type] => ->
        )

    [3] => Array
        (
            [file] => /path/to/phalcon-devtools/scripts/Phalcon/Bootstrap.php
            [line] => 193
            [function] => handle
            [class] => Phalcon\Mvc\Application
            [type] => ->
        )

    [4] => Array
        (
            [file] => /path/to/phalcon-devtools/scripts/Phalcon/Bootstrap.php
            [line] => 183
            [function] => getOutput
            [class] => Phalcon\Bootstrap
            [type] => ->
        )

    [5] => Array
        (
            [file] => /path/to/project/public/webtools.php
            [line] => 36
            [function] => run
            [class] => Phalcon\Bootstrap
            [type] => ->
        )

)
```

**Comment by sergeyklay** [comment]
Phalcon\Dispatcher::dispatch can't find route matching. It seems something wrong with application routing configuration or webserver setup.  @sergeysviridenko could you please take a look?

**Comment by n0nag0n** [comment]
I'm using PHPs built in webserver (I'm not running PHP 7.2.5) and the file is in `public/webtools.php` and `public/webtools.config.php`. In my browser I go to `localhost:3000/webtools.php` and am presented with the 404 error.

**Comment by sergeyklay** [comment]
Ah! Any chance to try a real web server e.g. Nginx or Apache? https://docs.phalconphp.com/en/3.3/webserver-setup

**Comment by n0nag0n** [comment]
Just cause I need to say it....I hate configuring apache. But I got it to work on my live server. Couldn't get it configured on my local apache server for whatever reason and I've got better things to do. It keeps trying to serve my IP over IPv6 and not IPv4 for whatever reason. But once I whitelisted the correct IP, I can see it on my live server. Just not sure why I can't see it running on my local php webserver (which is a lifesaver cause figuring out what apache is doing is a nightmare....

So while I say it works, if I click on something else like List all Controllers, I get the permission denied error on `/webtools.php?_url=/controllers/list`

**Comment by n0nag0n** [comment]
And it looks like if I refresh the page.....it works fine now working between pages. Something bad must have been cached and need a page reload to purge it...

**Comment by sergeyklay** [comment]
@n0nag0n Could you try to use `phalcon serve` command  from the project root instead of `php -S ...`

**Comment by n0nag0n** [comment]
@sergeyklay Same result. Tried 0.0.0.0:8000, localhost:8000, 127.0.0.1:8000, all with same result (but my web app works just fine).
![image](https://user-images.githubusercontent.com/2322095/40784297-1d568b18-649a-11e8-9c21-62379c87bb41.png)
![image](https://user-images.githubusercontent.com/2322095/40784304-23a4a72a-649a-11e8-983b-cb95e0bfa9b6.png)

**Comment by sergeyklay** [comment]
It seems to me its all about missing `_url` GET param

**Comment by n0nag0n** [comment]
@sergeyklay So this is my .htrouter file. I've tried both the commented and uncommented portions. I'm using the uncommented portion now as it wasn't recognizing any custom parameters inside a ?
```php
<?php
//  if (!file_exists(__DIR__  . $_SERVER['REQUEST_URI'])) {
//      $_GET['_url'] = $_SERVER['REQUEST_URI'];
//  }
//  return false;
    if (!file_exists(__DIR__ . '/' . $_SERVER['REQUEST_URI'])) {
        $explode = explode('?', $_SERVER['REQUEST_URI']);
        $_GET['_url'] = $explode[0];
        if (isset($explode[1])) {
            $params = explode('&', $explode[1]);
            foreach ($params as $param) {
                list($key, $value) = explode('=', $param);
                $_GET[$key] = $value;
            }
        }
    }
    return false;
```

**Comment by sergeyklay** [comment]
So, is it works now?

**Comment by n0nag0n** [comment]
It works under apache, and it works under Cherokee running as FCGI, but I still haven't been able to make it work with the PHP dev server which honestly is the easiest way to do this. @sergeyklay

**Comment by Druid33** [comment]
Hi everyone.
I have the same problem with phalcon 4 nad webtools 4.
After hours of crying, googling and depresion a start debuging devtools code. As soon as i display routes from router i realize, that problem is, as usual, between chair and keyboard :).

You need to write /webtools.php**/** to url not /webtools.php

The last backslash is important!
