### ISSUE TITLE
error in running install script

### ISSUE THREAD

**Issue by lydbupt** [phalcon/phalcon-devtools#1015]
### Expected and Actual Behavior

Following the instruction, I run ". ./phalcon.sh" in my phalcon-devtools dir, but I got an error as follow.
"init:3: = not found"
Seems the script tried to run in runlevel 3, but not success.

### Details

* System info and versions (if possible): (`phalcon info`)
* Phalcon Framework version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System: Ubuntu 16.04
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment]
Could you please provide more info: Devtools version, PHP version, installation method (git, composer), etc.

Thanks

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
