### ISSUE TITLE
I got an error when installing devtools

### ISSUE THREAD

**Issue by Lanhuabao** [phalcon/phalcon-devtools#1016]
I do all the step as what the docs say, finally when I use the phalcon script ,it thrown an error like this:

Constant COMPATIBLE_VERSION already defined in /soft/devtool/bootstrap/autoload.php on line 106
PHP Fatal error:  Maximum recursion depth exceeded in /soft/devtool/bootstrap/autoload.php on line 115

My OS is ubuntu 16.04.   PHP VERSION 7.0.12

**Comment by sergeyklay** [comment]
@Lanhuabao Fixed in 3.2.x branch

Cc: @Jurigag

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/phalcon-devtools/issues/1006, https://github.com/phalcon/phalcon-devtools/issues/1011
