### ISSUE TITLE
Blank page for modules with INI usage

### ISSUE THREAD

**Issue by WebworkStudios** [phalcon/phalcon-devtools#1020]
When I start a modulating project with INI-Config, there is a white page.
It works with Array Config. (You're now flying with Phalcon.)

Am I perhaps just too stupid? :)

**Comment by sergeyklay** [comment]
@WebworkStudios Could you please provide a bit more info to reproduce the issue? I mean minimal script to reproduce, PHP & DevTools version , OS, configuration, etc.

Thanks.

**Comment by WebworkStudios** [comment]
On the scripts I had nothing changed.
Command: phalcon project kickerscup --type = modules --enable-webtools --use-config-ini
**Environment**
-   OS: macOS Sierra
-   Server: Nginx (with MAMP)
-   PHP SAPI: cli
-   PHP Bin: /Applications/MAMP/bin/php/php7.1.3/bin/php
-   PHP Extension Dir: /Applications/MAMP/bin/php/php7.1.3/lib/php/extensions/no-debug-non-zts-20160303
-   PHP Bin Dir: /Applications/MAMP/bin/php/php7.1.3/bin
-   Loaded PHP config: /Applications/MAMP/bin/php/php7.1.3/conf/php.ini

**Versions**
-   Phalcon DevTools Version: 3.1.2
-   Phalcon Version: 3.1.2
-   AdminLTE Version: 2.3.6

**Comment by sergeyklay** [comment]
I'll try to sort out

**Comment by sergeyklay** [comment]
Fixed in the 3.2.x branch
