### ISSUE TITLE
Custom module in multi module project not accessible through URL

### ISSUE THREAD

**Issue by Weenuspenus** [phalcon/phalcon-devtools#1034]
Some info about the project I'm setting up, so that it's easier to refer to certain parts in this issue:
Project name: testproject
Project modules: frontend (default), portal (custom), cli (default, but not used)

**Setup:**
I created a new project using Devtools with the type "modules", created a new module inside of the new project with Devtools. Manually added module to `$application->registerModules` in `app/bootstrap_web.php`. Manually added module to `$loader->registerClasses` in `app/config/loader.php`. I copied app/modules/frontend/controllers to app/modules/portal/controllers and app/modules/frontend/views to app/modules/portal/views. I changed the namespaces in the app/modules/portal/controllers controller files. Project base is now ready!

**Expected & actual behaviour:**
I visit http://testproject.local/, I see the 'Congratulations! You're now flying with Phalcon.' view. Great, project works. I visit http://testproject.local/portal, I get a 404 page. 'Not Found. The requested URL /portal was not found on this server.'. Not what I was expecting, since the `app/config/routes.php` clearly define routes for _each module_. 

**Ways to reproduce**
Initial project:
`phalcon project testproject modules --use-config-ini).`

New module:
`phalcon module portal --output=app/modules.`

Extra manual tweaks:
1. Go to app/config/loader.php. After line 20 (`'Testproject\Modules\Frontend\Module' => APP_PATH . '/modules/frontend/Module.php',`), add the next line: `'Testproject\Modules\Portal\Module'      => APP_PATH . '/modules/portal/Module.php'`.
2. Go to app/bootstrap_web.php. After line 49 (`'frontend' => ['className' => 'Testproject\Modules\Frontend\Module']`), add the next line: `'portal' => ['className' => 'Testproject\Modules\Portal\Module']`.
3. Copy app/modules/frontend/controllers to /app/modules/portal/controllers. Go to app/modules/portal/controllers/ControllerBase.php & IndexController.php, and change the namespaces to 'namespace Testproject\Modules\Portal\Controllers;'
4. Copy /app/modules/frontend/views to /app/modules/portal/views.
5. Visit the project in your browser. Preferably through a virtualhost, like http://testproject.local.
6. Confirm that the project is working (you see the 'Congratulations!' view)
7. Visit http://testproject.local/portal. You'll see a 404 not found page. Expected behaviour would be to see the portal index view that we copied from the frontend module (which would be the same 'Congratulations!' view).

**System details**
phalcon info:
```
Environment:
  OS: Linux Delta 4.8.0-58-generic #63~16.04.1-Ubuntu SMP Mon Jun 26 18:08:51 UTC 2017 x86_64
  PHP Version: 7.0.18-0ubuntu0.16.04.1
  PHP SAPI: cli
  PHP Bin: /usr/bin/php7.0
  PHP Extension Dir: /usr/lib/php/20151012
  PHP Bin Dir: /usr/bin
  Loaded PHP config: /etc/php/7.0/cli/php.ini
Versions:
  Phalcon DevTools Version: 3.2.0
  Phalcon Version: 3.2.0
  AdminLTE Version: 2.3.6
```

php --ri phalcon:
```
phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.0
Build Date => Jun 21 2017 21:36:36
Powered by Zephir => Version 0.9.8-6335775f25

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off
```

php -v: 
```
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```
lsb_release -a (operating system):
```
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```
apache2 -v:
```
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2017-06-26T11:58:04
```

Other related info:
n/a

**Comment by Jurigag** [comment]
The answer is really trival - by default phalcon doesn't have automatic routes to modules, you need to add such, you can find similar threads on forum with answer.

**Comment by Weenuspenus** [comment]
@Jurigag The devtools generate a router file with what seems to have automatic module routing, as seen below:

```
<?php

$router = $di->getRouter();

foreach ($application->getModules() as $key => $module) {
    $namespace = preg_replace('/Module$/', 'Controllers', $module["className"]);
    $router->add('/'.$key.'/:params', [
        'namespace' => $namespace,
        'module' => $key,
        'controller' => 'index',
        'action' => 'index',
        'params' => 1
    ])->setName($key);
    $router->add('/'.$key.'/:controller/:params', [
        'namespace' => $namespace,
        'module' => $key,
        'controller' => 1,
        'action' => 'index',
        'params' => 2
    ]);
    $router->add('/'.$key.'/:controller/:action/:params', [
        'namespace' => $namespace,
        'module' => $key,
        'controller' => 1,
        'action' => 2,
        'params' => 3
    ]);
}
```

I've tried following advice from around the net, such as https://stackoverflow.com/questions/36503009/phalcon-multi-module-routes-for-other-modules, and replacing all code from my router.php with something like this:

```
$router->add('/portal', [
         'module' => 'portal', 
         'controller' => 'index', 
         'action' => 'index'
        ]);

$router->add('/portal/:controller/:action/([0-9]+)/:params', [
         'module' => 'portal',
         'controller' => 1,
         'action' => 2,
         'id' => 3, 
         'params' => 4
        ])->setName('portal-full');

$router->add('/portal/:controller/:action', [
         'module' => 'portal',
         'controller' => 1,
         'action' => 2
        ])->setName('portal-short');

$router->add('/portal/:controller', [
         'module' => 'portal',
         'controller' => 1,
         'action' => 'index'
       ]);
```
There is a reason why I've posted this issue in the Phalcon Devtools project, and not the cphalcon project, as I know that by default, Phalcon doesn't do that much.

**Comment by sergeysviridenko** [comment]
@Weenuspenus have you tried to use generated code without any changing?

**Comment by Jeckerson** [comment]
You need properly to configure vhost of webserver. Closing.
