### ISSUE TITLE
phalcon dev tools system path variable

### ISSUE THREAD

**Issue by ritox842** [phalcon/phalcon-devtools#1035]
I'm trying to add phalcon dev tools to my path variables (As shown [here][1]) but I'm getting this error (When I try to use phalcon in cmd):

    ERROR: The environment variable PTOOLSPATH is outdated!
    Current value: "C:\Program Files (x86)\phalcon-devtools".
    New value: C:\Program Files (x86)\phalcon-devtools

This is my phalcon.bat:

    @echo off
               
    set PTOOLSPATH="%ProgramFiles(x86)%\phalcon-devtools"
    php %PTOOLSPATH%\phalcon.php %*

My phalcon.php location is :

    C:\Program Files (x86)\phalcon-devtools

And lastly, my system variable is :

    C:\Program Files (x86)\phalcon-devtools

  [1]: https://docs.phalconphp.com/en/3.2/devtools-installation

I'm using windows 10, 
php 7.1.6,

What am I doing wrong?
Thanks in advance!

**Comment by sergeyklay** [comment]
@sergeysviridenko Could you please take a look

**Comment by sergeysviridenko** [comment]
Could you try `set PTOOLSPATH=%ProgramFiles(x86)%\phalcon-devtools`.

**Comment by ritox842** [comment]
It does't work... It looks like in ignores everything after the first space...

c:\Program

That's it..

**Comment by sergeyklay** [comment]
@ritox842 Well, could you install DevTools to the path without spaces? For example C:\Phalcon. Just for test

**Comment by ritox842** [comment]
When the path doesnt contains spaces it works... 
Its fine for now but I do prefer the dev tool dir will be under program files..

**Comment by sergeyklay** [comment]
@ritox842 Fixed in the `3.2.x branch`. Could you please try now the `3.2.x branch`?

**Comment by sergeysviridenko** [comment]
I propose close this issue. If it appear again - we'll open new issue.
