### ISSUE TITLE
phalcon-devtools ide-helper errors

### ISSUE THREAD

**Issue by CrazyWorkers** [phalcon/phalcon-devtools#1047]
In response to a problem， in the current version of phalcon-devtools,  the code prompts like failure after configured in the phpstorm , as if because the ide folder lack the stubs folder, which should be the Phalcon code to achieve prompt function code.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/phalcon-devtools/issues/1008

**Comment by sergeyklay** [comment]
The IDE stubs was migrated to the https://github.com/phalcon/ide-stubs repo

**Comment by CrazyWorkers** [comment]
thank you for your aswer.
