### ISSUE TITLE
Mysql root user is inaccessible except for su user

### ISSUE THREAD

**Issue by ChangePlaces** [phalcon/phalcon-devtools#1048]
When creating a project, the config file is populated with a standard mysql database, with user root and blank password. This was fine, however mysql now prevents the root user from being used except by a system su user. This poses a few questions which maybe the community, developer needs to answer:

- maybe the default config should be changed to something else?
- maybe a reminder should be output after project creation to create a new user?
- perhaps dev tools can ask for a mysql username and poss. password? Or, if it does ask for a username, then output a reminder to populate the password in the config file?

**Comment by sergeyklay** [comment]
> maybe the default config should be changed to something else?

I don't think it's necessary or we can do it universally.

> maybe a reminder should be output after project creation to create a new user?
> perhaps dev tools can ask for a mysql username and poss. password? Or, if it does ask for a username, then output a reminder to populate the password in the config file?

Agree for 100%.

**Comment by sergeyklay** [comment]
Cc: @sergeysviridenko

**Comment by ChangePlaces** [comment]
if you go the way of asking for a mysql username, then it should not allow the username 'root' with the above explanation.

**Comment by sergeyklay** [comment]
Implemented in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing!

**Comment by ChangePlaces** [comment]
thanks!
