### ISSUE TITLE
Prompt the user to create a .phalcon directory if missing from the project

### ISSUE THREAD

**Issue by ninjapanzer** [phalcon/phalcon-devtools#1054]
Example:
`$ phalcon migration new_mgration .`

will result in:
```
Phalcon DevTools (3.2.0)

  Error: This command should be invoked inside a Phalcon project directory.
```
The unfortunate part of this is we are not exposing to the use what the devtools are upset about.
This command should either tell the user to create a `.phalcon` directory in the project or ask them to confirm and generate it for them.

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.
