### ISSUE TITLE
Class name is changed when user specifies it

### ISSUE THREAD

**Issue by ChangePlaces** [phalcon/phalcon-devtools#1056]
### Expected and Actual Behavior
When creating a model and passing in the expected output name, it appears to be converted to lowercase except for the first letter. e.g. `phalcon model MyFooBar --name=my_foo_bars` creates a model called `Myfoobar` instead of `MyFooBar`.

### Details

* System info and versions (if possible): phalcon tools 3.2.0
* Phalcon Framework version: (`php --ri phalcon`) 3.2.1
* PHP Version: (`php -v`) 7.0
* Operating System: ubuntu
* Server: Nginx 
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.
