### ISSUE TITLE
Field names in generated model start with uppercase

### ISSUE THREAD

**Issue by midem** [phalcon/phalcon-devtools#1070]
### Expected and Actual Behavior

I generate models from mysql database using _model_ or _all-models_ command. My field names in database are in lowercase (for example "user_id"), but in generated model the names start with uppercase (for example "public $User_id;", but I expect "public $user_id;").

### Details

* Phalcon DevTools version: 3.2.0
* Phalcon Framework version: 3.2.1
* PHP Version: 7.1.7-1+ubuntu16.04.1+deb.sury.org+1
* Operating System: ubuntu16.04 (tested also on ubuntu14.04)
* Server: Apache

**Comment by Zheness** [comment]
Hi,
Same problem for me.

My field name is `createdBy` and when generating models, the name is in lowercase except the first letter (`Createdby`).
-> Expected `createdBy`

- Debian 8 (jessie)
- PHP 7.0.20
- Phalcon 3.2.1
- Phalcon DevTools 3.2.0
- MySQL 5.7.19
- nginx 1.12.1

**Comment by sergeyklay** [comment]
Cc: @sergeysviridenko

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Comment by sergeyklay** [comment]
[Just released v3.2.2](https://github.com/phalcon/phalcon-devtools/releases/tag/v3.2.2).
