### ISSUE TITLE
WebTools doesn't know where the models directory is

### ISSUE THREAD

**Issue by hugo9099** [phalcon/phalcon-devtools#1077]
### Expected and Actual Behavior

I'm trying to create a Model using the Web Interface provided by webtools.php
However, I'm getting these error messages:

**Sorry, WebTools doesn't know where the models directory is. Please add to application section modelsDir param with real path.**

It seems to be affecting Models and Controllers directories since Scaffold is disabled as well.

### My environment

* System info and versions (if possible): (`phalcon info`)
Phalcon DevTools (3.2.0)

Environment:
  OS: Darwin HMc.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
  PHP Version: 5.6.31
  PHP SAPI: cli
  PHP Bin: /usr/local/Cellar/php56/5.6.31_7/bin/php
  PHP Extension Dir: /usr/local/Cellar/php56/5.6.31_7/lib/php/extensions/no-debug-non-zts-20131226
  PHP Bin Dir: /usr/local/Cellar/php56/5.6.31_7/bin
  Loaded PHP config: /usr/local/etc/php/5.6/php.ini
Versions:
  Phalcon DevTools Version: 3.2.0
  Phalcon Version: 3.2.0
  AdminLTE Version: 2.3.6

* Phalcon Framework version: (`php --ri phalcon`)
php --ri phalcon

phalcon

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.0
Build Date => Jun 28 2017 15:51:01
Powered by Zephir => Version 0.9.8-6335775f25

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

* PHP Version: (`php -v`)
php -v
PHP 5.6.31 (cli) (built: Aug  7 2017 20:28:40)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

* Operating System:
Mac OSX 10.12.6

* Server: Apache
httpd -v
Server version: Apache/2.4.25 (Unix)
Server built:   Feb  6 2017 20:02:10

* Other related info (Database, table schema): 
MySQL Server version: 5.7.17 Homebrew

**Comment by sergeysviridenko** [comment]
I couldn't reproduce this issue. Could you check your settings in `config.php`? This problem can appear when folder where `WebTools` will put created model didn't set. If you use CLI, you can use option `--output=s`. If you use page `/webtools.php?_url=/models/generate` you can set `Model Directory`, this parameter uses path which set in your `config.php` file.

**Comment by hugo9099** [comment]
That is (I think) the issue. This new version is not using config.php but instead uses config.ini.
Somehow is not loading correctly the configuration from the .ini file.

**Comment by sergeysviridenko** [comment]
@hugo9099 Could you provide data about model directory from your `.ini` file?

**Comment by ronindesign** [comment]
I have this same error.

Docs say to put `config.ini` in project root, this is incorrect.
WebTools wouldn't read config.ini until I placed at `app/config/config.ini`

After this, my database settings are being correctly read from `config.ini`, and at least now the page is not blank / white and loads.
However I get error:
> Sorry, WebTools doesn't know where the models directory is. Please add to `application` section `modelsDir` param with real path.

I've tried changing the section in my config.ini from `[phalcon]` to `[application]` and defined real, absolute path to `/var/www/project/app/models`, but no change.

My guess is the `config.ini` is not being checked for application vars, and is instead using `config.php` for whatever reason (defaults, fall back config, etc).

However, also in my `app/config/config.php`, I've also configured `modelsDir` with real, absolute path, and still no luck.

I've checked permissions and any other file level configurations, but for whatever reason, WebTools doesn't think the path is valid, or is using the wrong value / empty value for `modelsDir`.

For reference here is my config.ini and config.php:

**app/config/config.ini**
```
defined('BASE_PATH') || define('BASE_PATH', getenv('BASE_PATH') ?: realpath(dirname(__FILE__) . '/../..'));
defined('APP_PATH') || define('APP_PATH', BASE_PATH . '/app');

return new \Phalcon\Config([
    'database' => [
        'adapter'     => 'Mysql',
        'host'        => 'localhost',
        'username'    => user,
        'password'    => pass,
        'dbname'      => testdb,
        'charset'     => 'utf8mb4',
    ],
    'application' => [
        'appDir'         => APP_PATH . '/',
        'controllersDir' => APP_PATH . '/controllers/',
        'modelsDir'      => APP_PATH . '/models/',
        'migrationsDir'  => APP_PATH . '/migrations/',
        'viewsDir'       => APP_PATH . '/views/',
        'pluginsDir'     => APP_PATH . '/plugins/',
        'libraryDir'     => APP_PATH . '/library/',
        'cacheDir'       => BASE_PATH . '/cache/',

        // This allows the baseUri to be understand project paths that are not in the root directory
        // of the webpspace.  This will break if the public/index.php entry point is moved or
        // possibly if the web server rewrite rules are changed. This can also be set to a static path.
        //'baseUri'        => preg_replace('/public([\/\\\\])index.php$/', '', $_SERVER["PHP_SELF"]),
        //'baseUri'        => preg_replace(['/public([\/\\\\])index.php$/','/webtools.php/'], '', $_SERVER["PHP_SELF"]),
        'baseUri' => '/'
    ]
]);
```

**app/config/config.ini**
```
[database]
adapter = mysql
host = localhost
username = user
password = pass
dbname = testdb
port = 3306
charset = utf8mb4

[application]
appDir         = '/var/www/project/app/'
controllersDir = '/var/www/project/app/controllers/'
modelsDir      = '/var/www/project/app/models/'
migrationsDir  = '/var/www/project/app/migrations/'
viewsDir       = '/var/www/project/app/views/'
pluginsDir     = '/var/www/project/app/plugins/'
libraryDir     = '/var/www/project/app/library/'
cacheDir       = '/var/www/project/app/cache/'
baseUri        = '/'
```

**Comment by ronindesign** [comment]
Looks like I was victim of the documentation again...
Removing `'` (single quote) from all paths fixed my issue and entries are being used correctly.
