### ISSUE TITLE
Scaffold - some first characters in controller are incorrectly capitalized

### ISSUE THREAD

**Issue by midem** [phalcon/phalcon-devtools#1078]
### Expected and Actual Behavior

I ran command **phalcon scaffold users** which created UsersController.php with $Users, $User, $User->Email (expected $users, $user, $user->email).
It is not possible to create an user or see data in search result using generated code.

Minimal script to reproduce the issue can be found in Phalcon Cookbook, chapter 2.

### Details

* System info and versions (if possible): Linux 1 4.4.0-91-generic 114~14.04.1-Ubuntu SMP Wed Aug 9 08:47:26 UTC 2017 x86_64
* Phalcon Framework version: 3.2.1
* Phalcon DevTools version: 3.2.2 (but 3.2.0 is  shown)
* PHP Version: 7.1.8-1+ubuntu14.04.1+deb.sury.org+1
* Operating System: xubuntu 14.04
* Server: Apache
* Other related info: Mysql

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.
