### ISSUE TITLE
Pear repo is old

### ISSUE THREAD

**Issue by blackbunny** [phalcon/phalcon-devtools#109]
Hello,
pear repo version is 0.8.0

**Comment by rianorie** [comment]
@phalcon ping.. this seems like one for you, or at least you'll know who to delegate this to :)

**Comment by sergeyklay** [comment]
@theDisco ping

**Comment by sergeyklay** [comment]
@theDisco

**Comment by sergeyklay** [comment]
Closed because of the long lack of feedback. Will be reopen back as needed.
