### ISSUE TITLE
Problem with migration system

### ISSUE THREAD

**Issue by mikhailmakarov** [phalcon/phalcon-devtools#1100]
### Problem with migration system

> 1. Wrong getting current migration version.

I generated migrations and now I have this list of versions:
1.0.0
1.0.1
1.0.10
1.0.11
1.0.12
1.0.2
1.0.3
1.0.4
1.0.5
1.0.6
1.0.7
1.0.8
1.0.9

On line 229 in file ./phalcon-devtools/scripts/Phalcon/Migrations.php:
```php
$initialVersion = self::getCurrentVersion($options);
```
method getCurrentVersion returns 109, but my version is 1.0.12. It's because the method gets the last string from the file. Dev-tool generated wrong positions of versions after migration run in this file.

> 2. Wrong comparison of versions.

On line 239 in file ./phalcon-devtools/scripts/Phalcon/Migrations.php:
```php
if ($finalVersion->getStamp() < $initialVersion->getStamp()) {
```
There is method getStamp. It returns int value of version. And for versions 1.1.0 and 1.0.10  it returns the same value = 110, that is not correct.

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. I'll plan to release 3.2.5 in next hours. Feel free to open a new issue if the problem appears again. Thank you for contributing.
