### ISSUE TITLE
Creating project in Phalcon 3.2.2 is php version specific i.e. php 5.6 or php 7.0

### ISSUE THREAD

**Issue by bhupender005** [phalcon/phalcon-devtools#1106]
In short : So if I install php5-phalcon (3.2) on local machine with php 5.6, can I easily move code to machine with php7.0 or is code version specific?

Detail scenario :

Local machine has following configuration :

Ubuntu 14.04
PHP 5.6
Phalcon 3.2.2 (installed using command php5-phalcon)
Phalcon devtools 3.2.5

Docker Image / Server Image has following config :

Ubuntu 16.04
PHP 7.0
Phalcon 3.2.2 (installed using command php7.0-phalcon)
Phalcon devtools 3.2.5

My concern here is that if I create skeleton and work on that using phalcon at local machine, will those same files and skeleton work on Docker/Server machine.

**Comment by sergeyklay** [comment]
There is no difference in codebase between `Phalcon 3.2 compiled for PHP 5` and `Phalcon 3.2 compiled for PHP 7` (at least at user land). Also as I know we don't use PHP version specific stuff in DevTools. The same code should work well for PHP 5 as well for PHP 7.  Anyway feel free to open a new issue if any problem appears.
