### ISSUE TITLE
Scaffold - some first characters in controller are incorrectly capitalized

### ISSUE THREAD

**Issue by frontman82** [phalcon/phalcon-devtools#1114]
### Expected and Actual Behavior

I run the command **php scaffold products** which created the controller with the first letter of the public vars in capitals
$product->Name = $this->request->getPost("name");
$product->Price = $this->request->getPost("price");
$product->Quantity = $this->request->getPost("quantity");
_expected_
$product->name = $this->request->getPost("name");
$product->price = $this->request->getPost("price");
$product->quantity = $this->request->getPost("quantity");

The example can be found in the devtools-usage example
https://docs.phalconphp.com/en/3.2/devtools-usage

### Details

* System info and versions (if possible): (`phalcon info`)
* Phalcon Framework version: 3.2.2
* PHP Version: 5.6.31
* Operating System: CentOS
* Server: Apache
* Other related info (Database, table schema): MariaDB

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
