### ISSUE TITLE
error while creating controller with command line

### ISSUE THREAD

**Issue by nadorator** [phalcon/phalcon-devtools#1115]
When generating scaffolding for tables with command line like:

```
C:\web\tubobox>phalcon scaffold --table-name=news --template-engine=volt

Phalcon DevTools (3.2.3)

C:\web\tubobox/app/controllers\NewsController.php
C:\web\tubobox/app/views/layouts\news.volt
C:\web\tubobox/app/views/news\index.volt
C:\web\tubobox/app/views/news\search.volt
C:\web\tubobox/app/views/news\new.volt
C:\web\tubobox/app/views/news\edit.volt
```
we get an error in the Controller generated. All properties of the news models  were with uppercase whereas the model itself is in lowercase in function saveAction and createAction.

The SQL code is here:

```sql
CREATE TABLE `news` (
  `id` int(11) NOT NULL,
  `body` text NOT NULL,
  `title` varchar(2048) NOT NULL DEFAULT '',
  `video` text NOT NULL,
  `picture` varchar(2048) NOT NULL DEFAULT '',
  `status` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

**Comment by sergeyklay** [comment]
@nadorator Could you please provide the generated code

**Comment by nadorator** [comment]
Here is the generated code as you can see the fields names are wrong because they have a capitalized first letter, as in the pull request you already have, the problem is the Text:camelize functionin the scaffold procedure  that does include this unecessary capitalisation because the camelize function should be use for class name or controller name camelisation but not for members/fields/actions name. The camelize function should be updated. To support both format for exemple MyNew for class name and myField for fields name.

`public function createAction()
    {
        if (!$this->request->isPost()) {
            $this->dispatcher->forward([
                'controller' => "news",
                'action' => 'index'
            ]);

            return;
        }

        $new = new News();
        $new->Body = $this->request->getPost("body");
        $new->Title = $this->request->getPost("title");
        $new->Video = $this->request->getPost("video");
        $new->Picture = $this->request->getPost("picture");
        $new->Status = $this->request->getPost("status");
        

        if (!$new->save()) {
            foreach ($new->getMessages() as $message) {
                $this->flash->error($message);
            }

            $this->dispatcher->forward([
                'controller' => "news",
                'action' => 'new'
            ]);

            return;
        }

        $this->flash->success("new was created successfully");

        $this->dispatcher->forward([
            'controller' => "news",
            'action' => 'index'
        ]);
    }`

**Comment by nadorator** [comment]
as on phalcon documentation https://docs.phalconphp.com/en/3.2/api/Phalcon_Text   camelize function should not be used for members in the controller scaffolding.  Instead you should use the field of the model as is. I will also do a test tomorrow with a model field name in the database like `key_test-one`.

**Comment by sergeysviridenko** [comment]
@nadorator you're right `Text::camelize` returns `FooBar` value. For this we\he created new method `Utils::lowerCamelizeWithDelimiter` can return `fooBar`. I fixed this problem yesterday. Could you update your devtools? 
I've created table `news` and controller looks good.
```
$new->video = $this->request->getPost("video");
$new->picture = $this->request->getPost("picture");
$new->status = $this->request->getPost("status");
```
