### ISSUE TITLE
White Page on Webtools.php

### ISSUE THREAD

**Issue by n4ndo** [phalcon/phalcon-devtools#1132]
> 
I create a new project with the command for test webtools (Webtools.php and Webtools.config have no modification)

`phalcon project --name=newproject --enable-webtools `

All works fine, but, when i go to localhost/newproject/webtools.php i see this:

> 
![image](https://user-images.githubusercontent.com/820868/31962012-f9efa79c-b8c1-11e7-9936-08282591d24a.png)

devtools.log

> Tue 24 20:58:04 DESKTOP-NHQ php: [NOTICE] E_NOTICE: Undefined property: Phalcon\Di\FactoryDefault::$di in C:\phalconphp\vendor\phalcon\devtools\scripts\Phalcon\Initializable.php on line 692
> Tue 24 20:58:04 DESKTOP-NHQ php: [ERROR] Uncaught exception: Argument 1 passed to Phalcon\Di\Injectable::setDI() must implement interface Phalcon\DiInterface, null given in C:\phalconphp\vendor\phalcon\devtools\scripts\Phalcon\Initializable.php on line 692

### Details

* System info and versions (if possible):
Phalcon DevTools Version: 3.2.8
Phalcon Version: 3.2.4
AdminLTE Version: 2.3.6
* PHP Version: 
 7.1.10
* Operating System:
Windows
* Server: 
Apache, xampp
* Other related info (Database, table schema):
MySQL

**Comment by sergeyklay** [comment]
Did you use php as fast cgi?

**Comment by n4ndo** [comment]
hello @sergeyklay  Well this is clean xampp installation, so not sure, let me check.

**Comment by sergeyklay** [comment]
I'm pretty sure this issue related to https://github.com/phalcon/cphalcon/issues/12056
Let's use original issue.

**Comment by n4ndo** [comment]
Just not that i install fcgi and the problem persist, swich to WTServer.

**Comment by sergeyklay** [comment]
@n4ndo Fixed in the [latest stable release](https://github.com/phalcon/phalcon-devtools/releases/tag/v3.2.9).  Thank you for the report, and for helping us make Phalcon better.
