### ISSUE TITLE
Difference between 'all-models' and 'model' commands with the file name.

### ISSUE THREAD

**Issue by Mateozmaldonado17** [phalcon/phalcon-devtools#1135]
When i download my entity from my db with the command 'all-models' this generates one php file, but its different with  the 'phalcon model'. for example:

with 'phalcon all-models' it downloads 'MyModel.php' and 'phalcon model mymodel' downloads 'Mymodel.php' ¿Why?

**Comment by sergeysviridenko** [comment]
@Mateozmaldonado17 I couldn't reproduce this bug. I've created table `mymodel` and generate model. All works fine. I've got both of `Mymodel.php` files. Which version of devtools do you use?

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
