### ISSUE TITLE
PR #1134 leads to Fatal PHP error

### ISSUE THREAD

**Issue by Nyde** [phalcon/phalcon-devtools#1136]
### Expected and Actual Behavior

> **webtools.php shows blank page instead of Webtools Board, with fatal error**

```php
Sun 29 20:36:06 php: [ERROR] Uncaught exception: Using $this when not in object context in D:\phalcon-devtools\scripts\Phalcon\Initializable.php on line 254
Sun 29 20:36:06 php: [INFO] E_DEPRECATED: Non-static method Phalcon\Bootstrap::getCacheDir() should not be called statically in D:\phalcon-devtools\scripts\Phalcon\Initializable.php on line 227
```
### Reproducing

Create project with 
```php
phalcon create-project PROJECT --enable-webtools
```
with or without any other parameters.

Then access http://localhost/PROJECT/webtools.php

For discussion on this, see my forum posts;

Initial: https://forum.phalconphp.com/discussion/17165/webtools-blank-page-on-webtoolsphp
Error: https://forum.phalconphp.com/discussion/17165/webtools-blank-page-on-webtoolsphp#C51843
Workaround: https://forum.phalconphp.com/discussion/17165/webtools-blank-page-on-webtoolsphp#C51889

It seems like #1134 broke this, switching to an older version fixed it.

### Details

* System info and versions (if possible):

```Phalcon DevTools (3.2.8)

Environment:
  OS: Windows NT 10.0 build 16299 (Windows 10) i586
  PHP Version: 7.0.6
  PHP SAPI: cli
  PHP Bin: D:\xampp7.0\php\php.exe
  PHP Extension Dir: C:\php\ext
  PHP Bin Dir: C:\php
  Loaded PHP config: D:\xampp7.0\php\php.ini
Versions:
  Phalcon DevTools Version: 3.2.8
  Phalcon Version: 3.2.3
  AdminLTE Version: 2.3.6
```

* Server: Apache
* Other related info

As you can see I got 3.2.3, but it won't work on 3.2.4 either.

**Comment by sergeyklay** [comment]
cc: @sergeysviridenko

**Comment by sergeysviridenko** [comment]
@Nyde could you try latest version?

**Comment by sergeysviridenko** [comment]
I suppose close this issue.

**Comment by Nyde** [comment]
Working as intended, thank you!
