### ISSUE TITLE
Webtools does not create css.

### ISSUE THREAD

**Issue by Niko9911** [phalcon/phalcon-devtools#1147]
### Expected and Actual Behavior

> **Dev-Tools do not create CSS. JS is generated, but not CSS.**

> Provide minimal script to reproduce the issue

```php
phalcon.php webtools enable
```

### Details

* System info and versions (if possible): (`phalcon info`)
`Phalcon DevTools (3.2.11)

Environment:
  ```
OS: Linux 4.8.0-53-generic #56~16.04.1-Ubuntu SMP Tue May 16 01:18:56 UTC 2017 x86_64
  PHP Version: 7.1.11-1+ubuntu16.04.1+deb.sury.org+1
  PHP SAPI: cli
  PHP Bin: /usr/bin/php7.1
  PHP Extension Dir: /usr/lib/php/20160303
  PHP Bin Dir: /usr/bin
  Loaded PHP config: /etc/php/7.1/cli/php.ini
Versions:
  Phalcon DevTools Version: 3.2.11
  Phalcon Version: 3.2.2
  AdminLTE Version: 2.3.6
```
* Phalcon Framework version: (`php --ri phalcon`)
```
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.2
Build Date => Sep  8 2017 05:04:34
Powered by Zephir => Version 0.9.9-868cb1f92b

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

```

**Comment by sergeysviridenko** [comment]
I propose to close this issue.

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Comment by Niko9911** [comment]
@sergeyklay Nothing were fixed.... It's still same issue after updating...

**Comment by sergeysviridenko** [comment]
@Niko9911 Have you updated your devtools after last merge?

**Comment by Niko9911** [comment]
@sergeysviridenko I updated my devtools 5 days ago. I will update it again asap.

**Comment by sergeysviridenko** [comment]
@Niko9911 I still can't reproduce it. Could you take a look any errors in php log?

**Comment by Niko9911** [comment]
@sergeysviridenko 
Well, I had small brain fart... I did download the "update" from 3.1.x branch... Sorry for inconvenience!

**Comment by Niko9911** [comment]
And issue after that was fixed. It was with /tmp/phalcon permissions...

**Comment by CeRBeR666** [comment]
stiil same on me. I pull 3.2.x but nothing changed

**Comment by Niko9911** [comment]
@CeRBeR666 Any logs?

**Comment by CeRBeR666** [comment]
This is my phalcon devtools version

```
C:\Users\Volkan>phalcon info

Phalcon DevTools (3.2.11)

Environment:
  OS: Windows NT HOUSTON 10.0 build 15063 (Windows 10) AMD64
  PHP Version: 5.6.31
  PHP SAPI: cli
  PHP Bin: F:\wamp64\bin\php\php5.6.31\php.exe
  PHP Extension Dir: C:\php\ext
  PHP Bin Dir: C:\php
  Loaded PHP config: F:\wamp64\bin\php\php5.6.31\php.ini
Versions:
  Phalcon DevTools Version: 3.2.11
  Phalcon Version: 3.2.4
  AdminLTE Version: 2.3.6
```

This is my phalcon.bat config 

```
@echo off
                  
set PTOOLSPATH=F:\phalcon-tools\
php %PTOOLSPATH%phalcon.php %* 
```
This is my config.php base_uri array

`'baseUri'        => preg_replace('/public([\/\\\\])index.php$/', '', $_SERVER["PHP_SELF"]),`

But 
![phalcon1](https://user-images.githubusercontent.com/504973/33239313-38eea0a8-d2b0-11e7-8e06-7b3022517188.png)
![phalcon2](https://user-images.githubusercontent.com/504973/33239321-6fb7ea72-d2b0-11e7-9c5e-7306b6ba2fb9.png)

**Comment by regis123** [comment]
$root = new SplFileInfo($path . 'public' . DS);
        $fsUtils->setDirectoryPermission($root, ['js' => 0777, 'css' => 0777]);

        $tools = rtrim(str_replace(["\\", '/'], DS, PTOOLSPATH), DS);

        copy($tools . DS . 'webtools.php', $path . 'public' . DS . 'webtools.php');

**Comment by regis123** [comment]
I tested on wamp64 and xampp32, unsuccessfully

**Comment by sergeysviridenko** [comment]
@CeRBeR666 Do you see `.js` file in your HTML tree?

**Comment by sergeysviridenko** [comment]
@regis123 I still can't reproduce this issue. I've created new project - all work fine. 

Could you provide more information?

**Comment by CeRBeR666** [comment]
@sergeysviridenko hi sergey i see js file in my html but path doesn't correct 
my js path 
`http://localhost/js/webtools.js?v=3.2.11`
But i try on fresh setup on phalcon and i never change any code. 
Thank you.

**Comment by sergeysviridenko** [comment]
@CeRBeR666 could you provide your `config` file. Do you use xampp or other? Which web-server do you use?

**Comment by regis123** [comment]
I think if you make virtualHost in wamp64 and other steps:

****http://localhost/add_vhost.php***

1- I create virtualHost Name (http://nameproject/)

2-Change... to 'baseUri' => '/',

3-Tool.php = $fsUtils->setDirectoryPermission($root, ['js' => 0777]);

**Comment by sergeysviridenko** [comment]
@regis123 I think too.

**Comment by CeRBeR666** [comment]
@regis123 its working. I make a vhost on my wamp server and phalcon tools working werry well. 
Thank you.
U can closed the issue ?
