### ISSUE TITLE
could not find driver

### ISSUE THREAD

**Issue by atianbang** [phalcon/phalcon-devtools#1149]
Phalcon DevTools (3.2.8)
when i run command ```phalcon model --name test ```,just throw the error ```could not find driver```,
i can get data from Di->db,is there some config for DevTools?

by the way,i use docker ,mysql dbhsot is not localhost or 127.0.0.1,is there need something to change?

anyone can help me?thx!

**Comment by chilimatic** [comment]
that usually means you don't have the pdo|mysql extensions compiled / installed. if you're executing inside of the docker container try to check if you got the extensions installed/enabled

usually they are in /etc/php/<here-different-linux-distros-have-different-paths>

**Comment by atianbang** [comment]
you notice me.just run the command and fetch data in two different container.i will have a try

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
