### ISSUE TITLE
Problem with webtools

### ISSUE THREAD

**Issue by virendpatel0** [phalcon/phalcon-devtools#1152]
I have installed Phalcon on FreeBSD 11 with out any error. Phalcon running without any error. I did install Phalcon-devtools through github. Followed all step I think. 

![untitled1](https://user-images.githubusercontent.com/33887664/33110491-cc0b6f98-cf0d-11e7-9dcd-b4a87ea45710.png)

When I click on link just blank page.

![untitled2](https://user-images.githubusercontent.com/33887664/33110550-27c090de-cf0e-11e7-89e9-eca12808066e.png)

I am newbie to Phalcon and Phalcon-Devtools please help me.

**Comment by sergeyklay** [comment]
@ virendpatel0 Is there any related web-server/php logs?

**Comment by sergeyklay** [comment]
@virendpatel0 Is there any related web-server/php logs?

**Comment by virendpatel0** [comment]
Nginx Access log

27.0.0.1 - - [22/Nov/2017:16:45:49 -0600] "GET /webtools.php HTTP/1.1" 200 6465 "-" "Mozilla/5.0 (X11; FreeBSD amd64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [22/Nov/2017:16:45:49 -0600] "GET /css/webtools.css?v=3.2.11 HTTP/1.1" 200 253410 "http://127.0.0.1/webtools.php" "Mozilla/5.0 (X11; FreeBSD amd64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [22/Nov/2017:16:45:49 -0600] "GET /js/webtools.js?v=3.2.11 HTTP/1.1" 200 607472 "http://127.0.0.1/webtools.php" "Mozilla/5.0 (X11; FreeBSD amd64; rv:55.0) Gecko/20100101 Firefox/55.0"
127.0.0.1 - - [22/Nov/2017:16:45:55 -0600] "GET /webtools.php?_url=/controllers/generate HTTP/1.1" 200 143 "http://127.0.0.1/webtools.php" "Mozilla/5.0 (X11; FreeBSD amd64; rv:55.0) Gecko/20100101 Firefox/55.0"

Nginx Error log is blank

php error log is empty too.

Thanks in advance for your help.

**Comment by sergeysviridenko** [comment]
@virendpatel0 Do you use latest stable version. Could you try to update? I can't reproduce this issue.

**Comment by sergeysviridenko** [comment]
@virendpatel0 as I can see on the second pic you've got URL - `localhost/webtools.php`. Could you provide your config

**Comment by virendpatel0** [comment]
With FreeBSD and Nginx please give me installation procedure with config for webtools. I might have missed some steps possibly.  Thanks in advance.

**Comment by sergeysviridenko** [comment]
Do you use xampp or other? Could you provide your config file and index page URL

**Comment by sergeyklay** [comment]
@virendpatel0 We'll need:
* Application config (please remove passwords or private data)
* Nginx configuration (mostly `server` section)
