### ISSUE TITLE
Code hints are incomplete

### ISSUE THREAD

**Issue by junliuxian** [phalcon/phalcon-devtools#1153]
Phalcon is a very good framework, and I like it for it. When I use phalcon-devtools to generate prompt, there is no return value and no parameter explanation. Can strengthen it?

**Comment by sergeyklay** [comment]
@junliuxian Could you please explain a bit more?

**Comment by junliuxian** [comment]
gen-stubs.php generated phalcon code, there is no method description, such as parameters and return value description, resulting in PHPStorm does not recognize

**Comment by sergeyklay** [comment]
Ah :) We use `zephir stubs` command for that. Personally I never used it. I think we need to remove this file from the repository to avoid confusion.

**Comment by sergeysviridenko** [comment]
@junliuxian Could you provide an example? I checked if method described in zephir, it described in stubs.

**Comment by junliuxian** [comment]
Sorry, I failed to shut it down in time. Actually, this problem has been solved.
