### ISSUE TITLE
webtools without css - xampp with PHP Version 7.1.7

### ISSUE THREAD

**Issue by regis123** [phalcon/phalcon-devtools#1154]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**
![phalconwebtools without css](https://user-images.githubusercontent.com/3351895/33338266-aed345d2-d45c-11e7-9c7e-b1a3f23e6449.PNG)
![webtools phalcon without css](https://user-images.githubusercontent.com/3351895/33338387-1c358e64-d45d-11e7-9f30-5ac87f48065c.PNG)

> Provide output if related

```php
// paste output here
```
> Provide minimal script to reproduce the issue

```php
// paste code
```

### Details
Where i need to change in my code.  Help...
* System info and versions (if possible): (`phalcon info`)
* Phalcon Framework version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment]
Refs:
* https://github.com/phalcon/phalcon-devtools/issues/1152
* https://github.com/phalcon/phalcon-devtools/issues/1147

**Comment by sergeysviridenko** [comment]
@regis123 could you provide more bit information and any steps to reproduce. It works fine for me. 
OS: Ubuntu 16-04
Phalcon DevTools Version: 3.2.11
Phalcon Version: 3.3.0

**Comment by regis123** [comment]
![phalconinvo](https://user-images.githubusercontent.com/3351895/33434771-6f391b74-d5c7-11e7-92fa-2bcdda6fd9f0.PNG)

with virtualhost create, now is 100%. No more problems, tks guys!

**Comment by sergeysviridenko** [comment]
@regis123 could we close this issue?

**Comment by regis123** [comment]
All right!

**Comment by regis123** [comment]
sergeysviridenko,

Yes ..! You Can close!

**Comment by sergeysviridenko** [comment]
@regis123 Could you give more information about how you were able to solve this issue?

**Comment by regis123** [comment]
WampServe 64, windows 7, php 5.6.  
1- I create virtualHost Name (http://invo/)
2-Change... to  'baseUri'        => '/', 
3-Tool.php =  $fsUtils->setDirectoryPermission($root, ['js' => 0777]);
test create : TestController , fine! 
Steps 2 e 3 i read in here.
Thats all!

**Comment by sergeysviridenko** [comment]
@regis123 Thank you very much.

**Comment by amsharma9** [comment]
@sergeysviridenko I don't think this is resolved. Even #1152 is the same issue. To recreate create a blank project with latest devtools on Wamp on Windows:
```
phalcon project test --enable-webtools --use-config-ini
```
Go to http://localhost/test. It will show you a page without CSS.
Doesn't show the page without `staticUri`. See 

- [Css webtools 3.1.2 is not loaded](https://forum.phalconphp.com/discussion/15931/css-webtools-312-is-not-loaded) 
- [Webtools can not load css if using different baseUri](https://forum.phalconphp.com/discussion/15111/webtools-can-not-load-css-if-using-different-baseuri)

are all same issue. Just create any project with webtools enabled and by default webtools doesn't work without specifying `staticUri` in the `config.ini` file.

**Comment by sergeysviridenko** [comment]
@amsharma9 could you open new issue and provide steps to reproduce?
