### ISSUE TITLE
Phalcon 3.2 "ide/stubs/Phalcon" directory are missing

### ISSUE THREAD

**Issue by FlameStorm** [phalcon/phalcon-devtools#1155]
Good day, Phalcon team!

The phalcon-devtools/ide/stubs/Phalcon directory with all of it content are missing in branch 3.2.x .

We are moving to Phalcon 3.2 and changing to branch of phalcon-devtools to 3.2.x there are many problems in typehinting. But it was all good on phalcon-devtools 3.1.x branch.

Please, fix this asap. 
Thank you!

* Phalcon Framework version: 3.2.4
* PHP Version: 5.6 x64
* Operating System: Windows 7 x64
* Server: Nginx + Apache x64
* Other related info: Mysql 5.7 x64 and other things

**Comment by selden1992** [comment]
phpstom ide not tip

**Comment by oscarmolinadev** [comment]
Stubs have a new repo:

https://github.com/phalcon/ide-stubs

**Comment by FlameStorm** [comment]
Does it have any matter? See above.

For me I just forced to take phalcon/cphalcon repository, fetch latest stable (3.2.4) cphalcon to local, modify constant `CPHALCON_DIR` at row in file `ide/gen-stubs.php` to valid for me path `__DIR__ . '/../../../../../cphalcon/ext/'` and run `php ide/gen-stubs.php`. It made the folder `ide/3.2.4/Phalcon` with all need classes. 
So, _my_ typehinting now fine. But - any other developer who wants to dev under Phalcon 3.2 nor will take the same adventures nor just go out of 3.2 and go to 3.1 branch without this problem.

**Comment by FlameStorm** [comment]
@oscarmolinadev thank for a hint! May be it will be useful. But it is not obvious. 
May be it's a good idea to add info about `Stubs` repo to `devtools` Readme once "phalcon devtools politics about Stubs" is changed (as I understand this)?

**Comment by sergeyklay** [comment]
https://github.com/phalcon/phalcon-devtools/pull/398
