### ISSUE TITLE
Problem with camelize models

### ISSUE THREAD

**Issue by Edreadman** [phalcon/phalcon-devtools#1156]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> When generating models the dev tools builds it with the camelize option even if i didn't add the option, i got a field named ProducType and when i generate the model it outputs productType, making the  findFirstBy<Property> and the get-set methods unable to work.

> Provide output if related
```php
 /**
     * field name is ProductType and it outputs like productType
     * @var integer
     * @Column(type="integer", length=11, nullable=false)
     */
    protected $productType; // <---- here

/**
     * Method to set the value of field productType
     *
     * @param integer $productType
     * @return $this
     */
    public function setProductType($productType)
    {
        $this->productType = $productType; // <---- here

        return $this;
    }
```
> Provide minimal script to reproduce the issue

```php
phalcon model --products --get-set --force --mapcolumn
```

### Details

* System info and versions (if possible): (`phalcon info`)
* Phalcon Framework version: 3.2.4
* PHP Version: 7.1
* Operating System: RHEL7
* Server: Apache
* Other related info (Database, table schema): MYSQL 5.x

**Comment by Edreadman** [comment]
Found the problem in phalcon-devtools\scripts\Phalcon\Builder\Model.php on lane 436

Change this:
$fieldName = Utils::lowerCamelizeWithDelimiter($field->getName(), '-', false);

For:
$fieldName = Utils::lowerCamelizeWithDelimiter($field->getName(), '-');

then my field name "ProductType" outputs " $this->ProductType = $ProductType;" instead of "$this->productType = $productType;"

**Comment by sergeysviridenko** [comment]
@Edreadman method `Utils::lowerCamelizeWithDelimiter()` has third default param is `false`. 
If I understood correctly you 'd like to have variable like `$ProductType`. This isn't default name of variable. We always use $productType. If you'd to have `$ProductType`, you can change this manually.

**Comment by sergeysviridenko** [comment]
@Edreadman this isn't bug. It is normal and expected behavior, so I propose to close this issue.
