### ISSUE TITLE
Hardcoding schema in init

### ISSUE THREAD

**Issue by amsharma9** [phalcon/phalcon-devtools#1162]
DevTools hard codes `schema` in `initialize()` function of generated models. Is this a good idea? Hard coding database name into the code creates so many issues and reduces flexibility. Does it serve any purpose? See this query [Phalcon tools setSchema by default now?](https://forum.phalconphp.com/discussion/15823/phalcon-tools-setschema-by-default-now) on the forum.

Is there a way to avoid this.

**Comment by sergeyklay** [comment]
@amsharma9 Could you please provide typical not neatly generated initialize method?

**Comment by amsharma9** [comment]
Here is a sample of code generated:

```
    /**
     * Initialize method for model.
     */
    public function initialize()
    {
        $this->setSchema("testdb");
        $this->setSource("co_bank_m");
    }
```

**Comment by sergeyklay** [comment]
@amsharma9 The last thing I need - steps to reproduce :)

**Comment by amsharma9** [comment]
Normal DevTools command for model generation. It generates this code with or without any options AFAIK.
```
phalcon model --name co_bank_m --get-set --namespace=Baseapp\Models --mapcolumn --extends=ModelBase
```

**Comment by sergeysviridenko** [comment]
@amsharma9 If I understood correctly, you would like to create model without `$this->setSchema("testdb");` in `initialize`. you can add option `--schema=''`.

Could you try run 
```
phalcon model --name co_bank_m --get-set --namespace=Baseapp\Models --mapcolumn --extends=ModelBase --schema=''
```

**Comment by amsharma9** [comment]
@sergeysviridenko It didn't work. It is looking for the table `co_bank_m` in blank database and it gives error:

```
 Error: Table "co_bank_m" does not exist.
```
If I change `schema` to my DB name `testdb` then it goes through.

**Comment by sergeysviridenko** [comment]
@amsharma9 Look I have table `member`. I've run `phalcon model --name member --get-set --namespace=Baseapp\Models --mapcolumn --extends=ModelBase --schema=''` and all works fine. Model has been created without `$this->setSchema("testdb");`.
Could you try to use this command with created table.

**Comment by amsharma9** [comment]
Ok, what you wrote works but I had to remove the empty quotes. With single quotes after schema it still gave `ERROR: Table "co_bank_m" does not exist.`. I am on Windows 7 using Wamp so could that be a reason for it not to work. This is what I gave on command line when it worked:
```
phalcon model --name your_table_name --get-set --namespace=Baseapp\Models --mapcolumn --extends=ModelBase --schema=
```

**Comment by amsharma9** [comment]
I have rechecked and tried with other tables, the tables exist. When I give `--schema=` it works but when I give `--schema=''`, it doesn't work.

**Comment by amsharma9** [comment]
@sergeysviridenko The code was generated perfectly, when using `--schema=""` there was no `setSchema()` call in `initialize()`- as expected.
