### ISSUE TITLE
Webtools page doesn't use CSS by default for any new project

### ISSUE THREAD

**Issue by amsharma9** [phalcon/phalcon-devtools#1164]
Webtools doesn't show the proper page without `staticUri` being specified in `config.ini`. See

- [Css webtools 3.1.2 is not loaded](https://forum.phalconphp.com/discussion/15931/css-webtools-312-is-not-loaded) 
- [Webtools can not load css if using different baseUri](https://forum.phalconphp.com/discussion/15111/webtools-can-not-load-css-if-using-different-baseuri)

are all same issue. Just create any project with webtools enabled and by default webtools doesn't work without specifying `staticUri` in the `config.ini` file.

To recreate create a blank project with latest devtools on Wamp on Windows:
```
phalcon project test --enable-webtools --use-config-ini
```
Go to http://localhost/test/webtools.php. It will show you a raw page without CSS. Check the path of CSS file in the source of that page, it is incorrect as mentioned in the forum posts above.

**Comment by sergeysviridenko** [comment]
@amsharma9 could you try to set virtual host? [Here](https://github.com/phalcon/phalcon-devtools/issues/1147) is solution to resolve problem like this.
