### ISSUE TITLE
Incomplete annotation definition in Model generator

### ISSUE THREAD

**Issue by alexbusu** [phalcon/phalcon-devtools#1169]
Generating Models with annotations does not specify the column name on the `@Column` property. 

Therefore having camelized Model properties will result in column map mismatch.
Using Annotations Model Metadata Strategy (AMMS) make the Model->columnMap() method useless, as the AMMS will parse Model annotations and [look for "column" parameter](https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model/metadata/strategy/annotations.zep#L325) in `@Column` property.

### Details

* DevTools Version: 3.2.11
* Phalcon Framework version: 3.2.4
* PHP Version: 7.0.25
* Operating System: Ubuntu
* Server: Nginx

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/phalcon-devtools/issues/589
