### ISSUE TITLE
version show "Phalcon DevTools (1.3.2)" ?

### ISSUE THREAD

**Issue by javacty** [phalcon/phalcon-devtools#1177]
When I  git clone git://github.com/phalcon/phalcon-devtools.git or download from release (v3.2.12) and install,  the version both show 1.3.2 ?

**Comment by sergeysviridenko** [comment]
@javacty could you provide a little bit more information and steps to reproduce?

**Comment by javacty** [comment]
ok
ubuntu 17.10 x64
php -v
PHP 7.2.1-1+ubuntu17.10.1+deb.sury.org+1 (cli) (built: Jan  5 2018 13:55:19) ( NTS )
php -m
[PHP Modules]
calendar
Core
ctype
date
dom
exif
fileinfo
filter
ftp
gettext
hash
iconv
json
libxml
mbstring
openssl
pcntl
pcre
PDO
pdo_pgsql
pgsql
phalcon7
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
volt
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
Zephir Parser
zlib

[Zend Modules]
Zend OPcache
=====================================================
cd ~
git clone git://github.com/phalcon/phalcon-devtools.git
cd phalcon-devtools/
./phalcon.sh
ERROR: Phalcon extension isn't installed, follow these instructions to install it: https://docs.phalconphp.com/en/latest/reference/install.html

vim bootstrap/autoload.php
25 if (!extension_loaded('phalcon')) {
to
25 if (!extension_loaded('phalcon7')) {

ERROR: Your Phalcon version isn't compatible with Developer Tools, download the latest at: https://phalconphp.com/download

vim bootstrap/autoload.php 
134 if (Version::getId() < COMPATIBLE_VERSION) {
135     throw new Exception(
136         "Your Phalcon version isn't compatible with Developer Tools, " .
137         'download the latest at: https://phalconphp.com/download'
138     );
139 }
to
/*
134 if (Version::getId() < COMPATIBLE_VERSION) {
135     throw new Exception(
136         "Your Phalcon version isn't compatible with Developer Tools, " .
137         'download the latest at: https://phalconphp.com/download'
138     );
139 }
*/

./phalcon.sh

Phalcon DevTools (1.3.2)

Available commands:
  info             (alias of: i)
  commands         (alias of: list, enumerate)
  controller       (alias of: create-controller)
  module           (alias of: create-module)
  model            (alias of: create-model)
  all-models       (alias of: create-all-models)
  project          (alias of: create-project)
  scaffold         (alias of: create-scaffold)
  migration        (alias of: create-migration)
  webtools         (alias of: create-webtools)
  serve            (alias of: server)
  console          (alias of: shell, psysh)

**Comment by sergeyklay** [comment]
@javacty Could you please provide output of:

```bash
php --ri phalcon
```

**Comment by javacty** [comment]
php --ri phalcon
Extension 'phalcon' not present.


Phalcon7 Version => Phalcon7(Dao7)-1.3.2
Build Date => Jan 21 2018 12:42:26
Sync => enabled

Directive => Local Value => Master Value
phalcon.debug.enable_debug => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.length_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.enable_property_method => On => On
phalcon.orm.enable_auto_convert => On => On
phalcon.orm.allow_update_primary => Off => Off
phalcon.orm.enable_strict => Off => Off
phalcon.validation.allow_empty => Off => Off
phalcon.db.escape_identifiers => On => On
phalcon.cache.enable_yac => On => On
phalcon.cache.enable_yac_cli => Off => Off
phalcon.cache.yac_keys_size => 4M => 4M
phalcon.cache.yac_values_size => 64M => 64M
phalcon.xhprof.nesting_max_level => 0 => 0
phalcon.xhprof.enable_xhprof => Off => Off
phalcon.xhprof.clock_use_rdtsc => 0 => 0

**Comment by sergeyklay** [comment]
> Phalcon7(Dao7)-1.3.2

You have to install **official** latest Phalcon to use DevTools v3
