### ISSUE TITLE
scaffolder has a problem with capitalisation in field names

### ISSUE THREAD

**Issue by eokenned** [phalcon/phalcon-devtools#1178]
### Expected and Actual Behavior
Trying to scaffold a database table with Capital letters in the field names and use the resultant CRUD

The tables scaffolds without error but the resultant code has issues.

If I use --get-set then createAction() and saveAction() set all field values in the DB to null.
If I don't use --get-set when scaffolding then createAction and saveAction has no effect on existing data.

Altering my mysql create table statements so that all fieldnames are lowercase only resolves the issue.

Thanks,

Eoin

OS Windows 10
Phalcon Version 3.3.1
Devtools Version 3.2.12
PHP version 7,2

**Comment by eokenned** [comment]
I went back and checked and this problem seems to start in dev-tools v3.2.3. v3.2.2 doesn't handle --get-set at all. But 3.20 is fine and doesn't have the issue with upper-case in field names.  v3.2.0 doesn't have the issue. The issue persists in v3.2.12. Hope this helps

**Comment by eokenned** [comment]
I do think this qualifies as a bug though.

**Comment by sergeysviridenko** [comment]
@eokenned Thank you for report. Could you provide a little bit more information? I'd like to have to take a look your configuration, your data that you have at the start and the end. Steps to reproduce would very helpful.

**Comment by sergeysviridenko** [comment]
@eokenned Could you provide your controller and model?

**Comment by Jeckerson** [comment]
Fixed
