### ISSUE TITLE
.phalcon directory required when running migrations with --log-in-db

### ISSUE THREAD

**Issue by ruudboon** [phalcon/phalcon-devtools#1183]
When running 
```
phalcon migration --log-in-db --action=run
```
Phalcon ask for the creation of a .phalcon directory, don't think this is needed and would be nice if this check could be removed for automatic deployment.

**Comment by sergeysviridenko** [comment]
@ruudboon I agree with you. I'd to take into consideration your suggestion in new version of migration, but in the future devtools always be in need `.phalcon` directory.

**Comment by ruudboon** [comment]
@sergeysviridenko Ok. Not really a big issue, in my deployment of the container I'm currently just creating the dir and then run the migration but feels a bit unnecessary. Feel free to close this.

**Comment by sergeysviridenko** [comment]
@ruudboon in `.phalcon` folder devtools will put config file. There are users can modify it and save their custom configuration and connect their own modules. I hope it will be helpful.
