### ISSUE TITLE
Can't create MIGRATION_LOG_TABLE due to Index column size too large

### ISSUE THREAD

**Issue by YujiShen** [phalcon/phalcon-devtools#1190]
I try to use --log-in-db option in migration, but when run the migration, I got the error:

```
ERROR: SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
```

I think it is because I use `utf8mb4` for my database. Maybe reduce the `version` column size? Now it is 255. And it will exceed max limit for indexing.

https://github.com/phalcon/phalcon-devtools/blob/b62a35e88433c8db1d34fdf2fb7cdfef50a48403/scripts/Phalcon/Migrations.php#L447

Here is a related question on SO: [How to fix MySql: index column size too large (Laravel migrate)](https://stackoverflow.com/questions/42043205/how-to-fix-mysql-index-column-size-too-large-laravel-migrate)

Environment:
  OS: Linux de4c926a06e4 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64
  PHP Version: 7.1.9
  PHP SAPI: cli
  PHP Bin: /usr/bin/php7
  PHP Extension Dir: /usr/lib/php7/modules
  PHP Bin Dir: /usr/bin
  Loaded PHP config: /etc/php7/php.ini
Versions:
  Phalcon DevTools Version: 3.2.8
  Phalcon Version: 3.3.1
  AdminLTE Version: 2.3.6

**Comment by sergeysviridenko** [comment]
@YujiShen Could you provide a little bit more information to correct reproduce, please?

**Comment by YujiShen** [comment]
I think the key to reproduce this is to set your Character Set of database to utf8mb4. Then try to generate the migration.

**Comment by sergeysviridenko** [comment]
@YujiShen which `version` do you have? like `1.0.0`?

**Comment by YujiShen** [comment]
@sergeysviridenko Have you tried timestamp?

**Comment by sergeysviridenko** [comment]
@YujiShen nope. Could you provide all steps to reproduce?

**Comment by Jeckerson** [comment]
Fixed by decreasing size of field from 255 to 195.
