### ISSUE TITLE
correction should be made in relative links.

### ISSUE THREAD

**Issue by kumarnabin** [phalcon/phalcon-devtools#1191]
css and js file did not load while accessing project through apache  url (`localhost/<project_name>/webtools.php`) and also url concatenated each time with new link.
 I made little change in `app\config\config.php` ie. 
```php
'baseUri'        => '/', 
```
and worked fine with server `phalcon serve localhost`
with  url `localhost:8000/webtools.php`
but not totally solved for apache url.

### Details

 System info and versions : 
 Phalcon DevTools Version: 3.2.12
 Phalcon Framework version: 3.3.1
 Operating System: Windows NT DESKTOP-PJI5P86 10.0 build 16299 (Windows 10) i586
 XAMPP: 7.2.2

**Comment by sergeysviridenko** [comment]
@kumarnabin could you provide information about your problem a little bit more? Please, add full information to correct reproduce your problem.

**Comment by kumarnabin** [comment]
Is there any better idea? please reply

**Comment by sergeysviridenko** [comment]
@kumarnabin You should change defauld setting for XAMPP.
Could you try [solution](https://github.com/phalcon/phalcon-devtools/issues/1147)
