### ISSUE TITLE
Brand New Phalcon Developr Tools

### ISSUE THREAD

**Issue by sergeysviridenko** [phalcon/phalcon-devtools#1193]
Main Goals:

- [ ] Brand new plugin system
- [ ] Fully modular system
- [ ] Minimal supported PHP is v7.0
- [ ] Ability to change Devtools configuration using custom, per application configuration
- [ ] Using [ChangeLog](https://keepachangelog.com/en/1.0.0)

----

Refs:

- [Phalcon  Forum: Future of the Phalcon Devtools](https://forum.phalconphp.com/discussion/9409/future-of-phalcon-devtools)

**Comment by lajosbencz** [comment]
I might be behind current version, but it would be neat to have proper IDE hinting when generating model classes.
In particular, related model hinting.

```php
/**
 * @property \Project\Models\RobotCategory $RobotCategory
 * @property \Project\Models\RobotParts[] $RobotParts
 */
class Robot extends PhModel
{
    function initialize() {
        $this->belongsTo('Project\Models\RobotCategory', ...);
        $this->hasMany('Project\Models\RobotParts', ...);
    }
}
```

**Comment by oscarmolinadev** [comment]
It would be nice if use Phalcon\Cli\Console and help to improve it. :)

**Comment by sergeysviridenko** [comment]
@oscarmolinadev Sure. there will be used it

**Comment by sergeysviridenko** [comment]
@lajosbencz We'll take it to consideration

**Comment by Jeckerson** [comment]
Closing in favor https://github.com/phalcon/phalcon-devtools/issues/1315
