### ISSUE TITLE
"Main Navigation" links are broken in Phalcon WebTools

### ISSUE THREAD

**Issue by jbenner-radham** [phalcon/phalcon-devtools#1215]
### Expected and Actual Behavior
When I navigate to the "Main Navigation" section and expand the "Models" dropdown and click the "List all" link I expect to be taken to the "Models List" page. Instead I am taken to the Phalcon project's `index.volt` page.

### To Reproduce the Issue
1. `$ phalcon.php project example-phalcon-lab --enable-webtools --template-engine="volt"`
2. `$ cd example-phalcon-lab`
3. `$ phalcon.php serve`
4. Visit <http://localhost:8000/webtools.php>.
5. Click on "Main Navigation > Models > List all".

### Details

* System info and versions (if possible): (`phalcon info`)
      
      Phalcon DevTools (3.2.12)
      
      Environment:
        OS: Darwin ICC11327 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
        PHP Version: 7.1.16
        PHP SAPI: cli
        PHP Bin: /usr/local/Cellar/php@7.1/7.1.16/bin/php
        PHP Extension Dir: /usr/local/Cellar/php@7.1/7.1.16/lib/php/20160303
        PHP Bin Dir: /usr/local/Cellar/php@7.1/7.1.16/bin
        Loaded PHP config: /usr/local/etc/php/7.1/php.ini
      Versions:
        Phalcon DevTools Version: 3.2.12
        Phalcon Version: 3.3.0
        AdminLTE Version: 2.3.6

* Phalcon Framework version: (`php --ri phalcon`)
      
      phalcon
      
      Web framework delivered as a C-extension for PHP
      phalcon => enabled
      Author => Phalcon Team and contributors
      Version => 3.3.0
      Build Date => Jan  5 2018 15:10:04
      Powered by Zephir => Version 0.10.5-04eb3288bf

      Directive => Local Value => Master Value
      phalcon.db.escape_identifiers => On => On
      phalcon.db.force_casting => Off => Off
      phalcon.orm.events => On => On
      phalcon.orm.virtual_foreign_keys => On => On
      phalcon.orm.column_renaming => On => On
      phalcon.orm.not_null_validations => On => On
      phalcon.orm.exception_on_failed_save => Off => Off
      phalcon.orm.enable_literals => On => On
      phalcon.orm.late_state_binding => Off => Off
      phalcon.orm.enable_implicit_joins => On => On
      phalcon.orm.cast_on_hydrate => Off => Off
      phalcon.orm.ignore_unknown_columns => Off => Off
      phalcon.orm.update_snapshot_on_save => On => On
      phalcon.orm.disable_assign_setters => Off => Off

* PHP Version: (`php -v`)
      
      PHP 7.1.16 (cli) (built: Mar 31 2018 02:27:44) ( NTS )
      Copyright (c) 1997-2018 The PHP Group
      Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
          with Zend OPcache v7.1.16, Copyright (c) 1999-2018, by Zend Technologies

* Operating System:
      
      MacOS Sierra 10.12.6

* Server: Nginx | Apache | Other
      
      Other: `$ phalcon.php serve`

* Other related info (Database, table schema): 
    The issue appears to be occurring because it's generating links like this <http://localhost:8000/webtools.php/webtools.php?_url=/models/list> instead of links that work like this <http://localhost:8000/webtools.php?_url=/models/list>.

If you accept this as an issue and would like help with it I would love to try and do a pull request for this myself if possible.

P.S. Thanks for your hard work on an amazing product!

**Comment by sergeysviridenko** [comment]
I wasn't able to reproduce this issue. It works fine for me. Could you provide app config?

**Comment by jbenner-radham** [comment]
I'm not on a LAMP stack right now, just using the `phalcon.php serve` PHP server, sorry for any miscommunication at all. Regardless I looked through that issue and didn't see anything relevant to my setup (e.g. no `add_vhost.php` file). Here's the config files as requested:

### `app/config/config.php`
```php
<?php
/*
 * Modified: prepend directory path of current file, because of this file own different ENV under between Apache and command line.
 * NOTE: please remove this comment.
 */
defined('BASE_PATH') || define('BASE_PATH', getenv('BASE_PATH') ?: realpath(dirname(__FILE__) . '/../..'));
defined('APP_PATH') || define('APP_PATH', BASE_PATH . '/app');

return new \Phalcon\Config([
    'database' => [
        'adapter'     => 'Mysql',
        'host'        => 'localhost',
        'username'    => 'root',
        'password'    => '',
        'dbname'      => 'test',
        'charset'     => 'utf8',
    ],
    'application' => [
        'appDir'         => APP_PATH . '/',
        'controllersDir' => APP_PATH . '/controllers/',
        'modelsDir'      => APP_PATH . '/models/',
        'migrationsDir'  => APP_PATH . '/migrations/',
        'viewsDir'       => APP_PATH . '/views/',
        'pluginsDir'     => APP_PATH . '/plugins/',
        'libraryDir'     => APP_PATH . '/library/',
        'cacheDir'       => BASE_PATH . '/cache/',

        // This allows the baseUri to be understand project paths that are not in the root directory
        // of the webpspace.  This will break if the public/index.php entry point is moved or
        // possibly if the web server rewrite rules are changed. This can also be set to a static path.
        'baseUri'        => preg_replace('/public([\/\\\\])index.php$/', '', $_SERVER["PHP_SELF"]),
    ]
]);
```

### `public/webtools.config.php`
<?php

/*
  +------------------------------------------------------------------------+
  | Phalcon Developer Tools                                                |
  +------------------------------------------------------------------------+
  | Copyright (c) 2011-2016 Phalcon Team (https://www.phalconphp.com)      |
  +------------------------------------------------------------------------+
  | This source file is subject to the New BSD License that is bundled     |
  | with this package in the file LICENSE.txt.                             |
  |                                                                        |
  | If you did not receive a copy of the license and are unable to         |
  | obtain it through the world-wide-web, please send an email             |
  | to license@phalconphp.com so we can send you a copy immediately.       |
  +------------------------------------------------------------------------+
  | Authors: Andres Gutierrez <andres@phalconphp.com>                      |
  |          Eduar Carvajal <eduar@phalconphp.com>                         |
  |          Serghei Iakovlev <serghei@phalconphp.com>                     |
  +------------------------------------------------------------------------+
*/

/**
 * @const PTOOLS_IP Allowed IP for access.
 *        Phalcon Developers Tools can only be used in local machine, however
 *        you can set this to allow certain IP address.
 *
 *        For example:
 *          192.168.0.1 or SUBNET 192., 10.0.2., 86.84.124.
 */
defined('PTOOLS_IP') || define('PTOOLS_IP', '192.168.');
defined('BASE_PATH') || define('BASE_PATH', dirname(dirname(__FILE__)));
defined('APP_PATH') || define('APP_PATH', BASE_PATH . DIRECTORY_SEPARATOR . 'app');

/**
 * @const ENV_PRODUCTION Application production stage.
 */
defined('ENV_PRODUCTION') || define('ENV_PRODUCTION', 'production');

/**
 * @const ENV_STAGING Application staging stage.
 */
defined('ENV_STAGING') || define('ENV_STAGING', 'staging');

/**
 * @const ENV_DEVELOPMENT Application development stage.
 */
defined('ENV_DEVELOPMENT') || define('ENV_DEVELOPMENT', 'development');

/**
 * @const ENV_TESTING Application test stage.
 */
defined('ENV_TESTING') || define('ENV_TESTING', 'testing');

/**
 * @const APPLICATION_ENV Current application stage.
 */
defined('APPLICATION_ENV') || define('APPLICATION_ENV', getenv('APPLICATION_ENV') ?: ENV_DEVELOPMENT);

// ---------------------------- DO NOT EDIT BELOW ------------------------------

/**
 * @const PTOOLSPATH The path to the Phalcon Developers Tools.
 */
defined('PTOOLSPATH') || define('PTOOLSPATH', '/Users/jbenner/.composer/vendor/phalcon/devtools');
```
I'll poke around in my code after I get off work and see if I can come up with something too.

**Comment by sergeysviridenko** [comment]
@jbenner-radham Thank you for report. Clear. Could you change your `baseUri` to '/'. It must help you.

**Comment by jbenner-radham** [comment]
@sergeysviridenko Yes, changing the `baseUri` fixed the problem. Thank you.
