### ISSUE TITLE
Don't work，why？

### ISSUE THREAD

**Issue by kg-web** [phalcon/phalcon-devtools#1216]
![image](https://user-images.githubusercontent.com/20922287/38465652-14665816-3b51-11e8-8f87-e7e23eefa27c.png)
![image](https://user-images.githubusercontent.com/20922287/38465655-1d91149e-3b51-11e8-8517-ecad22edd2f2.png)
![image](https://user-images.githubusercontent.com/20922287/38465659-2701e1de-3b51-11e8-880f-7ee5c14486ab.png)
![image](https://user-images.githubusercontent.com/20922287/38465661-2dff0020-3b51-11e8-83c3-d542370e839c.png)

**Comment by hakimio** [comment]
Try the following script:
```
@echo off
                  
set PTOOLSPATH=%~dp0
php %PTOOLSPATH%phalcon.php %*
```

**Comment by kg-web** [comment]
Thank you. I've solved it.
