### ISSUE TITLE
Migrations issue : Foreign Key constraint is incorrectly 

### ISSUE THREAD

**Issue by KVSocial** [phalcon/phalcon-devtools#1226]
Hello all!

I have a small issue with Phalcon migration.

When I use the command : phalcon migration run 
I get error "Foreign Key constraint is incorrectly formed"

That is because the table of the FK isn't created yet, how to best solve this issue? 
I am using Phalcon Dev Tools 3.2.12

Thank you

**Comment by sergeysviridenko** [comment]
@KVSocial actually it is expected behavior if table isn't exist. At this moment you can solve this problem using many ways. For example you can create FK after migrations or create table before running other migrations or other.
