### ISSUE TITLE
Change the bat file from "phalcon.php.bat" to "phalcon.bat" for Windows installations

### ISSUE THREAD

**Issue by codecrafting-net** [phalcon/phalcon-devtools#1238]
### Expected and Actual Behavior

> The Phalcon documentation guide implies that using composer to install the devetools requires no aditional step, beyond having the vendor\bin folder on the system PATH, but the created bat script have a name of "phalcon.php.bat" (inside vendor\bin) which does not work in command prompt, forcing the change to "phalcon.bat" to make the "phalcon" command line be recognized.

### Details

Phalcon DevTools (3.4.0)

Environment:
  OS: Windows NT BA7400ET223 6.2 build 9200 (Windows 8 Enterprise Edition) AMD64
  PHP Version: 7.1.5
  PHP SAPI: cli
  PHP Bin: C:\Users\c115556\AppData\Local\Programs\PHP\php.exe
  PHP Extension Dir: C:\php\ext
  PHP Bin Dir: C:\php
  Loaded PHP config: C:\Users\c115556\AppData\Local\Programs\PHP\php.ini
Versions:
  Phalcon DevTools Version: 3.4.0
  Phalcon Version: 3.3.0
  AdminLTE Version: 2.3.6
  Composer version 1.6.2

**Comment by Jeckerson** [comment]
Can you tell where you found file with name `phalcon.php.bat` ?

Because I can find only `phalcon.bat` and it is located in root of project
https://github.com/phalcon/phalcon-devtools/blob/3.4.x/phalcon.bat

**Comment by codecrafting-net** [comment]
Well, I not so sure about where the file is, but after installation on the vendor/bin folder the file have the name "phalcon.php.bat". I think the file is generated based on composer.json file which have a "bin" config with the name "phalcon.php".

**Comment by CameronHall** [comment]
> I think the file is generated based on composer.json file which have a "bin" config with the name "phalcon.php".

[That would be correct.](https://getcomposer.org/doc/articles/vendor-binaries.md#what-about-windows-and-bat-files-)

We can remove `phalcon.bat` and rename `phalcon.php` to `phalcon`.

**Comment by Jeckerson** [comment]
Implemented

**Comment by someson** [comment]
you just broke all the generated app without any vendors (composer) for just generating db models for windows users. After git pull (3.4.*) the .bat file is gone. There is no other way to run executables as .exe/.com/.bat and now instead of just instead of documented command like

`phalcon all-models --namespace=App\Shared\Models\Base --extends=\Library\Models\ModelBase`

i have to use

`php {MYPATH}\Github\phalcon-devtools\phalcon all-models --namespace=App\Shared\Models\Base --extends=\Library\Models\ModelBase`

am i wrong?

**Comment by Jeckerson** [comment]
If you install devtools via composer, you have `vendor/bin/phalcon` bat file, which is generated automatically.

**Comment by someson** [comment]
as i just said, no composer used!
1. clone the repo
2. use command as recommended: `phalcon commands` → already broken! Which next steps? `phalcon` on windows platform references to `phalcon.bat`, where is no such.

please, update https://docs.phalconphp.com/3.4/en/devtools-installation#installation-windows now

**Comment by Jeckerson** [comment]
`phalcon.bat` will be back in next minor version. To make possible code execution in cases when devtools is installed through `git clone`

**Comment by Jeckerson** [comment]
Fixed in [v3.4.3](https://github.com/phalcon/phalcon-devtools/releases/tag/v3.4.3) release.
