### ISSUE TITLE
Newer version of dev-tools >3.2.3 doesnt generate Model Anotations Metadata

### ISSUE THREAD

**Issue by JABirchall** [phalcon/phalcon-devtools#1241]
I recently updated dev tools to to 3.4 version, but noticed when generating models it doesnt generate the metadata in the models. Since i use the anotations metadata strategy this is needed, and I wouldnt want to all this manually.

I've been using dev tools 3.2 before updating and metadata generates fine, even after rolling back. Dont know what version specifically this happens in since i skipped a few.

### Details
* System info and versions (if possible): 
```
Environment:
  OS: Windows NT DESKTOP-30FF08I 10.0 build 14393 (Windows 10) i586
  PHP Version: 7.1.16
  PHP SAPI: cli
  PHP Bin: G:\WebServer\php7.1\php.exe
  PHP Extension Dir: C:\php\ext
  PHP Bin Dir: C:\php
  Loaded PHP config: G:\WebServer\php7.1\php.ini
Versions:
  Phalcon DevTools Version: 3.4.0
  Phalcon Version: 3.4.0
```
* Phalcon Framework version: 3.4
* PHP Version: 7.1.16
* Operating System: Windows
* Server: Nginx

**Comment by sergeysviridenko** [comment]
@JABirchall Could you try to use `--annotate` option? It has to help you. Your command must be something like `phalcon model --name=foobar --annotate`

**Comment by JABirchall** [comment]
Ahh thanks, that worked.
