### ISSUE TITLE
Upgrade to Box 3

### ISSUE THREAD

**Issue by theofidry** [phalcon/phalcon-devtools#1248]
I saw that you are using Box2, since the original repo is a bit dead I think a heads up is worth it. So Box 3 has been released on the fork [humbug/box](https://github.com/humbug/box) and should make it way easier to build the PHARs. If you are interested, don't hesitate to ping me about it, otherwise feel free to close that issue :)

**Comment by Jeckerson** [comment]
Changed to milestone 4.0.0 due requirement of php ^7.1

**Comment by Jeckerson** [comment]
#1282

**Comment by Jeckerson** [comment]
https://github.com/phalcon/phalcon-devtools/issues/1248 - Drop support of PHP5 for 4.x version

**Comment by Jeckerson** [comment]
Implemented in `v4.0.0-beta.1` release.
