### ISSUE TITLE
Phalcon Devtools Version 3.4 use of Bootstrap 4.0 breaks scaffolded views use of pager class

### ISSUE THREAD

**Issue by eokenned** [phalcon/phalcon-devtools#1249]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior
Upgrade to boostrap 4.0 in devtools 3.4 does not take account of some changes in bootstrap from versrion 3 to version 4.

The pager class is no longer supported so the next and previous buttons on the search page and other pagination buttons on other scaffolded pages do not work. 

This breaks the all the scaffolded pages and distorts them with the header floating over the "next" and "previous" links and also over the search results table.

Phalcon scaffolded pages now look like this
![image](https://user-images.githubusercontent.com/7012577/46217228-57e55680-c339-11e8-83e5-72af43b57849.png)

The problem can be resolved by reverting to bootstrap v 3.3.7 in app/views/index.phtml

If updating to bootstrap v4.0 it looks like you would need to use the pagination - page-item and page-link classes with something along the following lines

![image](https://user-images.githubusercontent.com/7012577/46217596-510b1380-c33a-11e8-8041-2ab3fec0d714.png)

### Details

* Phalcon Framework version: 3.4.1
* Phalcon Devtools version 3.4
* PHP Version: 7.1.4
* Operating System: Windows 10
* Server: Apache

**Comment by sergeyklay** [comment]
@montaccep Could you please take a look

**Comment by montaccep** [comment]
In Bootstrap 3, a pagination component was created by applying the pagination class to any ul element. However Bootstrap 4 demands one to properly indicate pagination and link items using page-item as well as page-link class.

Check out the bootstrap docs: https://getbootstrap.com/docs/4.0/getting-started/introduction/

**Comment by sergeyklay** [comment]
Fixed in the `3.4.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
