### ISSUE TITLE
I have a problem with Scaffold

### ISSUE THREAD

**Issue by LorenRodriguez** [phalcon/phalcon-devtools#1251]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior
When I try to generate Scaffold, the page goes blank and is not generated the Scaffold

### Details

OS Windows 7
Phalcon Version 3.4.1
Devtools Version 3.4.0
PHP version 7.2.9

**Comment by Jeckerson** [comment]
What command do you execute?
