### ISSUE TITLE
Can't use the phalcon-devtools with phalcon 4.0？

### ISSUE THREAD

**Issue by follypimpin** [phalcon/phalcon-devtools#1262]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**
I am trying to install phalco-devtools and it seems phalcon-devtools version is currently not compatible with phalcon v4.0.0 alpha

When I execute phalcon commands help etc this error is displayed in the console:

> Provide output if related
![20190117124703](https://user-images.githubusercontent.com/29546364/51446456-54237880-1d0a-11e9-95ef-88d54a6c6d7f.png)

```php
// paste output here
```
> Provide minimal script to reproduce the issue
cd ~
    git clone https://github.com/phalcon/phalcon-devtools.git
    cd phalcon-devtools
    ln -s $(pwd)/phalcon.php /usr/bin/phalcon
    chmod ugo+x /usr/bin/phalcon
```php
// paste code
```

### Details

* System info and versions (if possible): (`phalcon info`)
* Phalcon Framework version: (`php --ri phalcon`) 4.0.0 alpha
* PHP Version: (`php -v`) 7.3
* Operating System: Centos 7
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by merovinh** [comment]
Have the same error. Looks like phalcon-devtools not updated yet to work with the Phalcon v4.0.0-alpha1. If you want to use phalcon-devtools, you can switch back to Phalcon V3.4.2, it's works for me.

**Comment by mraspor** [comment]
Same issue with Phalcon version 4.0.0-alpha.2.

composer.json file:
`{
    "require-dev": {
        "phalcon/devtools": "~4.0@dev"
    }
}`

Error:

> Your requirements could not be resolved to an installable set of packages.
>  Problem 1
> - Installation request for phalcon/devtools ~4.0@dev -> satisfiable by phalcon/devtools[4.0.x-dev].
> - phalcon/devtools 4.0.x-dev requires ext-phalcon ~3.3 -> the requested PHP extension phalcon has the wrong version (4.0.0-alpha.2) installed.

**Comment by ruudboon** [comment]
Phalcon Devtools isn't v4 compatible yet. Before starting development we need to be in beta at least.
