### ISSUE TITLE
migration timestamp incorrect version class name

### ISSUE THREAD

**Issue by chipco** [phalcon/phalcon-devtools#1268]
I have defined timestamped based migrations, saved in database. When I run `phalcon migrations run` on a 32 bit system I get an error: 
```
Error: Migration class cannot be found EmailConfirmationsMigration_2147483647 at D:\web\hyundai-flow\App/Migrations\1545486321396341_init\email_confirmations.php
```
The class name actually ends with 1545486321396341 and not the queried 2147483647.

The problem lies in `Phalcon\Version\TimestampedItem->getStamp()` which returns an int. On the test platform PHP_INT_MAX is 2147483647.

**Comment by Jeckerson** [comment]
Current issue will be fixed in 4.x with new migrations system. At that moment use x64 bit system.
