### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by 976293711** [phalcon/phalcon-devtools#1273]
### Problem
> /usr/local/var/www/phalcon/phalcon-devtools/phalcon: line 151: 70298 Segmentation fault: 11  php "$devtools/phalcon.php" $*

**Comment by 976293711** [comment]
php 7.3

**Comment by ruudboon** [comment]
What phalcon version are you using?

**Comment by 976293711** [comment]
3.4.0

**Comment by ruudboon** [comment]
Can you first try to upgrade to Phalcon 3.4.3

**Comment by Ultimater** [comment]
Do any of these work?

- `phalcon info`
- `phalcon help`
- `phalcon serve`

What OS is this being run under?

And can you get us a backtrace?
See https://github.com/phalcon/phalcon-devtools/blob/master/CONTRIBUTING.md#bug-report-checklist

Thanks.
