### ISSUE TITLE
ide/gen-stubs.php has Hardcoded user path

### ISSUE THREAD

**Issue by phil-directedge** [phalcon/phalcon-devtools#1277]
Currently the Source has a very specific user path to define the directory to the cphalcon project which is almost guaranteed to fail.

```php
define('CPHALCON_DIR' , '/Users/micate/Code/cphalcon/ext/');
```

What I recommend is more of a generic solution that checks for some of the most common storage paths. For example, here is the one that I have that works with composer, and includes OS safe paths:

```php
define('CPHALCON_DIR' , dirname(dirname(__DIR__)) . str_replace('/', DIRECTORY_SEPARATOR, '/cphalcon/ext/'));
```

**Comment by Jeckerson** [comment]
Example of new usage:

```
cd /opt
git clone git@github.com:phalcon/cphalcon.git
cd /path/to/devtools
CPHALCON_DIR=/opt/cphalcon/ext/ php ide/gen-stubs.php
```
