### ISSUE TITLE
[Discussion] Remove Phalcon Migrations

### ISSUE THREAD

**Issue by CameronHall** [phalcon/phalcon-devtools#1278]
I propose that we remove the Phalcon Migrations feature  in the 4.0 revision of the Phalcon Developer Tools, in favor of [CakePHP's Phinx](https://github.com/cakephp/phinx). 

It seems there are regular issues with the Migrations component, with 21.3% of the issues for this project related to the migrations tool alone. It makes sense, for us to offload this maintenance debt to Phinx as it is already production ready, battle tested and incredibly popular with 7M+ Downloads.

If necessary, we could compromise and create a wrapper for Phinx to maintain the functionality but offload the nitty gritty.

**Comment by Jeckerson** [comment]
Agree!

**Comment by ruudboon** [comment]
Agree. I would love to see the wrapper to handle the config parsing etc.

**Comment by Ultimater** [comment]
Wrapper sounds like fun.

**Comment by sergeyklay** [comment]
I'm ok with this. I think this may be implemented in the v4.0.x . But note we'll need to update the docs  to refer to previous dev-tools version when mentioning previous implementation of migrations. We must also provide at least minimal documentation for the new implementation. And finally, what do you thing guys about a migration converter or a solution (at least a tip) to use old migrations with the new version.

**Comment by Jeckerson** [comment]
@sergeyklay All what you mentioned is possible.

**Comment by CameronHall** [comment]
@sergeyklay this suggestion is only for `v4.0.x`. I suggest it now, as there is already a mass of backward incompatibilities between Phalcon 3 and 4, it's an appropriate time (at least I believe it to be) to also introduce backward incompatibilities to the developer tools as well.

**Comment by Jeckerson** [comment]
Another option is doctrine migrations - https://github.com/doctrine/migrations

**Comment by ruudboon** [comment]
Related https://github.com/phalcon/phalcon-devtools/issues/1315

**Comment by Jeckerson** [comment]
Closing in favor - https://github.com/phalcon/phalcon-devtools/issues/1339
