### ISSUE TITLE
No response on create-project command

### ISSUE THREAD

**Issue by seonpua** [phalcon/phalcon-devtools#1280]
When i ran the phalcon create project command there is no any response and project folder is  not created. Is any one encounter this issue before?

![Untitled](https://user-images.githubusercontent.com/48373271/54471818-79a89c00-47fa-11e9-8c96-fbe25ae91ffb.png)
![Untitled4](https://user-images.githubusercontent.com/48373271/54471866-f0459980-47fa-11e9-87d2-403ed4d7d4b1.png)

![Untitled2](https://user-images.githubusercontent.com/48373271/54471819-79a89c00-47fa-11e9-9853-6e18e066380b.png)
![Untitled3](https://user-images.githubusercontent.com/48373271/54471820-7a413280-47fa-11e9-8f05-d64f121b2710.png)

**Comment by Jeckerson** [comment]
Did you tried any another commands from list?

**Comment by Jeckerson** [comment]
Also, try to upgrade devtools from 3.4.0 to 3.4.1 version

**Comment by seonpua** [comment]
> nother commands from list?

Yes other command is fine

> Also, try to upgrade devtools from 3.4.0 to 3.4.1 version
ok will try

**Comment by seonpua** [comment]
tested with 3.4.1 version it still no works for me and found it stop on this script

 $builder = new ProjectBuilder([
            'name'           => $projectName,
            'type'           => $projectType,
            'directory'      => $projectPath,
            'enableWebTools' => $enableWebtools,
            'templatePath'   => $templatePath,
            'templateEngine' => $templateEngine,
            'useConfigIni'   => $useConfigIni
        ]);

**Comment by Jeckerson** [comment]
@seonpua send please output of `php -m` command. Want to see if you have all needed PHP modules installed.

**Comment by Jeckerson** [comment]
Also, I noticed that you have PHP 7.3 on screenshots, which could be the problem.

**Comment by sergeyklay** [comment]
Phalcon v3.4.3 is the known version to works with PHP 7.3

**Comment by Jeckerson** [comment]
@seonpua Upgrade from PHP 7.3.1 to PHP 7.3.3 and try again.

**Comment by sergeyklay** [comment]
And upgrade Phalcon to v3.4.3
