### ISSUE TITLE
Phalcon DevTools not working Phalcon Lib v3.4.3 - PHP 7.3

### ISSUE THREAD

**Issue by bgastaldi** [phalcon/phalcon-devtools#1284]
I installed Phalcon v3.4.3 to run with PHP 7.3 but phalcon dev-tools doesn't work. When I execute any command nothing happens.

Can someone help me?

Tks

**Comment by Jeckerson** [comment]
Can you specify what specific commands doesn't work form list below?

```
Available commands:
  info             (alias of: i)
  commands         (alias of: list, enumerate)
  controller       (alias of: create-controller)
  module           (alias of: create-module)
  model            (alias of: create-model)
  all-models       (alias of: create-all-models)
  project          (alias of: create-project)
  scaffold         (alias of: create-scaffold)
  migration        (alias of: create-migration)
  webtools         (alias of: create-webtools)
  serve            (alias of: server)
  console          (alias of: shell, psysh)
```

**Comment by bgastaldi** [comment]
All commands

![1](https://user-images.githubusercontent.com/3454381/54496024-19346000-48c9-11e9-9faa-0ac30a049eb3.png)

![2](https://user-images.githubusercontent.com/3454381/54496025-1cc7e700-48c9-11e9-9aec-8292ebad88ce.png)

**Comment by bgastaldi** [comment]
@Jeckerson , I upgraded PHP to version 7.3.3 and now it's working.

**Comment by Jeckerson** [comment]
One of possible answer is that there is some bug in 7.3.2 version...

**Comment by CameronHall** [comment]
@Jeckerson can we please consider updating the version constraint for PHP to `>=5.6 < 7.3.2 || >7.3.3`?

**Comment by Jeckerson** [comment]
@CameronHall For hotfix it can be solution, but we don't know if all works in another minor versions. Any way I'll create PR for this specific case.
