### ISSUE TITLE
typo and extra backslash in Phalcon\Builder\Model.php

### ISSUE THREAD

**Issue by talal424** [phalcon/phalcon-devtools#1286]
version 3.4.0

line #183 getOption should be hasOption 
```php
$entityNamespace = '';
if ($this->modelOptions->hasOption('namespace')) {
    $entityNamespace = $this->modelOptions->getOption('namespace')."\\";
}
```

line #201 getOption should be hasOption 
same thing but at line #210 using $this->getEntityClassName would produce backslash if namespace option is not used
possible solution:

```php
$entityNamespace = '';
if ($this->modelOptions->hasOption('namespace')) {
    $entityNamespace = $this->modelOptions->getOption('namespace')."\\";
}

$refColumns = $reference->getReferencedColumns();
$columns = $reference->getColumns();
$initialize[] = $snippet->getRelation(
    'belongsTo',
    $this->modelOptions->getOption('camelize') ? Utils::lowerCamelize($columns[0]) : $columns[0],
    $entityNamespace . Utils::camelize($reference->getReferencedTable()),
    $this->modelOptions->getOption('camelize') ? Utils::lowerCamelize($refColumns[0]) : $refColumns[0],
    "['alias' => '" . Text::camelize($reference->getReferencedTable(), '_-') . "']"
);
```

**Comment by Jeckerson** [comment]
@talal424 Hi! 

1. Can you specify files, because there are only lines?
2. Can you tell if that typo bring some errors of logic?
3. Can you make PR with explanations?

**Comment by Jeckerson** [comment]
Probably similar issue - #1235

**Comment by talal424** [comment]
Can you specify files, because there are only lines?
```scripts/Phalcon/Builder/Model.php```
Can you tell if that typo bring some errors of logic?
throws InvalidArgumentException when setting relations ```hasMany``` and ```belongsTo```
Can you make PR with explanations?
yes i made #1287
Can you upgrade to latest (3.4.1) devtools and check if your problem still occurs?
yes the issue is also in 3.4.1

**Comment by Jeckerson** [comment]
Fixed
