### ISSUE TITLE
Introduce blackbox testing

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/phalcon-devtools#1289]
I propose to introduce blackbox  testing via [Sharness](https://github.com/chriscool/sharness). I hope this will allow us to write tests quickly and easy.

To better understand what tasks this will cover, for example, look at this: https://github.com/phalcon/phalcon-devtools/pull/1287#issuecomment-474792374

Implementation example: https://github.com/phalcon/zephir/blob/6a2d0b157df9421438a2ee26d8c505abaaefbab8/unit-tests/sharness/t0002-generate.sh

**Comment by Jeckerson** [comment]
Need more discussions and more tools to check... 

Marking to 4.0 milestone for now.

**Comment by Jeckerson** [comment]
Will be used Codeception CLI module instead.
