### ISSUE TITLE
Fix PTOOLS_IP in docker container (web tools)

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/phalcon-devtools#1290]
### Actual Behavior

> **During enabling of web tools in project, config contain generic IP address (192.168.x) that do not exists inside Docker container.**

https://github.com/phalcon/phalcon-devtools/blob/54a77f25a48c10e927728078e6fa6442cdccf481/templates/webtools.config.php#L30

### Expected Behavior

Change constant to dynamic value that will work in all cases.

```php
defined('PTOOLS_IP') || define('PTOOLS_IP', $_SERVER['REMOTE_ADDR']);
```

### Details

* System info and versions (if possible): 3.4.x
* Phalcon Framework version: 3.4.x
* PHP Version: 7.x
* Operating System: Docker
* Server: Other

**Comment by sergeyklay** [comment]
Since this is just a template and not a real project, the end user can (and should, apparently) itself take care of the relevance of this value. We can add a detailed comment to the template.

**Comment by Jeckerson** [comment]
@sergeyklay Which is probably would be better solution. Not only in template but after `phalcon webtools enable` command execution.

**Comment by Jeckerson** [comment]
Added note in code.
