### ISSUE TITLE
Update Model Template Generation

### ISSUE THREAD

**Issue by CameronHall** [phalcon/phalcon-devtools#1297]
@CameronHall @Jeckerson Can we add an issue to the devtools so that this becomes part of the template generating models? Thanks

_Originally posted by @niden in https://github.com/phalcon/cphalcon/pull/13950#issuecomment-480831033_

**Comment by BeMySlaveDarlin** [comment]
Done.

**Comment by Jeckerson** [comment]
Fixed in #1497
