### ISSUE TITLE
Segmentation Fault for every project related action (create-model,.....)

### ISSUE THREAD

**Issue by Fuhunter** [phalcon/phalcon-devtools#1301]
Relating to this Forum Post: https://forum.phalconphp.com/edit/discussion/19579

Hey Guys,

I set up a new environment on macOS 10.14.4 using MAMP with PHP 7.3.1.
The Phalcon extension is working fine, but I always get a segmentation fault when generating a model.

### Details

* System info and versions (if possible): (`phalcon info`): Phalcon DevTools (3.4.0)

Environment:
  OS: Darwin 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
  PHP Version: 7.3.1
  PHP SAPI: cli
  PHP Bin: /Applications/MAMP/bin/php/php7.3.1/bin/php
  PHP Extension Dir: /Applications/MAMP/bin/php/php7.3.1/lib/php/extensions/no-debug-non-zts-20180731
  PHP Bin Dir: /Applications/MAMP/bin/php/php7.3.1/bin
  Loaded PHP config: /Applications/MAMP/bin/php/php7.3.1/conf/php.ini
Versions:
  Phalcon DevTools Version: 3.4.0
  Phalcon Version: 3.4.2
  AdminLTE Version: 2.3.6

* Phalcon Framework version: (`php --ri phalcon`) 3.4.3
* PHP Version: (`php -v`) 7.3.1
* Operating System: macOS 10.14.4
* Server: Apache
* Other related info (Database, table schema): mysql database

**Comment by ruudboon** [comment]
Thnx for your report.
Can you list your extensions also? It could be that there is an extension missing.

**Comment by Fuhunter** [comment]
@ruudboon

Here it goes:

`[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imap
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
phalcon
Phar
posix
readline
Reflection
session
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
zip
zlib`

**Comment by ruudboon** [comment]
@Fuhunter Looks like you got them all. 
Where did you get the Phalcon.so from?

**Comment by Fuhunter** [comment]
@ruudboon 
Compiled from source Branch v3.4.X

**Comment by ruudboon** [comment]
@Fuhunter Did you build it on the same Mac?

**Comment by Fuhunter** [comment]
@ruudboon yes

**Comment by Izopi4a** [comment]
Compiled from source Branch v3.4.X

if you used zephir 0.11 = don't. for phalcon 3 use zephir 0.10.

If you used ext/install take a look at this commit ( this commit exists on my fork only ! )

https://github.com/Izopi4a/cphalcon/commit/a138e23047f3bd785e4b9401126c3822e9a47427

**Comment by Fuhunter** [comment]
@Izopi4a I used the ./build/install file/folder

What does your change with the CFLAGS do? Whats the reason for it?

**Comment by Izopi4a** [comment]
https://en.wikipedia.org/wiki/CFLAGS
http://sdf.org/~riley/blog/2014/10/30/march-mtune/

**Comment by Fuhunter** [comment]
But doesn't the devtools just use Phalcon itself? Connect to the database, read the table columns and finally build a php model file? (Much simplified, I know)

Where does those CFLAGS optimisations about my processor fit in?

(Am I the only one affected by it?)

**Comment by Jeckerson** [comment]
@Fuhunter Try to upgrade to `v3.4.1`

**Comment by Fuhunter** [comment]
I deleted my local phalcon devtools folder, cloned it again from this repository and it still says Version 3.4.0

**Comment by Jeckerson** [comment]
Try to download from releases page - https://github.com/phalcon/phalcon-devtools/releases

**Comment by Izopi4a** [comment]
segfault comes from phalcon. As i said i remember some problems compiling it yourself on mac. If you know what you are doing then probably is fine. otherwise i suggest you use pre-compiled phalcon extension

**Comment by sergeyklay** [comment]
@ruudboon As I remember you're created a PR to Phalcon repo to fix this? Could you send the same path to 3.4.x branch so that we'll have at least ready to git clone branch.

**Comment by ruudboon** [comment]
@sergeyklay No problem. But don't think this is related. My fix was an issue where you could not run docker on a different machine (with older cpu)

**Comment by sergeyklay** [comment]
@Fuhunter Could you please re-install Phalcon using 3.4.x branch and test again? Just clone the 3.4.x branch, go to build directory and call `./install` script

**Comment by TOP-OWN** [comment]
This is a nice framework, but the installation process is too cumbersome to extend（composer）;  For example --laravel ,The installation is very simple，

**Comment by Fuhunter** [comment]
@sergeyklay Sorry for the late response

Installed Phalcon from 3.4.x Branch, but still get the segmentation fault within phalcon-devtools when creating a model

**Comment by sergeyklay** [comment]
I'll try to sort out as soon as I can

**Comment by player903** [comment]
I have the same problem   ，Command Line       ，/works/phalcon-devtools-3.4.1/phalcon.sh: line 151: 53469 Segmentation fault: 11  php "$devtools/phalcon.php" $*

**Comment by player903** [comment]
Phalcon DevTools (3.4.0)

Environment:
  OS: Darwin 192.168.0.114 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 22:26:31 PDT 2019; root:xnu-4903.251.3~5/RELEASE_X86_64 x86_64
  PHP Version: 7.3.1
  PHP SAPI: cli
  PHP Bin: /Applications/MAMP/bin/php/php7.3.1/bin/php
  PHP Extension Dir: /Applications/MAMP/bin/php/php7.3.1/lib/php/extensions/no-debug-non-zts-20180731
  PHP Bin Dir: /Applications/MAMP/bin/php/php7.3.1/bin
  Loaded PHP config: /Applications/MAMP/bin/php/php7.3.1/conf/php.ini
Versions:
  Phalcon DevTools Version: 3.4.0
  Phalcon Version: 3.4.2
  AdminLTE Version: 2.3.6

**Comment by sergeyklay** [comment]
@player903 Could you provide core dump ?

**Comment by Jeckerson** [comment]
Closing for now, as there are new `3.4.x` versions related to seg faults. Feel free to re-open if problem still exist.
