### ISSUE TITLE
Declaration of Phalcon\Devtools\Version::_getVersion() must be compatible with Phalcon\Version::_getVersion(): array in /root/phalcon-devtools/scripts/Phalcon/Devtools/Version.php on line 44

### ISSUE THREAD

**Issue by ZhangRuiMingZRM** [phalcon/phalcon-devtools#1302]
php version: PHP 7.2.17-0ubuntu0.18.04.1
phalcon-devtools version :  3.4.0

I have already installed phalcon-devtools;
When i  typed `phalcon`
```
PHP Fatal error:  Declaration of Phalcon\Devtools\Version::_getVersion() must be compatible with Phalcon\Version::_getVersion(): array in /root/phalcon-devtools/scripts/Phalcon/Devtools/Version.php on line 44

```
It seems to be caused by inconsistent return types

You should add return type(array)  for Phalcon\Devtools\Version::_getVersion() in phalcon-devtools/scripts/Phalcon/Devtools/Version.php on line 44
```php
    protected static function _getVersion(): array
    {
        return [3, 4, 0, 4, 0];
    }

```

**Comment by ruudboon** [comment]
Looks like you're running Phalcon v4 alpha that isn't compatible with phalcon-devtools 3.4.0.
There isn't a v4 release for devtools yet. Work is currently being done in the 4.0.x branch

**Comment by dbinhua** [comment]
First, you find this error file, and add a return tyoe to the function.
`protected static function _getVersion() : array
{
       return [3, 4, 0, 4, 0];
}`
