### ISSUE TITLE
can not build phalcon.phar

### ISSUE THREAD

**Issue by bokunodev** [phalcon/phalcon-devtools#1316]
![Screenshot_1](https://user-images.githubusercontent.com/54968427/64395797-a771ed80-d085-11e9-92c6-45761cad6dfb.png)

**Comment by ruudboon** [comment]
What versions are you using?

**Comment by Jeckerson** [comment]
And what PHP version?

**Comment by bokunodev** [comment]
7.4

*B*


Pada tanggal Jum, 6 Sep 2019 pukul 12.41 Anton Vasiliev <
notifications@github.com> menulis:

**Comment by bokunodev** [comment]
php*7.4*


Pada tanggal Kam, 12 Sep 2019 pukul 09.53 Abdul Wahab <bokunocode@gmail.com>
menulis:

**Comment by sergeyklay** [comment]
@bokunodev Nor Phalcon, nor Dev Tools does not works with PHP 7.4 right now.
