### ISSUE TITLE
Class constants vanish when model is regenerated with --force

### ISSUE THREAD

**Issue by lmfmaier** [phalcon/phalcon-devtools#1317]
Phalcon DevTools Version: 3.4.0
Phalcon Version: 3.4.4

After regenerating a model with `phalcon model <model> --force` class constants defined at the top of the class definition are gone. Custom class methods and members defined before the regeneration are still there

**Comment by BeMySlaveDarlin** [comment]
Fixed this bug and some other bugs related to `--force`
