### ISSUE TITLE
when install latest 3.4.4 version from release page, ./phalcon show same 3.4.0 version

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/phalcon-devtools#1332]
when install latest 3.4.4 version from release page, ./phalcon show same 3.4.0 version

_Originally posted by @KozakIvan in https://github.com/phalcon/phalcon-devtools/issues/1329#issuecomment-541626369_

**Comment by ruudboon** [comment]
Fixed in 3.4.x branch
