### ISSUE TITLE
config.php - No such file or directory

### ISSUE THREAD

**Issue by KozakIvan** [phalcon/phalcon-devtools#1336]
[user@notebook qwe]$ phalcon i

Phalcon DevTools (3.4.5)

Environment:
  OS: Linux userbook 5.3.5-arch1-1-ARCH #1 SMP PREEMPT Mon Oct 7 19:03:08 UTC 2019 x86_64
  PHP Version: 7.3.10
  PHP SAPI: cli
  PHP Bin: /usr/bin/php
  PHP Extension Dir: /usr/lib/php/modules
  PHP Bin Dir: /usr/bin
  Loaded PHP config: /etc/php/php.ini
Versions:
  Phalcon DevTools Version: 3.4.5
  Phalcon Version: 3.4.4
  AdminLTE Version: 2.3.6

$ phalcon project qwe
$ phalcon serve
[Mon Oct 14 19:04:12 2019] PHP Warning:  include(/home/user/projects/php/phalcon/qwe/app/config/config.php): failed to open stream: No such file or directory in /home/user/projects/php/phalcon/qwe/app/config/services.php on line 15
[Mon Oct 14 19:04:12 2019] PHP Warning:  include(): Failed opening '/home/user/projects/php/phalcon/qwe/app/config/config.php' for inclusion (include_path='.:') in /home/user/projects/php/phalcon/qwe/app/config/services.php on line 15

**Comment by ruudboon** [comment]
@KozakIvan Can you try to specify the project type (cli, micro, simple or modules).
```
phalcon project qwe micro
```

**Comment by Dmitrijlin** [comment]
Hello, I have the same problem. I tried everything, but always I have this. I found only config.ini and nothing more. 

D:\php-7.3.10\php.exe D:\Apache24\htdocs\Phalcon\qwe\run

Warning: include(D:\Apache24\htdocs\Phalcon\qwe/app/config/config.php): failed to open stream: No such file or directory in D:\Apache24\htdocs\Phalcon\qwe\app\config\services.php on line 7

Warning: include(): Failed opening 'D:\Apache24\htdocs\Phalcon\qwe/app/config/config.php' for inclusion (include_path='.;C:\php\pear') in D:\Apache24\htdocs\Phalcon\qwe\app\config\services.php on line 7
PHP Warning:  include(D:\Apache24\htdocs\Phalcon\qwe/app/config/config.php): failed to open stream: No such file or directory in D:\Apache24\htdocs\Phalcon\qwe\app\config\services.php on line 7
PHP Warning:  include(): Failed opening 'D:\Apache24\htdocs\Phalcon\qwe/app/config/config.php' for inclusion (include_path='.;C:\php\pear') in D:\Apache24\htdocs\Phalcon\qwe\app\config\services.php on line 7

**Comment by FI-LIFE** [comment]
Problem in  96d8c4948d150b0255cbcdf079d6ae33ef08e3f1

`git checkout a51c53bdf86c010e893b9c082021b17b77415ff3`

and try again

**Comment by KozakIvan** [comment]
PHP Warning disappeared and file config.php on it's own place

**Comment by Jeckerson** [comment]
@KozakIvan Can you please explain what you did to warning disappeared?

**Comment by KozakIvan** [comment]
git pull && git checkout a51c53bdf86c010e893b9c082021b17b77415ff3

**Comment by Jeckerson** [comment]
@KozakIvan Can you try it with latest release `v3.4.5` ?

**Comment by KozakIvan** [comment]
phalcon serve

Phalcon DevTools (3.4.5)

Preparing Development Server
  Host: 0.0.0.0
  Port: 8000
  Base: .htrouter.php
  Document Root: public
Starting Server with /usr/bin/php -S 0.0.0.0:8000 -t public .htrouter.php

[Tue Oct 29 10:41:12 2019] PHP Warning:  include(/home/user/projects/php/phalcon/qwerty/app/config/config.php): failed to open stream: No such file or directory in /home/user/projects/php/phalcon/qwerty/app/config/services.php on line 15

**Comment by Jeckerson** [comment]
@KozakIvan Please update to version `3.4.6` and check if problem is gone. 
Feel free to re-open the issue.
