### ISSUE TITLE
Error when using relative paths with "create-project" command

### ISSUE THREAD

**Issue by Woosy** [phalcon/phalcon-devtools#1338]
### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

I'm very new to Phalcon and PHP frameworks. I just installed the devtools on Ubuntu 18.04 using git & a symlink to /usr/bin (tutorial from the README).
The `phalcon` command works fine, but when I do `phalcon create-project test`, I'm getting the following output :

```php
PHP Warning:  mkdir(): Permission denied in /home/arthur/Tools/phalcon-devtools/scripts/Phalcon/Builder/Project.php on line 105
Error: Unable create project directory /test/
```

It seems that it's trying to create the project "test" at the root of my system.
So I tried using `phalcon create-project /home/arthur/test` and it works fine...

### Details

* System info and versions (if possible): (`phalcon info`)
![image](https://user-images.githubusercontent.com/26418696/66992999-1ef65c00-f0cb-11e9-8231-0390d830b046.png)

* Phalcon Framework version: (`php --ri phalcon`)
![image](https://user-images.githubusercontent.com/26418696/66993035-2f0e3b80-f0cb-11e9-9290-d6153a5e98dc.png)

* PHP Version: (`php -v`)
![image](https://user-images.githubusercontent.com/26418696/66993071-40efde80-f0cb-11e9-9767-af6e6494a422.png)

* Operating System:
![image](https://user-images.githubusercontent.com/26418696/66993260-8a402e00-f0cb-11e9-9c56-0f9dc7d31e46.png)

**Comment by Jeckerson** [comment]
Fixed.
