### ISSUE TITLE
Router.php on Project Command

### ISSUE THREAD

**Issue by caleuanhopkins** [phalcon/phalcon-devtools#1374]
Devtools: v4 (pulled from 4.0.x branch)
Phalcon: v4 RC-3

I ran command `project` and project generated find but `config/router.phg` is missing the `$_SERVER["REQUEST_URI"]` variable in `$router->handle();`. Without the server variable the following error is returned:
```
Wrong number of parameters
#0 /phalcon4/app/config/router.php(13): Phalcon\Mvc\Router->handle()
#1 /phalcon4/public/index.php(20): include('/phal...')
#2 {main}
```

See: https://docs.phalcon.io/4.0/en/routing

**Comment by Jeckerson** [comment]
Merged. Didn't noticed that one. Thank you!
