### ISSUE TITLE
CLI Tests and fixes

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/phalcon-devtools#1376]
- [x] Manual commands review and execution
- [x] Bug fixes and small refactors
- [x] Add more tests, if needed

**Comment by talal424** [comment]
#1376 - Fix finding correct config.php file

the added slash '/' in `preg_match` returns false in windows environment.

would it be simpler if swapped with `preg_match('/config\.php$/i', $f->getFilename())`

**Comment by sergeyklay** [comment]
@talal424 Could you please open a new issue with description of the problem and minimal steps to reproduce? Thank you.

**Comment by talal424** [comment]
done #1426
