### ISSUE TITLE
Support global usage

### ISSUE THREAD

**Issue by ruudboon** [phalcon/phalcon-devtools#1378]
When installing devtools (v4.0.0-beta.2) globally you will get the following error:
```
ERROR: Please run composer install
```
Please add support for global installation.

**Comment by sergeyklay** [comment]
Do you mean [phalcon.phar](https://github.com/phalcon/phalcon-devtools/releases/download/v4.0.0-beta.2/phalcon.phar)?

**Comment by Jeckerson** [comment]
@sergeyklay No, when you install package globally: `composer global install`.

**Comment by faridanthony** [comment]
Hi, is this solved yet? I'm getting the same:
ERROR: Please run composer install

**Comment by foroughfadaei** [comment]
> Hi, is this solved yet? I'm getting the same:
> ERROR: Please run composer install

me too

**Comment by mrdipesh1** [comment]
Samething happened to me for 2 days, but finally it is solved.
I did,

1. Installed composer, by downloading composer.exe

2. Open composer.json which is located at C:/user/Your PC USERNAME/appdata/roaming/composer and pasted
{
"require-dev": {
"phalcon/devtools": "~4.0"
}
}

3. run `composer global require phalcon/devtool` in cmd. It will take time to download, you have to wait. 
Note: I have installed GIT, [From here](https://www.atlassian.com/git/tutorials/install-git) and during the process it will ask for token key and the link for that will be given by cmd itself. If any error occured during download, restart this step. Phalcon/devtool must be @100% or should be installed through cache. I didnt care about other downloads excepts downloads with name phalcon/(migration & devtools).

4. After complete, you will find the phalcon devtool path inside that composer path

5. inside devtool path, there is a file in .bat format. Open it and modify the PTOOLPATH to same directory where that .bat file located

6. register the same path you just used in .bat file in Enviromental Variable PATH

7. open new CMD and type phalcon. I got the result as it should display.

**Comment by fagai** [comment]
Will this support not be merged into 3.x?

**Comment by Jeckerson** [comment]
Related #1431

**Comment by DebugTheCode** [comment]
Going into the phalcon-devtools folder (e.g. /Users/[username]/phalcon-devtools and run `composer install`, fixed it for me.

**Comment by javad4481** [comment]
run this in terminal
below in [username] insert your own username  like   "/home/javad/phalcon-devtools"
`cd /home/[username]/phalcon-devtools/`
`composer install`
if " phalcon " command not found
`alias phalcon=/home/[username]/phalcon-devtools/phalcon`

**Comment by BeMySlaveDarlin** [comment]
(click image to see fullsize)
Debian installation OK
<details>
<img src="https://user-images.githubusercontent.com/10584911/110360097-57476300-804f-11eb-80fe-8e0b28843343.PNG" data-canonical-src="https://user-images.githubusercontent.com/10584911/110360097-57476300-804f-11eb-80fe-8e0b28843343.PNG" />
</details>
Centos installation OK
<details>
<img src="https://user-images.githubusercontent.com/10584911/110360300-9c6b9500-804f-11eb-8ff7-60159c43f811.PNG" data-canonical-src="https://user-images.githubusercontent.com/10584911/110360300-9c6b9500-804f-11eb-8ff7-60159c43f811.PNG" />
</details>
Windows (XAMPP) installation OK
<details>
<img src="https://user-images.githubusercontent.com/10584911/110360352-ab524780-804f-11eb-8eea-a9113374a19c.PNG" data-canonical-src="https://user-images.githubusercontent.com/10584911/110360352-ab524780-804f-11eb-8eea-a9113374a19c.PNG" />
</details>
