### ISSUE TITLE
CompiledPath and CompiledSeparator deprecated

### ISSUE THREAD

**Issue by jenovateurs** [phalcon/phalcon-devtools#1380]
After installing phalcon-devtools from branch 4.0.x, I tried to create a new project with `volt ` by using this command:
`phalcon project --name=test --type=simple --template-engine=volt`
I loaded the new project in the browser and these errors appeared :
```
Deprecated: The 'compiledPath' option is deprecated. Use 'path' instead.
Deprecated: The 'compiledSeparator' option is deprecated. Use 'separator' instead.
```

**Comment by Jeckerson** [comment]
Fixed.
