### ISSUE TITLE
v4 - Command project - Trouble with args

### ISSUE THREAD

**Issue by jenovateurs** [phalcon/phalcon-devtools#1383]
Tested with Debian Stretch.

With Phalcon DevTools (3.4.8), the command : 
`phalcon project hello_world simple –-template-engine=volt`
Does this: 
```
Success: Controller "index" was successfully created.

/var/www/html/hello_world/app/controllers/IndexController.php

  Success: Project 'hello_world' was successfully created.
Please choose a password and username to use Database connection.Used default:'root' without password.
```
The created folder is **hello_world**

With Phalcon DevTools (4.0.0-beta.2) from the branch 4.0.x
Does this: 
```
Phalcon DevTools (4.0.0-beta.2)

Success: Controller "index" was successfully created.

 Info: /var/www/html/phalcon-devtools/–-template-engine=volt/hello_world/app/controllers/IndexController.php

 Success: Project 'hello_world' was successfully created.

 Info: Please choose a password and username to use Database connection.

 Info: Used default: 'root' without password.
```
The created folder is **–-template-engine=volt** not **hello_world**.

**Comment by Jeckerson** [comment]
What is even more strange, is that it creates both, correctly and incorrectly just randomly...

![image](https://user-images.githubusercontent.com/3289702/69833445-d387af80-122b-11ea-98cb-757e390ac95c.png)

**Comment by Jeckerson** [comment]
Well, it doesn't work for you, because you have special character in your command:
```
–-template-engine=volt
^
``

`–` != `-`

That's why it is interpreted as 3d argument and not as option. And third argument is directory name where to save.

**Comment by jenovateurs** [comment]
@Jeckerson Good catch, thanks for taking the time to look at it. 
To give you some context, I have copied the original command from a Word file. I think that when two dash follow one another, Word converts the dash into a special character.
