### ISSUE TITLE
flash does not set errors

### ISSUE THREAD

**Issue by bnlambert** [phalcon/phalcon-devtools#1396]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Flash message is supposed to be set 

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related

```php
 null
```
> Provide minimal script to reproduce the issue

```php

if ($this->request->isPost()) {
            
            if ($form->isValid($this->request->getPost()) == false) {
                
               foreach ($form->getMessages() as $message) {
                    $this->flash->error((string) $message);
                }
            return $this->response()->setJsonContent($this->flash);
               
            }
        }

```

### Details
Phalcon 4.0 modules app on win 10 running php 7.2.3 apache

* System info and versions (if possible): (`phalcon info`)
* Phalcon Framework version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Server: Nginx | Apache | Other
* Other related info (Database, table schema):

**Comment by Jeckerson** [comment]
Is this core example is generated by devtools?

**Comment by Jeckerson** [comment]
Also, inside flash service provider, try use `$flash->setImplicitFlush(false);`

**Comment by bnlambert** [comment]
> Is this core example is generated by devtools?

No @Jeckerson, the code sample provide is an attempt to implement flash during form validation.

**Comment by Jeckerson** [comment]
And what about `setImplicitFlush(false)` ?

**Comment by Jeckerson** [comment]
Here is example, why flash sessions wasn't working (because session wasn't started, nor passed as 2nd parameter):
https://github.com/phalcon/phalcon-devtools/pull/1398/files#diff-590ae0955193258f813489d1dedb09c9R43-R45

_Closing this, due not related to devtools._

**Comment by bnlambert** [comment]
NB: This project was generated by devtools and `setImplicitFlush(false) ` was not part of it.
Thank you for the support.

**Comment by Jeckerson** [comment]
@bnlambert But you told before that this code is not generated by devtools
https://github.com/phalcon/phalcon-devtools/issues/1396#issuecomment-565853947

**Comment by bnlambert** [comment]
May be it was a typo, sorry!  it is the case. I remember saying this on discord

https://discordapp.com/channels/310910488152375297/311108658031362058

> ... @Jeckerson FYI: most of my questions will be concerning the modules app generated by devtools. I am currently migrating and and testing an existing code base to from v3.4  to v4

**Comment by Jeckerson** [comment]
Anyway, I already fixed generation

https://github.com/phalcon/phalcon-devtools/blob/caabde2f9ccfa954c6d24e94d0549d21bab5ad7d/templates/project/modules/services_web.php#L43

https://github.com/phalcon/phalcon-devtools/blob/caabde2f9ccfa954c6d24e94d0549d21bab5ad7d/templates/project/modules/services_web.php#L54

**Comment by bnlambert** [comment]
Thanks i have implemented the changes you mentioned as well and it works great. Thanks!
