### ISSUE TITLE
double and length 1

### ISSUE THREAD

**Issue by zak-wojtek77** [phalcon/phalcon-devtools#1399]
If I have table "test" with field type of "DOUBLE" and run command:
vendor/bin/phalcon migration generate --table=test
then is generate such file:
```php
new Column(
                        'price',
                        [
                            'type' => Column::TYPE_DOUBLE,
                            'notNull' => true,
                            'size' => 1,
                            'after' => 'id'
                        ]
                    )
```
where size = 1

Next when I run command:
vendor/bin/phalcon migration run --verbose
I have error:
ALTER TABLE `test` MODIFY `price` DOUBLE(1) NOT NULL AFTER `id`ERROR: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') NOT NULL AFTER `id`' at line 1

### Details

* Phalcon Framework version: 3.4.1
* phalcon-devtools version: 3.4.10
* PHP Version: 7.2
* Operating System: Linux
* Server: Nginx

**Comment by Jeckerson** [comment]
Fixed in [3.4.11](https://github.com/phalcon/phalcon-devtools/releases/tag/v3.4.11)
