### ISSUE TITLE
Scaffold requires sessionBag

### ISSUE THREAD

**Issue by ruudboon** [phalcon/phalcon-devtools#1402]
When using scaffold the controller contains reference to `persistent`
Persistent requires sessionBag to be available in the di. 
We got 2 solutions.
1. Add sessionBag by default in al the services.
2. Rewrite scaffold

**Comment by Jeckerson** [comment]
I suggest to remove it, as I did in other projects like Vokuro and Invo, during update to v4.

**Comment by Jeckerson** [comment]
Fixed.
