### ISSUE TITLE
webtools don't work (404)

### ISSUE THREAD

**Issue by zak-wojtek77** [phalcon/phalcon-devtools#1412]
### Expected and Actual Behavior
After run command:
vendor/bin/phalcon webtools enable
and run webside:
http://myWebside/webtools.php

I get 404

### Details

* System info and versions (if possible): Phalcon-devtools 4.0.0
* Phalcon Framework version: 4.0.0
* PHP Version: 7.4
* Operating System: Linux Debian
* Server: Nginx
* Other related info (Database, table schema): Mysql 8

**Comment by Jeckerson** [comment]
Known bug, use `/` at the end, like that: `webtools.php/`

**Comment by zak-wojtek77** [comment]
Really now if I add at the end "/" I can see website. But still don't know how I can generate something. This problem was not in Phalcon 3.4.1.

**Comment by Jeckerson** [comment]
Now you can't use both: `notFound()` and `setDefault*()` in Router. If you declare `notFound()`, then any routes that are not in the list - will send to you 404 action.

**Comment by Jeckerson** [comment]
Fixed in #1413
