### ISSUE TITLE
generate model - option namespace has't been defined

### ISSUE THREAD

**Issue by zak-wojtek77** [phalcon/phalcon-devtools#1414]
### Expected and Actual Behavior
When I run such command:
vendor/bin/phalcon model --name=myTable
I get such error:
"Option namespace has't been defined"

This problem was in version 3.4.1 but has been resolved and again come back.

* System info and versions (if possible): 4.0.x-dev
* Phalcon Framework version: 4.0.0
* PHP Version: 7.4
* Operating System: Debian
* Server: Nginx

**Comment by Ladinstar** [comment]
I have the same problem

**Comment by DeaDSouL** [comment]
same issue in phalcon 4.0.2 and devtools 4.0.1

**Comment by Jeckerson** [comment]
Hm, probably it may be related with PHP 7.4, because I'm testing with PHP 7.2...

Will try with another PHP version.

**Comment by Jeckerson** [comment]
Related - #1420

**Comment by zak-wojtek77** [comment]
I think maybe difference is because we use different code. Please you write what shoul I write in composper.json?

**Comment by zak-wojtek77** [comment]
I have upgraded devtools from 4.0.x-dev caa898c to v4.0.1 and is good. I have checked for PHP 7.2 and PHP 7.4.

**Comment by zak-wojtek77** [comment]
thank you

**Comment by sinetik** [comment]
im having the same problem with phalcon 4.0.2 + php 7.4.0
