### ISSUE TITLE
[NFR] generated controller doesn't support CRUD operation

### ISSUE THREAD

**Issue by sigeje** [phalcon/phalcon-devtools#142]
I think it would be good if this devtools is able to generate controller which supports CRUD operation. What do you think?

**Comment by sergeysviridenko** [comment]
@sigeje could you provide more information about your suggestion?

**Comment by sigeje** [comment]
@sergeysviridenko thanks for following it up. I'm not sure if the latest version already support this.
If I can recall it correctly, at that time it only generate empty controller. What I expect was it generate controller with basic actions like add, edit, delete, get and get by id. Looking at recent trend that many apps using RESTful API, maybe it's cool and more relevant if controller is generated with basic RESTful method like put, post, get, delete. Just my two cents.

**Comment by sergeyklay** [comment]
Closing in favor of #1043
