### ISSUE TITLE
Move CI from Travis to Github Actions

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/phalcon-devtools#1420]
* Look at `.ci` folder and `.travis.yml` file
* Add CI for PHP 7.4

**Comment by jenovateurs** [comment]
Currently working on it : https://github.com/les-enovateurs/phalcon-devtools/actions

**Comment by jenovateurs** [comment]
Issue finished: https://github.com/phalcon/phalcon-devtools/pull/1446
