### ISSUE TITLE
Remove BuildPharDockerfile in 4.0.x branch

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/phalcon-devtools#1421]
Due native `.phar` building each release, current files are useless for Phalcon DevTools since version 4.

Files to remove:
* `build/BuildPharDockerfile`
* `Makefile`

/cc @MilesChou please tell if you still need this files for v4.

**Comment by MilesChou** [comment]
Got it, I will download `.phar` file from [GitHub Releases](https://github.com/phalcon/phalcon-devtools/releases)

**Comment by Jeckerson** [comment]
Done in #1422
