### ISSUE TITLE
Create All-Models Schema, ManyToMany not being generated

### ISSUE THREAD

**Issue by tidytrax** [phalcon/phalcon-devtools#1423]
When i execute the below code, gererate all models fine, with all relations between then, but 
methods belongs to and manyToMany does **not** make reference to fk of another schema.

`phalcon all-models --schema=user --namespace=App\\Models\\Abstracts\\User --extends=\\System\\Mvc\\Model --output=/var/www/html/vztus-cms/app/models/Abstracts/User --config=/var/www/html/vztus-cms/app/config/config_webtools.php --doc --relations --fk --annotate --force --get-set --abstract --force 2>&1`

**Comment by Jeckerson** [comment]
What devtools version?

**Comment by tidytrax** [comment]
4.0.1 Phalcon 4.0.2 Postgres 12.1 Php 7.4.2 Nginx 1.6.11

**Comment by tidytrax** [comment]
It does make the relation between same schema, only another schema(same db) it does not create the fk relation belongs and many

**Comment by tidytrax** [comment]
For some reason now i have generated again and relations was created
