### ISSUE TITLE
Column Annotation

### ISSUE THREAD

**Issue by tidytrax** [phalcon/phalcon-devtools#1425]
Column anotation does not generate type boolean for postgresql.

Also does not generate the default value for any columns.

DevTools 4.0.1 Phalcon 4.0.2 Postgres 12.1 Php 7.4.2 Nginx 1.6.11

> phalcon all-models --schema=main --namespace=App\\Models --doc --relations --fk --annotate --force

**Comment by wmamrak** [comment]
Similarly, SMALLINT, MEDIUMINT and TINYINT are annotated as strings.

DevTools 4.0.1, Phalcon 4.0.3, MariaDB 10.4.11, PHP 7.4.1, Apache 2.4.41

**Comment by tidytrax** [comment]
> Similarly, SMALLINT, MEDIUMINT and TINYINT are annotated as strings.
> 
> DevTools 4.0.1, Phalcon 4.0.3, MariaDB 10.4.11, PHP 7.4.1, Apache 2.4.41

Yep, so is useless, I was triyng to use because of this bug, bit I did make a fix, if you have the same problem as column type and default value, you can do like this.

https://github.com/phalcon/cphalcon/issues/14722#issuecomment-578501004

**Comment by BeMySlaveDarlin** [comment]
Fixed in attached PR.
