### ISSUE TITLE
#1376 broke finding correct config.php file in windows

### ISSUE THREAD

**Issue by talal424** [phalcon/phalcon-devtools#1426]
### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

#1376 [committed on Nov 21, 2019](https://github.com/phalcon/phalcon-devtools/commit/a033e99b2a18deab99129fca2ca0c84a35dc4221) 

the added slash in `preg_match` returns false in windows

> Provide minimal script to reproduce the issue

```batch

phalcon project test1

cd test1

phalcon controller foo
```
throws exception: `Error: Builder can't locate the configuration file`

> suggested solution:

target file: `src/Builder/Path.php`

change line # 63

```php
if (preg_match('/config\.php$/i', $f->getFilename())) {
```

change line # 71

```php
if (preg_match('/config\.ini$/i', $f->getFilename())) {
```

### Details
Environment:
  OS: Windows NT TALAL-PC 10.0 build 18362 (Windows 10) AMD64
  PHP Version: 7.2.18
  PHP SAPI: cli
  PHP Bin: C:\wamp\bin\php\php7.2.18\php.exe
  PHP Extension Dir: C:\php\ext
  PHP Bin Dir: C:\php
  Loaded PHP config: C:\wamp\bin\php\php7.2.18\php.ini
Versions:
  Phalcon DevTools Version: 4.0.1
  Phalcon Version: 4.0.2
  AdminLTE Version: 2.3.6

**Comment by Hembi** [comment]
The mentioned solution fixed this problem on Windows 10:
```
change line # 63
if (preg_match('/config\.php$/i', $f->getFilename())) {

change line # 71
if (preg_match('/config\.ini$/i', $f->getFilename())) {
```

**Comment by BeMySlaveDarlin** [comment]
Because of preg_match is too sensitive and `getPathName` returns different data on differend platforms, replaced regex matching to less stict `strpos` in #1487
