### ISSUE TITLE
scaffold doesn't work properly with phalcon dev-tools 4.0.1

### ISSUE THREAD

**Issue by ahmetbibi** [phalcon/phalcon-devtools#1429]
When I tried to create a scaffold and execute it I got these errors. 

``
Fatal error: Uncaught Error: Call to undefined method Phalcon\Paginator\Adapter\Model::getPaginate() in /shared/httpd/tennis-club/tennisClub/app/controllers/MemberController.php:47 
Stack trace: 
#0 [internal function]: MemberController->searchAction() 
#1 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(MemberController), 'searchAction', Array) 
#2 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->dispatch() 
#3 /shared/httpd/tennis-club/tennisClub/public/index.php(43): Phalcon\Mvc\Application->handle('/member/search') 
#4 {main} thrown in /shared/httpd/tennis-club/tennisClub/app/controllers/MemberController.php on line 47
``

I tried them on Ubuntu 18.04, Windows and Devilbox. When I canceled the pagination in Controller Class and in the view page it started to work but still didn't edit or update to the database.

**Comment by jenovateurs** [comment]
Fix in #1436
