### ISSUE TITLE
Phalcon extension missing 

### ISSUE THREAD

**Issue by charbelmhanna** [phalcon/phalcon-devtools#1430]
I have a problem making phalcon work on my xamp locally. 

I added the extension php_falcon for the version I have, also added php_psr and enable them in php.ini on php 7.3.5 version operation system X64 VC15. 

On my wamp it seems that phalcon is enable but when I run composer to install devtools 

Your requirements could not be resolved to an installable set of packages.
------------------------
  Problem 1
    - phalcon/devtools v4.0.1 requires ext-phalcon ^4.0.0 -> the requested PHP extension phalcon is missing from your system.
    - phalcon/devtools v4.0.0 requires ext-phalcon ^4.0.0 -> the requested PHP extension phalcon is missing from your system.
    - Installation request for phalcon/devtools ^4.0 -> satisfiable by phalcon/devtools[v4.0.0, v4.0.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\wamp64\bin\php\php7.3.5\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, deleting ./composer.json.
--------------------------------

also when I run php --ri phalcon I get this 
-> Extension 'phalcon' not present 

I have tried many ways ...

**Comment by ruudboon** [comment]
Can you switch to discord or the forum for support questions? We would like to use this for bugs etc only.
