### ISSUE TITLE
[BUG] phalcon.phar not work on php 7.4.3

### ISSUE THREAD

**Issue by ekmst** [phalcon/phalcon-devtools#1431]
I get an error when starting:

```
$ php phalcon.phar
PHP Fatal error:  Uncaught Error: Class 'Phalcon\DevTools\Version' not found in phar:///home/vagrant/workspace/4models/phalcon.phar/phalcon:35
Stack trace:
#0 /home/vagrant/workspace/4models/phalcon.phar(14): require()
#1 {main}
  thrown in phar:///home/vagrant/workspace/4models/phalcon.phar/phalcon on line 35
```

### Details

* Phalcon Framework version: `4.0.4`
* Devtools Version: `4.0.1`
* PHP Version: `7.4.3`
* Operating System: `Ubuntu 18.04`

**Comment by vhanla** [comment]
Error here too on installation with composer.

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - friendsofphp/php-cs-fixer v2.13.0 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.3) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.0 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.3) does not satisfy that requirement.
    - friendsofphp/php-cs-fixer v2.13.0 requires php ^5.6 || >=7.0 <7.3 -> your PHP version (7.4.3) does not satisfy that requirement.
    - Installation request for friendsofphp/php-cs-fixer (locked at v2.13.0, required as ^2.0) -> satisfiable by friendsofphp/php-cs-fixer[v2.13.0].

```

**Comment by RajP7Jowa** [comment]
you can use with this `composer.json`


`{
    "name": "phalcon/devtools",
    "type": "library",
    "description": "This tools provide you useful scripts to generate code helping to develop faster and easy applications that use with Phalcon framework.",
    "keywords": ["framework", "phalcon", "devtools", "webtools", "phar"],
    "homepage": "https://phalcon.io",
    "license": "BSD-3-Clause",
    "authors": [
        {
            "name": "Phalcon Team",
            "email": "team@phalcon.io",
            "homepage": "https://phalcon.io/en/team"
        },
        {
            "name": "Contributors",
            "homepage": "https://github.com/phalcon/phalcon-devtools/graphs/contributors"
        }
    ],
    "support": {
        "issues": "https://github.com/phalcon/phalcon-devtools/issues",
        "source": "https://github.com/phalcon/phalcon-devtools",
        "forum": "https://forum.phalcon.io"
    },
    "require": {
        "php": ">=7.2",
        "ext-pdo": "*",
        "ext-phalcon": "^4.0.0",
        "psy/psysh": "~0.9",
        "nikic/php-parser": "^4.2.4",
        "phalcon/migrations": "^1.1",
        "vlucas/phpdotenv": "^3.6"
    },
    "require-dev": {
        "humbug/box": "^3.8",
        "codeception/codeception": "^3.1",
        "phpdocumentor/reflection-docblock": "^4.3",
        "phpunit/phpunit": "^8.0",
        "codeception/specify": "^1.2",
        "codeception/verify": "^1.2",
        "squizlabs/php_codesniffer": "^3.5",
        "phalcon/ide-stubs": "^4.0.0",
        "vimeo/psalm": "^3.7"
    },
    "autoload": {
        "psr-4" : {
            "Phalcon\\DevTools\\" : "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Phalcon\\Test\\": "tests/unit",
            "Phalcon\\Test\\Models\\": "tests/_data/models",
            "Phalcon\\Test\\Module\\": "tests/_support/Module"
        },
        "files": [
            "tests/_support/helpers.php"
        ]
    },
    "bin": ["phalcon"]
}`

**Comment by someson** [comment]
`Fatal error: Uncaught Error: Class 'Phalcon\DevTools\Version' not found in phar:///usr/local/bin/phalcon/phalcon on line 35`
php 7.4.13

**Comment by Jeckerson** [comment]
Checked in #1378
