### ISSUE TITLE
PHP Fatal Error - Creating controller

### ISSUE THREAD

**Issue by brunomerod** [phalcon/phalcon-devtools#1435]
Trying to create a controller from phalcon-devtools command line. It's working on every project except this one...

## Command 
`phalcon controller test
`
### Expected Behavior
```
Phalcon DevTools (4.0.1)
                                                      
Success: Controller "test" was successfully created.  
                                                                
Info: /var/www/PATH/app/controllers/TestController.php  
```

### Actual Behavior (Fatal Error Output)
```
Phalcon DevTools (4.0.1)

PHP Fatal error:  Uncaught TypeError: Return value of Phalcon\DevTools\Builder\Path::getConfig() must be an instance of Phalcon\Config, integer returned in /home/bruno/phalcon-devtools/src/Builder/Path.php:69
Stack trace:
#0 /home/bruno/phalcon-devtools/src/Builder/Component/AbstractComponent.php(86): Phalcon\DevTools\Builder\Path->getConfig('ini')
#1 /home/bruno/phalcon-devtools/src/Builder/Component/Controller.php(57): Phalcon\DevTools\Builder\Component\AbstractComponent->getConfig()
#2 /home/bruno/phalcon-devtools/src/Commands/Builtin/Controller.php(63): Phalcon\DevTools\Builder\Component\Controller->build()
#3 /home/bruno/phalcon-devtools/src/Script.php(109): Phalcon\DevTools\Commands\Builtin\Controller->run(Array)
#4 /home/bruno/phalcon-devtools/src/Script.php(148): Phalcon\DevTools\Script->dispatch(Object(Phalcon\DevTools\Commands\Builtin\Controller))
#5 /home/bruno/phalcon-devtools/phalcon(64): Phalcon\DevTools\Script->run()
#6 {main}
  thrown in /home/bruno/phalcon-devtools/src/Builder/Path.php on line 69
```

### Details

* System info and versions
> OS: Linux 4.15.0-1065-oem #75-Ubuntu SMP Wed Nov 20 10:51:26 UTC 2019 x86_64
> description: Notebook
> product: Inspiron 3583 (08CA)
> vendor: Dell Inc.
> description: CPU
> product: Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
> width: 64 bits
> memory: 8GiB

* Phalcon
> Phalcon DevTools Version: 4.0.1
> Phalcon Version: 4.0.0-RC.3
> AdminLTE Version: 2.3.6

* PHP Version
> 7.2.24-0ubuntu0.18.04.3

* Server: Apache
* Other related info (MySQL):

**Comment by Jeckerson** [comment]
What is your config file?

**Comment by sushirod** [comment]
It's the default one. Jus recently created this project with 'phalcon project PROJECT_NAME'.

* app/config/config.php

`<?php

defined('BASE_PATH') || define('BASE_PATH', getenv('BASE_PATH') ?: realpath(dirname(__FILE__) . '/../..'));
defined('APP_PATH') || define('APP_PATH', BASE_PATH . '/app');

/*
 * Using Json connections
 */
return new \Phalcon\Config([
    'database' => [
        'adapter'     => 'Mysql',
        'host'        => 'localhost',
        'username'    => 'root',
        'password'    => '',
        'dbname'      => 'test',
        'charset'     => 'utf8',
    ],
    'application' => [
        'appDir'         => APP_PATH . '/',
        'controllersDir' => APP_PATH . '/controllers/',
        'modelsDir'      => APP_PATH . '/models/',
        'migrationsDir'  => APP_PATH . '/migrations/',
        'viewsDir'       => APP_PATH . '/views/',
        'pluginsDir'     => APP_PATH . '/plugins/',
        'libraryDir'     => APP_PATH . '/library/',
        'cacheDir'       => BASE_PATH . '/cache/',

        // This allows the baseUri to be understand project paths that are not in the root directory
        // of the webpspace.  This will break if the public/index.php entry point is moved or
        // possibly if the web server rewrite rules are changed. This can also be set to a static path.
        'baseUri'        => preg_replace('/public([\/\\\\])index.php$/', '', $_SERVER["PHP_SELF"]),
    ]
]);
`

**Comment by BeMySlaveDarlin** [comment]
This error appears in cases, when you have config.php and config.ini at the same time in you configs folder or when other conflicting changes we done after default installation to files structure.
Driving through trace can detect `Phalcon\DevTools\Builder\Path->getConfig('ini')` call at last stack, where 'ini' should be NULL by `$type = null` methods signature, if no option were provided by input.
Is not reproducible normal ways.
