### ISSUE TITLE
Enable option for path to config file

### ISSUE THREAD

**Issue by calinrada** [phalcon/phalcon-devtools#144]
Now, i am forced to have a config directory in app/ or where where i point it via --directory option. This is not very cool :). It's easy, fast and useful to add an option --config-path in Commands/Builtin/Model.php and change the _getConfig method in Builder/Component.php

**Comment by sergeysviridenko** [comment]
@calinrada Could you provide more information about your suggestion?

**Comment by sergeysviridenko** [comment]
@calinrada Maybe [this PR](https://github.com/phalcon/phalcon-devtools/pull/1098/files) help you?

**Comment by sergeyklay** [comment]
Closing, this is implemented. If there are bugs, we can follow up in separate issues.
