### ISSUE TITLE
Wrong migration for Column::TYPE_DECIMAL

### ISSUE THREAD

**Issue by 1vanov** [phalcon/phalcon-devtools#1444]
_ERROR: SQLSTATE[42000]: Syntax error or access violation: 1427 For float(M,D), double(M,D) or decimal(M,D), M must be >= D (column 'discount')_

Here're the migration files for the same table, but with different versions of devtools:

**phlacon-devtools 3 (working):**
```
'type' => Column::TYPE_DECIMAL,
'default' => "0.00",
'size' => 13,
'scale' => 2
```

**phlacon-devtools 4 (not working):**
```
'type' => Column::TYPE_DECIMAL,
'default' => "0.00",
'notNull' => false,
'scale' => 2,
```

As you can see, in the new migration I made using the updated devtools, there's no _'size'_ attribute for decimal type column, this causes an error.

**Comment by Jeckerson** [comment]
Will be fixed when `phalcon/migrations` will be updated to `v2.x`

**Comment by Jeckerson** [comment]
Related #1464

**Comment by Jeckerson** [comment]
Closing in favor #1464
