### ISSUE TITLE
migrate can't work

### ISSUE THREAD

**Issue by shuqiangzhou** [phalcon/phalcon-devtools#1447]
![2020-04-07 16-38-41 的屏幕截图](https://user-images.githubusercontent.com/26402118/78648551-b4daa900-78ee-11ea-9bb0-e5ba4f83c72b.png)
phalcon version 4.0.5

![2020-04-07 16-39-11 的屏幕截图](https://user-images.githubusercontent.com/26402118/78648602-c3c15b80-78ee-11ea-9a3a-60669811c0a0.png)

phalcon devtool version 4.0.1

use phalcon migration generate command it's get me a error:
that say 
![2020-04-07 16-44-09 的屏幕截图](https://user-images.githubusercontent.com/26402118/78648749-06833380-78ef-11ea-8363-f47220cb15ec.png)
this is bug ??
and I want migrate all tables ,the help ask me no need use any options,the same bad,only use --table option it's well.
![2020-04-07 16-47-04 的屏幕截图](https://user-images.githubusercontent.com/26402118/78649365-ed2eb700-78ef-11ea-8c43-ce35c0d90595.png)
![2020-04-07 16-52-43 的屏幕截图](https://user-images.githubusercontent.com/26402118/78650230-34697780-78f1-11ea-8073-a92b0600b004.png)

**Comment by Jeckerson** [comment]
Related phalcon/migrations#88
