### ISSUE TITLE
Upgrade lucas/phpdotenv dependency to v4

### ISSUE THREAD

**Issue by ae-bogdan** [phalcon/phalcon-devtools#1460]
### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

I am currently using lucas/phpdotenv in my project and it is at version 4. However if I want to install phalcon-devtools, it requires me downgrade the phpdotenv in my project to 3.6.

> Provide output if related

![image](https://user-images.githubusercontent.com/17846988/82706273-ebdc0280-9c81-11ea-9185-ff2a1c629dce.png)

I would be able to make a pull request if you also feel like this can be addressed.

**Comment by quinnjr** [comment]
Taking a cursory look over the library, I can't find any actual invocation of Dotenv. The only uses of environment variables are through `getenv()`.

Perhaps the requirement should be dropped altogether since Dotenv v5 is also available?

**Comment by misantron** [comment]
Any updates here? Will be great to update `lucas/phpdotenv` to actual version.

**Comment by Jeckerson** [comment]
Will be released in next version.
