### ISSUE TITLE
Missing PHP Phalcon module

### ISSUE THREAD

**Issue by PerezRE** [phalcon/phalcon-devtools#1462]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior
Hello! After installing phalcon in latest version (v.4) and also psr extesions on Windows 10 with xampp, and obviously restarting httpd service, evertything seems to be okay from php info page. Phalcon and PSR are 'loaded' and shown un such page. But in CLI, if i type `php --ri phalcon` or `php -m` none phalcon life sign there in spite of `php --ini` shows pointing to the xampp php.ini file correctly. I would really appreciate any support.

_php -m output_
```
php -m 
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
dom
filter
hash
iconv
json
libxml
mbstring
mysqlnd
openssl
pcre
PDO
Phar
readline
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib
[Zend Modules]
```

_php -v output_
```
PHP 7.4.4 (cli) (built: Mar 17 2020 13:49:19) ( ZTS Visual C++ 2017 x64 )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

_php --ini output_
```php --ini
Configuration File (php.ini) Path: C:\WINDOWS
Loaded Configuration File:         C:\App\xampp\php\windowsXamppPhp\php.ini
Scan for additional .ini files in: (none)
Additional .ini files parsed:      (none)
```

_php ---ri phalcon output_
```php --ri phalcon
Extension 'phalcon' not present.
```

### Details

* Phalcon Framework version: phalcon_x64_vc15_php7.4_4.0.6+5190
* PHP Version: PHP 7.4.4 (cli) (built: Mar 17 2020 13:49:19) ( ZTS Visual C++ 2017 x64 )
* Operating System: Windows 10 2004
* Server: Apache

**Comment by ruudboon** [comment]
Can you check in your phpinfo if more ini files are used?

**Comment by PerezRE** [comment]
> Can you check in your phpinfo if more ini files are used?

Not sure if type whole output here, but if it's required for future consultations I'll put it. 
By now, I leave a temporary .[html](https://we.tl/t-pO8q0PQbWy) file

**Comment by ruudboon** [comment]
You php cli is using: `C:\App\xampp\php\windowsXamppPhp\php.ini`
Your webserver is using: `C:\App\xampp\php\php.ini`

**Comment by PerezRE** [comment]
Thanks a lot. I didn't realise about that. I've changed the php cli path pointing to webserserver `php.ini` as well.
