### ISSUE TITLE
Devtools Migrations Column type ENUM

### ISSUE THREAD

**Issue by flaussinot** [phalcon/phalcon-devtools#1469]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**
I tried to implement migrations and I noticed that enum column type is generated as Column::TYPE_VARCHAR with size 1 and there is no option to change to set/enum.

> Provide output if related

```
ERROR: SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'test'
```
> Provide minimal script to reproduce the issue

```php
CREATE TABLE `products` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `test` enum('on','off') DEFAULT 'off',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

The model generated by webtools.php:
```php
...
new Column(
	'test',
	[
		'type' => Column::TYPE_CHAR,
		'default' => "off",
		'size' => 1,
		'after' => 'id'
	]
)
...
```

### Details

* Phalcon DevTools Version: 3.4.11
* Phalcon Framework version: 3.4.5
* PHP Version: 7.3.14
* Operating System: Linux CentOS
* Server: Apache
* Other related info (Database, table schema): MySql

**Comment by Jeckerson** [comment]
ENUM type support was added since v2 `phalcon/migrations`. If possible, please use as separate package inside your composer.json file.

https://github.com/phalcon/migrations

**Comment by Jeckerson** [comment]
Related #1464

**Comment by Jeckerson** [comment]
Closing if favor of #1464
