### ISSUE TITLE
Methods of class Phalcon\Logger  don't have return type restriction like "errors" "info"

### ISSUE THREAD

**Issue by studyzhanglei** [phalcon/phalcon-devtools#1475]
![image](https://user-images.githubusercontent.com/43992249/95827877-e08b8f80-0d66-11eb-92e5-eee0764eb1b4.png)

![image](https://user-images.githubusercontent.com/43992249/95827969-f9944080-0d66-11eb-8fcf-3fc18f2babea.png)

**Comment by studyzhanglei** [comment]
![Uploading image.png…]()

**Comment by studyzhanglei** [comment]
![image](https://user-images.githubusercontent.com/43992249/95828214-47a94400-0d67-11eb-9d80-6ad890f36bad.png)

**Comment by Jeckerson** [comment]
Not related to devtools.
