### ISSUE TITLE
Scaffolding with Webtools

### ISSUE THREAD

**Issue by AndrewMarkUK** [phalcon/phalcon-devtools#1477]
When I navigate to the view in the browser I get this:

Fatal error: Uncaught Error: Call to a member function getRecordId() on array in C:\xampp\htdocs\tennisClub\app\views\account_management\search.phtml:67 Stack trace: #0 [internal function]: unknown() phalcon/cphalcon#1 [internal function]: Phalcon\Mvc\View\Engine\Php->render('C:\\xampp\\htdocs...', Array, true) phalcon/cphalcon#2 [internal function]: Phalcon\Mvc\View->engineRender(Array, 'account_managem...', true) phalcon/cphalcon#3 [internal function]: Phalcon\Mvc\View->processRender('account_managem...', 'search', Array) phalcon/cphalcon#4 [internal function]: Phalcon\Mvc\View->render('account_managem...', 'search') phalcon/cphalcon#5 C:\xampp\htdocs\tennisClub\public\index.php(43): Phalcon\Mvc\Application->handle('/account_manage...') phalcon/cphalcon#6 {main} thrown in C:\xampp\htdocs\tennisClub\app\views\account_management\search.phtml on line 67

Here is line 67: (First record in the foreach)
<td><?php echo $account_management->getRecordId(); ?></td>

Thing is, If I change it to <?php echo $account_management['RecordID']?> It outputs

Why does the scaffolder output it this way and if it is correct that it does so, any idea why I wuld then get this error?

**Comment by BeMySlaveDarlin** [comment]
- Checked on clean project with table having field record_id as pk.
- Created scaffolding for table with `--get-set` option.
- Issue doesn't reproduces, but its legit there is no trailing semicolon after getters in search page view foreach.
Anyways added trailing semicolons as you said it fixed your issue.

**Comment by Jeckerson** [comment]
Fixed in #1493
