### ISSUE TITLE
Scaffold Generate

### ISSUE THREAD

**Issue by ankushkatiyar** [phalcon/phalcon-devtools#1478]
I got an error when create scaffold using cli, i have users table and i'm using  phalcon scaffold users with cli

Fatal error: Declaration of Users::findFirst($parameters = NULL) must be compatible with Phalcon\Mvc\Model::findFirst($parameters = NULL): ?Phalcon\Mvc\ModelInterface

I also tried to create scaffold from webtools after enable in application

**Comment by ankushkatiyar** [comment]
via cli function generated like that public static function findFirst($parameters = null)
Need to change to public static function findFirst($parameters = null): \Phalcon\Mvc\ModelInterface 
It will work fine

**Comment by flyingangel** [comment]
With question mark as it can return null `?\Phalcon\Mvc\ModelInterface`. Please fix

**Comment by Jeckerson** [comment]
Fixed in #1492 
Will be released in next patch version.
