### ISSUE TITLE
"Option namespace hasn't been defined" on generating model

### ISSUE THREAD

**Issue by flyingangel** [phalcon/phalcon-devtools#1491]
Error `Option namespace hasn't been defined` when generating a class with constraint relation.

There's 2 typos errors in the file `Model.php`

Used `if ($this->modelOptions->getOption('namespace'))` instead of `if ($this->modelOptions->hasOption('namespace'))`

A quick, dirty fix is to put `--namespace=""` in the command line

Devtool tag 4.0.5

**Comment by BeMySlaveDarlin** [comment]
Fixed check behavior for `namespace` and `abstract` options on model creation

**Comment by Jeckerson** [comment]
Fixed in #1494
