### ISSUE TITLE
Phalcon Devtools error: generate controllers, models and scaffold not working  (404 not found page)

### ISSUE THREAD

**Issue by luisrom661** [phalcon/phalcon-devtools#1500]
(this text is automatically translated from Spanish to English.)

Hello, I would like to ask about this error that Phalcon devtools shows when generating a controller, model or scaffold:

![image](https://user-images.githubusercontent.com/57530289/113227494-70ab8b80-9258-11eb-8b3f-14c3f9f43ad4.png)
![image](https://user-images.githubusercontent.com/57530289/113227542-87ea7900-9258-11eb-89a2-f89eab47cff9.png)

my configurations are as follows (config,php)

![image](https://user-images.githubusercontent.com/57530289/113227622-b700ea80-9258-11eb-91cd-c99fe2290d27.png)

### Details

* System versions: Phalcon Devtools 4.1.0
* Phalcon Framework version: Phalcon 4.1.0
* PHP Version: PHP Version 7.4.16
* Operating System: Windows 10
* Server: Apache and MySQL

**Comment by BeMySlaveDarlin** [comment]
1. Fixed handle error in #1501 
2. For better workflow i recommend to add into your nginx vhost config
```
    location /webtools {
        try_files $uri $uri/ /webtools.php?_url=$uri&$args;
    }
```

**Comment by luisrom661** [comment]
> 1. Fixed handle error in #1501
> 2. For better workflow i recommend to add into your nginx vhost config
> 
> ```
>     location /webtools {
>         try_files $uri $uri/ /webtools.php?_url=$uri&$args;
>     }
> ```
> 
> `location` is a path where your `webtools.php` is located + filename without `.php`
> 
> For example vhost's root path is `/app/public`, and webtools located
> 
> 1. at /app/public/webtools.php: localtion will be /webtools
> 2. at /app/public/webtools/webtools.php: location will be /webtools/webtools

thanks for your answer, I am not very clear where I should add those lines of code from the location /webtools, can you please tell me? thanks a lot.

**Comment by BeMySlaveDarlin** [comment]
While you have Nginx or Apache webserver, you can add this directive into your website configuration under that webserver.

**Comment by luisrom661** [comment]
> While you have Nginx or Apache webserver, you can add this directive into your website configuration under that webserver.

Thank you!
