### ISSUE TITLE
Debugbar on Multi Module Phalcon Project Not Working 

### ISSUE THREAD

**Issue by CeRBeR666** [phalcon/phalcon-devtools#1505]
Hello
I try using your debugbar on my project. But i have an error code like 

> Provide output if related

```php
Wrong number of parameters
#0 /Users/agaoglu/Desktop/Devs/php/vendor/snowair/phalcon-debugbar/src/ServiceProvider.php(184): Phalcon\Mvc\Router->handle()
#1 /Users/agaoglu/Desktop/Devs/php/vendor/snowair/phalcon-debugbar/src/ServiceProvider.php(163): Snowair\Debugbar\ServiceProvider->safeCheck()
#2 /Users/agaoglu/Desktop/Devs/php/vendor/snowair/phalcon-debugbar/src/ServiceProvider.php(35): Snowair\Debugbar\ServiceProvider->boot()
#3 /Users/agaoglu/Desktop/Devs/php/vinola/app/bootstrap_web.php(60): Snowair\Debugbar\ServiceProvider->start()
#4 /Users/agaoglu/Desktop/Devs/php/vinola/public/index.php(3): require('/Users/agaoglu/...')
#5 {main}
```

My bootsrap_web.php 
```php
require APP_PATH . '/config/routes.php';
    (new Snowair\Debugbar\ServiceProvider(APP_PATH . '/config/debugbar.php'))->start();
    echo $application->handle($_SERVER['REQUEST_URI'])->getContent();
```
How can i fix this ?

### Details

Environment:
  OS: Darwin volkan-mbp 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
  PHP Version: 7.4.16
  PHP SAPI: cli
  PHP Bin: /opt/homebrew/Cellar/php@7.4/7.4.16/bin/php
  PHP Extension Dir: /opt/homebrew/Cellar/php@7.4/7.4.16/lib/php/20190902
  PHP Bin Dir: /opt/homebrew/Cellar/php@7.4/7.4.16/bin
  Loaded PHP config: /opt/homebrew/etc/php/7.4/php.ini
Versions:
  Phalcon DevTools Version: 4.1.0
  Phalcon Version: 4.1.0
  AdminLTE Version: 3.0.1

**Comment by Jeckerson** [comment]
Hello,

You are using external library which isn't supported by Phalcon team, and according to it's repository there is no support for Phalcon v4.

You might fork it and fix by your self, but this is not related to the phalcon devtools.

Refs:
https://github.com/snowair/phalcon-debugbar

**Comment by CeRBeR666** [comment]
Ups wrong repo. 
Thank you for taking time and answering.
