### ISSUE TITLE
PHP Fatal error: Uncaught Error: Class "Phalcon\Config" 

### ISSUE THREAD

**Issue by blackjyn** [phalcon/phalcon-devtools#1526]
`PHP Fatal error:  Uncaught Error: Class "Phalcon\Config" not found in C:\Users\...r\vendor\phalcon\devtools\src\Builder\Component\
AbstractComponent.php:48`

It thrown when running `phalcon project`  and `phalcon serve` 

Phalcon Dev info: 
```
Phalcon DevTools (4.2.0)

Environment:
  OS: Windows : XXXXX AMD64
  PHP Version: 8.1.2
  PHP SAPI: cli
  PHP Bin: C:\xampp\php\php.exe
  PHP Extension Dir: C:\php\ext
  PHP Bin Dir: C:\php
  Loaded PHP config: C:\xampp\php\php.ini
Versions:
  Phalcon DevTools Version: 4.2.0
  Phalcon Version: 5.0.0RC1
  AdminLTE Version: 3.0.1
```

Solution?

**Comment by lemonCarlJ** [comment]
I have the same problem

**Comment by bsun0000** [comment]
In 5.0.0alpha7 (2021-11-16) Phalcon\Config was moved to Phalcon\Config\Config

**Comment by Jeckerson** [comment]
> Phalcon Version: 5.0.0RC1

Change to v4.1.2
