### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Phalcon\Config' not found 

### ISSUE THREAD

**Issue by zeroone2005** [phalcon/phalcon-devtools#1528]
phalcon project  xxx

`
Phalcon DevTools (4.2.0)
Fatal error: Uncaught Error: Class 'Phalcon\Config' not found in C:\Users\cl\AppData\Roaming\Composer\vendor\phalcon\devtools\src\Builder\Component\AbstractComponent.php:48
Stack trace:
#0 C:\Users\cl\AppData\Roaming\Composer\vendor\phalcon\devtools\src\Commands\Builtin\Project.php(74): Phalcon\DevTools\Builder\Component\AbstractComponent->__construct()
#1 C:\Users\cl\AppData\Roaming\Composer\vendor\phalcon\devtools\src\Script.php(109): Phalcon\DevTools\Commands\Builtin\Project->run()
#2 C:\Users\cl\AppData\Roaming\Composer\vendor\phalcon\devtools\src\Script.php(148): Phalcon\DevTools\Script->dispatch()
#3 C:\Users\cl\AppData\Roaming\Composer\vendor\phalcon\devtools\phalcon(65): Phalcon\DevTools\Script->run()
#4 {main}
  thrown in C:\Users\cl\AppData\Roaming\Composer\vendor\phalcon\devtools\src\Builder\Component\AbstractComponent.php on line 48`

Phalcon :
Phalcon is a full stack PHP framework, delivered as a PHP extension, offering lower resource consumption and high performance.
phalcon => enabled
Author => Phalcon Team and contributors
Version => 5.0.0RC4
Build Date => Aug  8 2022 17:25:37
Powered by Zephir => Version 0.16.0-$Id$

**Comment by Jeckerson** [comment]
Devtools isn't support Phalcon v5 atm, please use Phalcon v4.
