### ISSUE TITLE
Dev Tools generates relative application paths in config but requires full paths

### ISSUE THREAD

**Issue by eristoddle** [phalcon/phalcon-devtools#153]
I ran into an issue where dev tools will generate this:
[application]
controllersDir = ../app/controllers/
modelsDir      = ../app/models/
viewsDir       = ../app/views/
pluginsDir     = ../app/plugins/
libraryDir     = ../app/library/
baseUri        = /phalconBlog/
cacheDir       = ../app/cache/
But in order for Web Tools to work correctly or either to generate Models and CRUD, these paths have to be full:
[application]
controllersDir = /home/eristoddle/Dropbox/xampp/htdocs/phalconBlog/app/controllers/
modelsDir      = /home/eristoddle/Dropbox/xampp/htdocs/phalconBlog/app/models/
viewsDir       = /home/eristoddle/Dropbox/xampp/htdocs/phalconBlog/app/views/

I would think the relative path would be the best for both and was going to look into fixing it. I have committed a couple of fixes earlier to the project. Just don't have the time right now.

**Comment by Kr3m** [comment]
How exactly is anything that requires absolute paths and creates more work for server migrations not a bug?  This is even worse for Windows developers who develop locally and have to move to a linux production environment....

**Comment by sergeyklay** [comment]
Any paths should be resolved with `realpath()` which it was done in `phalcon-devtools/2.0.x`
If no — create issue
