### ISSUE TITLE
PHP Fatal error: Class 'Phalcon_exception' not found in

### ISSUE THREAD

**Issue by rizsc** [phalcon/phalcon-devtools#16]
Hello,

I getting following error when I create new project.

PHP Fatal error: Class 'Phalcon_exception' not found in

Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Riz>phalcon
|----------------------
|-- Available commands:
|----------------------
- all-models
- controller
- enable-webtools
- migrate
- migration
- model
- project
- scaffold
- scaffold-bootstrap

D:\wamp\www>phalcon project phalcontry
PHP Fatal error:  Class 'Phalcon_Exception' not found in D:\phalcon-devtools\scr
ipts\Script\ScriptException.php on line 33
PHP Stack trace:
PHP   1. {main}() D:\phalcon-devtools\phalcon.php:0
PHP   2. require() D:\phalcon-devtools\phalcon.php:63
PHP   3. require() D:\phalcon-devtools\scripts\project.php:26
PHP   4. require() D:\phalcon-devtools\scripts\Script\Script.php:21

Fatal error: Class 'Phalcon_Exception' not found in D:\phalcon-devtools\scripts\
Script\ScriptException.php on line 33

Call Stack:
    0.0005     649744   1. {main}() D:\phalcon-devtools\phalcon.php:0
    0.0171     684440   2. require('D:\phalcon-devtools\scripts\project.php') D:
\phalcon-devtools\phalcon.php:63
    0.0211     808336   3. require('D:\phalcon-devtools\scripts\Script\Script.ph
p') D:\phalcon-devtools\scripts\project.php:26
    0.0224     811248   4. require('D:\phalcon-devtools\scripts\Script\ScriptExc
eption.php') D:\phalcon-devtools\scripts\Script\Script.php:21

**Comment by MarcinGrabowski** [comment]
Hello,
if you try create a model in the windows, and you receive error:

> Warning: file_put_contents(C:\xampp\htdocs\ScrumPoker\C:/xampp/htdocs/ScrumPoker/public_html\../app/models\Rooms.php): failed to open stream: Invalid argument in C:\phalcon-tools\scripts\Phalcon\Builder\Model.php on line 492

you must change in class: phalcon-tools\scripts\Phalcon\Builder\Path.php:90
from
`$this->rootPath = rtrim($path, '\\/') . DIRECTORY_SEPARATOR;`
on
`$this->rootPath = rtrim(str_replace('/', DIRECTORY_SEPARATOR, $path), '\\/') . DIRECTORY_SEPARATOR;`

Good luck :-)

**Comment by sergeyklay** [comment]
@MarcinGrabowski 
Fixed in the `3.0.x` branch.

**Comment by ahmadfauzirahman** [comment]
please help me , this my problem when i install phalcon
![phalcon problem](https://user-images.githubusercontent.com/17350730/30238789-969c097c-9578-11e7-913c-01c92c8a881d.png)

**Comment by sergeyklay** [comment]
@ahmadfauzirahman Open please a new issue with steps to reproduce
