### ISSUE TITLE
bad link generated on view for camelCase database

### ISSUE THREAD

**Issue by ghost** [phalcon/phalcon-devtools#164]
hello,

[newzen@i5Desk camelCase]$ phalcon

Phalcon DevTools (1.2.4)

I have a given database which can't modify

```sql
delimiter $$

CREATE TABLE variant (
id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
name tinytext NOT NULL,
status tinyint(1) unsigned NOT NULL DEFAULT '0',
PRIMARY KEY (id),
UNIQUE KEY id_UNIQUE (id)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8$$

CREATE TABLE variantValue (
id bigint(20) unsigned NOT NULL AUTO_INCREMENT,
name tinytext NOT NULL,
status tinyint(1) unsigned NOT NULL DEFAULT '0',
variant_id bigint(20) unsigned NOT NULL,
PRIMARY KEY (id),
UNIQUE KEY id_UNIQUE (id),
KEY fk_variant_value_variant1_idx (variant_id),
CONSTRAINT fk_variant_value_variant1 FOREIGN KEY (variant_id) REFERENCES variant (id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=992 DEFAULT CHARSET=utf8$$
```

after

`phalcon scaffold variantValue --template-engine=volt`

`http://localhost/camelCase/variantvalue`

get the index page for the new controller but if i click on search link

and i get `http://localhost/camelCase/variantValue/search`,

as you can see the controler name was changed from variantvalue to variantValue and of course i get a blank screen.

what will happen with the 3er table

```sql
CREATE TABLE variantLanguageValue (
language_id int(11) NOT NULL,
variantValue_id bigint(20) unsigned NOT NULL,
name varchar(255) NOT NULL,
KEY fk_variantLanguageValue_variantValue1_idx (variantValue_id),
KEY fk_variantLanguageValue_language1_idx (language_id),
CONSTRAINT fk_variantLanguageValue_variantValue1 FOREIGN KEY (variantValue_id) REFERENCES variantValue (id) ON DELETE NO ACTION ON UPDATE NO ACTION,
CONSTRAINT fk_variantLanguageValue_language1 FOREIGN KEY (language_id) REFERENCES language (id) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8$$
```

into index for controller
`{{ link_to("variantLanguageValue/new", "Create variantLanguageValue") }}`
but controller is
`class VariantlanguagevalueController extends ControllerBase`

will be nice if controller be camelCase name too

I think that a bug into devtools.

Taken from https://github.com/phalcon/cphalcon/issues/1740

**Comment by sergeyklay** [comment]
We can't implement this.
In your case for `variantLanguageValueController` or `VariantLanguageValueController` 
Phalcon always will look for `VariantlanguagevalueController`. See https://github.com/phalcon/cphalcon/issues/2572

For these needs you can use the routing and aliasing.
