### ISSUE TITLE
PHPDoc in stubs for ide must use @return $this, not the actual class names

### ISSUE THREAD

**Issue by ianbytchek** [phalcon/phalcon-devtools#168]
Otherwise, when such classes are extended, ide gets confused by the chained methods. For example, MyBuilder extends Phalcon\Mvc\Model\Query\Builder. Chained methods from()->where() will return MyBuilder, but ide will think it will return Phalcon\Mvc\Model\Query\Builder, because PHPDocs tells it so.

**Comment by sergeyklay** [comment]
@ianbytchek Refer please with issue to [phalcon/zephir](https://github.com/phalcon/zephir) repo. 
This isn't Devtools' issue. Stubs are generated by `zephir stubs`
