### ISSUE TITLE
Cannot create migrations with mysql column type tinyint(1)

### ISSUE THREAD

**Issue by bond-os** [phalcon/phalcon-devtools#178]
Hello,

I have a database designed in MySQL Workbench, which sets boolean fileds as tinyint(1). When running migration generate i'm getting 

```
Phalcon DevTools (1.2.6)

1393347998.7632: SHOW TABLES  => 1393347998.7639 (0.00063490867614746)
1393347998.7641: DESCRIBE `account_types`  => 1393347998.7652 (0.0010890960693359)

  Error: Unrecognized data type 8 at column active
```

Table is as follows:

``` mysql
CREATE TABLE `account_types` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `created_at` datetime NOT NULL,
  `updated_at` datetime NOT NULL,
  `active` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Migration creation works only with tinyint(4), it fails on each table with boolean/tinyint(1) field.

**Comment by ruudboon** [comment]
Any updates on this? Enum is also not working, I guess it's related to some mysql specific implementation.

**Comment by oleksandr-torosh** [comment]
Same problem with ENUM datatype

**Comment by sergeyklay** [comment]
I will try to deal with this

**Comment by DestinyMKas** [comment]
same with smallint & bigint
