### ISSUE TITLE
Creating simple project using --use-config-ini does not work

### ISSUE THREAD

**Issue by cefalo19** [phalcon/phalcon-devtools#182]
When I try to create a "simple" project using --use-config-ini, I receive this error:
 
    $ phalcon project phalconBlog simple --use-config-ini
    Error: Unable to write to '../app/controllers/IndexController.php'
 
I do not get this error when using `--use-config-ini` for other types of project (micro or modules).

**Comment by sergeyklay** [comment]
Fixed
