### ISSUE TITLE
The name "Default" as namespace makes a fatal error.

### ISSUE THREAD

**Issue by taophp** [phalcon/phalcon-devtools#184]
I've just create a project using the Phalcon DevTools (1.2.6):
```bash
phalcon project --type=modules
```
Well, the `.htaccess`file  was missing but this was easily fixed. But there is another problem. When I tried to access the page, I got a fatal error:
```
PHP Parse error:  syntax error, unexpected 'Default' (T_DEFAULT), expecting identifier (T_STRING)                                                  or \\\\ (T_NS_SEPARATOR) or '{' in /var/www/projects/formation2/default/apps/frontend/Module.php on line 3, referer: http://localhost/projects/formation2/
```
It seems that the word 'Default' cannot be used as namespace.

By the way, it should be great to have a command to easily create a new module...

**Comment by sergeyklay** [comment]
Thanks! Fixed in 2.0.x
