### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by scento** [phalcon/phalcon-devtools#190]
The following functions lack of some PHPDoc:

<pre>Acl/Adapter/Memory::addInherit($roleName: string, $roleToInherit: string|object): boolean|null
Acl/Adapter/Memory::addResource($resource: \Phalcon\Acl\Resource|string, $accessList: array|string|null: boolean
Acl/Adapter/Memory::addResourceAccess($resourceName: string, $accessList: array|string
Acl/Adapter/Memory::dropResourceAccess($resourceName:string, $accessList: array|string
Acl/Adapter/Memory::_allowOrDeny($roleName: string, $resourceName: string, $access: string|array, $action: int)
Acl/Adapter/Memory::allow($roleName: string, $resourceName: string, $access: string|array

Acl/Adapter::getEventsManager():MangerInterface|null
Acl/Adapter::getActiveRole():string|null
Acl/Adapter::getActiveResource():string|null
Acl/Adapter::getActiveAccess():string|null

Annotations/Annotation::getExprArguments(): array|null
Annotations/Annotation::getArguments(): array|null
Annotations/Annotation::getArgument($position: int|string): mixed
Annotations/Annotation::hasNamedArgument($position: string): boolean
</pre>

**Comment by sergeyklay** [comment]
Fixed in 2.0.x
