### ISSUE TITLE
missing BuilderException use declaration

### ISSUE THREAD

**Issue by CoDanny** [phalcon/phalcon-devtools#191]
When I run 'phalcon migration run' using the master branch I get:

Fatal error: Class 'Phalcon\Commands\Builtin\BuilderException' not found in /Users/daniel/phalcon-devtools/scripts/Phalcon/Commands/Builtin/Migration.php on line 112

This is due to the use declaration missing in the migration file. It's trying to find it in the namespace

**Comment by sergeyklay** [comment]
Fixed in 2.0.x
