### ISSUE TITLE
creating model: not including set/getSource

### ISSUE THREAD

**Issue by ug19** [phalcon/phalcon-devtools#196]
Hi everyone!

I would like to report an error with creating model in a console.

I have a table "users_flowers". The problem is that the name of generated model is "UsersFlowers" but there is no information about a real table name - I mean there is no setSource/getSoruce method.

By the way I have analizyed the docs and still do not understand the difference between setSource and getSource but maybe it's not a place.

I am kind of beginner in terms of frameworks so sorry if it's not really an issue. But voiced lot of "fucks" looking for an error in my hasManyTomany till I found what was wrong, hehe:)

I am using Phalcon 1.3.0, Bitnami WAMP, MySQL, Windows XP.

**Comment by sergeyklay** [comment]
@ug19 Fixed in `2.0.x` branch
