### ISSUE TITLE
Controller Bug when using getters and setters

### ISSUE THREAD

**Issue by garethwi** [phalcon/phalcon-devtools#203]
There are two places in the controllers where direct access to the properties is being attempted when the get-set option has been chosen:

editAction

```
$this->view->id = $model->id;
```

should be

```
$this->view->id = $model->getId();
```

And in saveAction

```
"params" => array($region->id)
```

should be 

```
"params" => array($region->getId())
```

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x branch`. Feel free to open a new issue if the problem appears again. Thank you for contributing.
