### ISSUE TITLE
Dead option "data" for Migration command

### ISSUE THREAD

**Issue by julianseeger** [phalcon/phalcon-devtools#204]
The migration command is able to use the "data" option (https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Commands/Builtin/Migration.php#L138) but as the `$_possibleParameters` array does not contain this option, there does not seem to be any way to pass this parameter in because an
>Error: Unknown parameter 'data'

is thrown. I would wan't to use this parameter to export the inital seed data into a migration.

**Comment by catalincislariu** [comment]
Hi, is this feature done and it can be used?

**Comment by catalincislariu** [comment]
Hi, is this done? How can I use it? phalcon migration --exportData run?

**Comment by sergeyklay** [comment]
HI @catalincislariu 

Use please Phalcon Devtools 2.0.x branch and enter `phalcon migration` without params for help

**Comment by catalincislariu** [comment]
Hi,

I already spent to much time on trying to find on the framework documentation or anywhere on the web the command to export also the data with the database structure.

I would really appreciate if you can help me with the command because I can't get it working even after seeing the help from phalcon migrate.

Regards,
Catalin Cislariu

**Comment by sergeyklay** [comment]
@julianseeger Thanks. Fixed in `2.0.x` branch

**Comment by sergeyklay** [comment]
@catalincislariu 

First, let's check table:

```sh
$ mysql -uroot testdb
> select count(*) from tokens;
+----------+
| count(*) |
+----------+
|        2 |
+----------+
1 row in set (0.00 sec)

MariaDB [notify]> \q
```

Okay, 2 rows. Let's generate first migration:

- **always** - import data always
- **oncreate** - import data when create table

```sh
$ phalcon migration generate --table=tokens --data=always

# Output omitted for brevity
```

Let's take a look at the files

```sh
$ ls -l app/migrations/1.0.0/
total 12
-rw-rw-r-- 1 klay klay  200 Sep 15 22:49 tokens.dat
-rw-rw-r-- 1 klay klay 4578 Sep 15 22:49 tokens.php
```

- **tokens.dat** - data
- **tokens.php** - migration
- **app/migrations/1.0.0/** - version

Now we need to empty a table completely:

```sh
$ mysql -uroot testdb
> select count(*) from tokens;
MariaDB [notify]> select count(*) from tokens;
+----------+
| count(*) |
+----------+
|        2 |
+----------+
1 row in set (0.00 sec)

MariaDB [notify]> truncate table tokens;
Query OK, 0 rows affected (0.00 sec)

MariaDB [notify]> select count(*) from tokens;
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (0.00 sec)

MariaDB [notify]> \q
```

But what is in the data file?

```sh
$ cat app/migrations/1.0.0/tokens.dat
'6'|1|'\'123123123123213\''|'\'qweqweqweqweqwe\''|'0000-00-00 00:00:00'|'0000-00-00 00:00:00'|10
'7'|1|'\'qwerqwerqwerqweweqr\''|'\'46546436346456346\''|'0000-00-00 00:00:00'|'0000-00-00 00:00:00'|10
```

Hmm..

```sh
$ phalcon migration run

# Output omitted for brevity

$ mysql -uroot testdb
> select count(*) from tokens;
+----------+
| count(*) |
+----------+
|        2 |
+----------+
1 row in set (0.00 sec)

MariaDB [notify]> \q
Bye
```

Done :)

**Comment by catalincislariu** [comment]
Ty very much, that will help me and others for sure. Appreciate it.
