### ISSUE TITLE
Migration showing sql profiles

### ISSUE THREAD

**Issue by nazwa** [phalcon/phalcon-devtools#215]
Hello everyone!

I was just thinking... every time migrations are generated or run, all sql queries are outputted to console. Do we really need that? For me it's just clutter, but do you think those profiles are actually useful to anyone?

**Comment by rianorie** [comment]
perhaps an --output flag, something to think about.

**Comment by sergeysviridenko** [comment]
@nazwa I suppose it useful because I can control process generate/run migration and I can see all errors and all SQL queries which executed. But i agree we can wright SQL queries in `log` file or screen. Is this your suggestion?

**Comment by sergeysviridenko** [comment]
I guess we can close this issue.

**Comment by sergeysviridenko** [comment]
I guess we can close this issue.
