### ISSUE TITLE
[Migration] phalcon migration run do nothing

### ISSUE THREAD

**Issue by dinhhoanglong91** [phalcon/phalcon-devtools#226]
I have executed ```phalcon migration run``` but my database don't change. The result of this command is only:
```Phalcon DevTools (1.3.2 ALPHA 1)```
When I removed ```.phalcon/migration-version``` file and executed the above command, ```.phalcon/migration-version``` is created with content is: ```1.0.0``` (It is about creating table).
But my database is still empty.
Can you help me fix this problem.

In addition, if I execute ```phalcon migration generate``` and then, ```phalcon migration run```, it may run correctly:
```
Phalcon DevTools (1.3.2 ALPHA 1)
Success: Version 1.0.1 was successfully migrated  
```

**Comment by 7thcubic** [comment]
Ideally this isnt a bug. You are not suppose to re-run the same version. If you have manually dropped the entire schema for your mysql,  you have to manually remove the migration-version file.

but i suppose its possible to add a --force command.

**Comment by nathanielks** [comment]
Adding a force command would be super helpful.

**Comment by rikur** [comment]
Storing the fromVersion in a file is not a very solid solution IMHO. Storing it in the database similar to what Rails does makes a lot more sense -- it is tied to the schema/data of the database and gets transported along database dumps etc.
