### ISSUE TITLE
Error when trying to generate a volt file with scaffold 

### ISSUE THREAD

**Issue by raja-aitlahrir1** [phalcon/phalcon-devtools#229]
Hello, 

the command, phalcon scaffold blogs --template-engine=s volt , is not working
It displays this error 

 Error: SQLSTATE[HY000] [2002] No such file or directory 

Can you please help?

Regards

**Comment by jorwan** [comment]
Hi @raja-aitlahrir1 
Could you please explain how did you solved it ?
Thanks
