### ISSUE TITLE
model and all-models generate different code

### ISSUE THREAD

**Issue by RaTm7** [phalcon/phalcon-devtools#234]
Hello,

when your generate model with "model"-command, u get other code then with "all-models".
For Example, your dont have the --fk/--validations/--relations options, but it would make sence.
Same with the Phalcon\Mvc\Model::initialize().

With "model" you get "setSource()", with "all-models" you dont, but it is needed, i guess?

About the get-/set-Methods, i would love to have type-casts there, dont know how it is with generated code, didnt tried it yet, but with manuell created ones, u get strings, even if there are integer/float values.

So far, RaTm7

P.S. "--validations" in "all-models" doesnt seem to do anything, i would expect to get validations for all columns, so i can change/override them, if needed. But maybe i just didnt called it right?

P.P.S Anyway its really amazing Framework u did there, i really love it. In Combination with angularjs, u can pull of some crazy projects in no time. :)

**Comment by sergeysviridenko** [comment]
I guess this issue can be deleted.
