### ISSUE TITLE
install step

### ISSUE THREAD

**Issue by hanbz** [phalcon/phalcon-devtools#235]
When you install the devtools you must set the folder "chmod 777" but the document don't have this step.
Maybe you can write a little FAQ ?

**Comment by rianorie** [comment]
@hanbz You don't need 777, but the user you're executing the console script as needs permission to write or if you're using the webtools, the web user does. 

Can you let me know which of the two you were using so we might enhance them?

**Comment by mesgen** [comment]
phalcon install complate but php warning

PHP Warning:  Module 'phalcon' already loaded in Unknown on line 0

why ?

**Comment by sergeyklay** [comment]
Something like

http://stackoverflow.com/questions/28124200/php-warning-module-modulename-already-loaded-in-unknown-on-line-0

http://stackoverflow.com/questions/3518796/php-extension-module-hello-already-loaded-in-unknown-on-line-0?rq=1

**Comment by mesgen** [comment]
through php.ini "extension = phalcon.so" erased and the error has been corrected now, 
phalcon is running smoothly
