### ISSUE TITLE
DevTools does not generate models for Postgresql tables

### ISSUE THREAD

**Issue by martin-georgiev** [phalcon/phalcon-devtools#237]
The following is related to this discussion http://forum.phalconphp.com/discussion/2981/devtools-cannot-create-models-from-postgresql-db#C9921

All comments are related to Phalcon 1.3.2 deployed on a Bitnamp WAPP Stack 5.5.15 with Win 7.

In devtools\scripts\Phalcon\Web\Tools\controllers\ControllerBase.php there is no fallback when on line 69 $dbTables = $connection->listTables() fails to provide the tables list.

devtools\scripts\Phalcon\Web\Tools\views\models\index.phtml is auto-completing the database name and not the actual schema name for postgre configurations. Issue caused by if-else block implemented on line 76 in devtools\scripts\Phalcon\Web\Tools\controllers\ControllerBase.php

devtools\scripts\Phalcon\Web\Tools\controllers\ModelsController.php is giving inadequate feedback with stating on line 83 that "Models were created successfully", even if no models were actually created.

**Comment by rianorie** [comment]
Created a new uncluttered endpoint for this, see #295.
