### ISSUE TITLE
Missing FileInterface::getKey()

### ISSUE THREAD

**Issue by dostoevskiy-spb** [phalcon/phalcon-devtools#239]
Hello!
In IDE autocomplete mocks you miss FileInterface::getKey() function. Please, add it. Thx.

**Comment by Green-Cat** [comment]
There is no getKey method in the interface in the core of phalcon, not really sure what you mean. If you believe there should be one you should open an NFR (New Feature Request) on the main phalcon repository. https://github.com/phalcon/cphalcon/blob/master/phalcon/http/request/fileinterface.zep
