### ISSUE TITLE
Missing configuration in services.php

### ISSUE THREAD

**Issue by wlisesrivas** [phalcon/phalcon-devtools#242]
When you create a project with the command tools, for MySql database work fine, but when you want to use PostgreSQL the services.php file don't add some important properties like:

![phalcon](https://cloud.githubusercontent.com/assets/1482092/4022069/5d654ac2-2b15-11e4-8cac-e25acb8f2109.JPG)

If you want to add the PORT or SCHEME must be added in the services.php directly because in the config.php does not change anything. I don't know if when create a project tells what database to use, but must be add all (even if dont are present at config.php) for usability reason.

Version: Phalcon DevTools (1.3.2 ALPHA 1)

**Comment by danialali1** [comment]
Array to string conversion in app\config\services.php on line 57
help me solve this issue please

**Comment by sergeyklay** [comment]
@danialali1 Create please separated issue and provide please app\config\services.php

**Comment by danialali1** [comment]
@sergerklay ThankYou for your feedback i sorted it out myself :P
Thank You once again :)

**Comment by hasannawaz** [comment]
@danialali1 : could you please post how you fixed it and close the issue ? :smile:

**Comment by sergeyklay** [comment]
@wlisesrivas I've fixed this issue. Can you please check it now in 2.0.x branch?
