### ISSUE TITLE
webtools doesn't work

### ISSUE THREAD

**Issue by geoidesic** [phalcon/phalcon-devtools#277]
Phalcon v1.3.3
1. phalcon project --name multi --enable-webtools
     Success: Project 'multi' was successfully created.
2. browse to http://localhost/arc/multi
     Congratulations!
     You're now flying with Phalcon. Great things are about to happen!
3. browse to http://localhost/arc/multi/webtools
     WebtoolsController handler class cannot be loaded

**Comment by trentramseyer** [comment]
It is attempting to find a controller in your app named WebtoolsController which isn't created by the webtools system. Webtools run independently of your apps.

**Comment by massimoselvi** [comment]
try: 
http://localhost/arc/multi/webtools.php

**Comment by mesgen** [comment]
phalcon, the installation has been completed but PHP is warning.

error:
PHP Warning: Module 'phalco the' already loaded in Unknown on line 0
Warning: Module 'phalco the' already loaded in Unknown on line 0

What is the reason? How do I fix it?

**Comment by mesgen** [comment]
phalcon, the installation has been completed but PHP is warning.

error:

PHP Warning: Module 'phalcon the' already loaded in Unknown on line 0

Warning: Module 'phalcon the' already loaded in Unknown on line 0

What is the reason? How do I fix it?

**Comment by Green-Cat** [comment]
@geoidesic ping

**Comment by geoidesic** [comment]
I'll have to try this later, sorry. Changed computers early in Feb and haven't had a chance to play with Phalcon since. Might only get there in Feb 2016. How would I "export PTOOLSPATH in your shell" btw?

**Comment by geoidesic** [comment]
I am hoping to rewrite an API using Phalcon in 2016.

**Comment by sergeyklay** [comment]
@geoidesic You can use [my .profile](https://github.com/sergeyklay/dotfiles/blob/master/.profile) as example for export purposes
