### ISSUE TITLE
Fix Phalcon\Http\Response method signature

### ISSUE THREAD

**Issue by vv3d0x** [phalcon/phalcon-devtools#281]
Response has a method called **setFileToSend** his signature has 3 args, but here only 2.

we have
```php
/**
		 * Sets an attached file to be sent at the end of the request
		 *
		 * @param string $filePath
		 * @param string $attachmentName
		 */
		public function setFileToSend($filePath, $attachmentName=null);
```

but we should have
```php
/**
		 * Sets an attached file to be sent at the end of the request
		 *
		 * @param string $filePath
		 * @param string $attachmentName
		 * @param boolean $attachment 
		 */
		public function setFileToSend($filePath, $attachmentName=null, $attachment=true){ }
```

https://github.com/phalcon/cphalcon/blob/master/ext/http/response.c#L893

**Comment by 7thcubic** [comment]
i believe this is on the wrong section

**Comment by rianorie** [comment]
For a second I thought so too, but he's talking about the IDE stubs, I think. I'll verify and put it in the codebase if it is

**Comment by 7thcubic** [comment]
its cphalcon bro =d

**Comment by rianorie** [comment]
actually, it's not. If you check the file he linked to you'll see the function is reading 3 parameters, while the stubs for 1.3.4 only have 2. The 2.0.0 stubs have all three though. See https://github.com/phalcon/phalcon-devtools/blob/master/ide/1.3.4/Phalcon/Http/Response.php#L299 and   https://github.com/phalcon/phalcon-devtools/blob/master/ide/2.0.0/Phalcon/Http/Response.php#L300
