### ISSUE TITLE
phalcon migration generate - AUTO_INCREMENT

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/phalcon-devtools#282]
Is there are some way to disable AUTO_INCREMENT generation from local tables?

Some times local rows could have different primary key counters or even have empty table, so AUTO_INCREMENT set current counter of local tables where migration was generated.

Could be, for example:
```bash
phalcon migration generate --no-auto-increment
```

**Comment by ruudboon** [comment]
+1 for that.

**Comment by hi2u** [comment]
I'm on devtools version 2.0.7, and it looks like this has been completed now...

    --no-auto-increment    Disable auto increment (Generating only)

It seems to me that this would be a sensible default?

Considering that migrations don't transfer actual row data, how often would people want the auto_increment kept?  

Obviously still worth leaving in as an option though.

**Comment by sergeyklay** [comment]
@hi2u Thanks for confirm. This has been completed now by @7thcubic
