### ISSUE TITLE
Multiple database engine support

### ISSUE THREAD

**Issue by rianorie** [phalcon/phalcon-devtools#295]
Add support for the PostgreSQL database engine. Potentially other databases as well.

See #290 and #237

**Comment by 7thcubic** [comment]
boss. postgresql is supported

```php
   } elseif ($adapter == 'Postgresql') {
            $schema = 'public';
            $initialize[] = sprintf(
                $templateThis, 'setSchema', '"' . $this->_options['schema'] . '"'
            );
```

**Comment by max91** [comment]
```
if (isset(self::$_databaseConfig->dbname)) {
      $defaultSchema = self::$_databaseConfig->dbname;
 } else {
      $defaultSchema = null;
}
```

https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Mvc/Model/Migration.php#L389

wtf? =/

**Comment by sergeysviridenko** [comment]
@rianorie devtools support PostgreSQL now. Could try latest stable version?

**Comment by rianorie** [comment]
@sergeysviridenko I'll just close this then :) I added the issue back then because there were requests for it.
