### ISSUE TITLE
Sqlite doesn't seem to work with webtools

### ISSUE THREAD

**Issue by austerus** [phalcon/phalcon-devtools#314]
I have modified the default config from 

    'database' => array(
        'adapter'     => 'Mysql',
        'host'        => 'localhost',
        'username'    => 'root',
        'password'    => '',
        'dbname'      => 'test',
        'charset'     => 'utf8',
    )

to

    'database' => array(
        'adapter'     => 'Sqlite',
        'dbname'      => 'test.sqlite',
        'charset'     => 'utf8',
    )

however even though eventually I made it work in my app, the webtools simply can't find the PDO/Sqlite adapter it seems!

Has anyone encountered this ?

Thanks!

**Comment by w2pc** [comment]
what is the exact error?

**Comment by austerus** [comment]
The error returned in the UI in the Models section is "Adapter is not supported"

**Comment by sergeyklay** [comment]
@austerus I just checked - everything is fine in 2.0.x branch

**Comment by austerus** [comment]
Confirmed, thanks!
