### ISSUE TITLE
PHP Parse error:  syntax error, unexpected '[' in /../phalcon-devtools-master/scripts/Phalcon/Builder/Model.php on line 373

### ISSUE THREAD

**Issue by weboot** [phalcon/phalcon-devtools#318]
Phalcon DevTools (1.3.4) version.

run phalcon model modelname

result: PHP Parse error:  syntax error, unexpected '[' in /../phalcon-devtools-master/scripts/Phalcon/Builder/Model.php on line 373

**Comment by jyyan** [comment]
in my ubuntu 12.04 also got this problem too. 
--
$ php -v
PHP 5.3.10-1ubuntu3.16 with Suhosin-Patch (cli) (built: Feb 13 2015 20:15:04) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
--

**Comment by jyyan** [comment]
hi all . i found thats my php version 5.3.10 do not support the syntax , such as :

    $reference->getColumns()[0]

replace those codes to (line 37x & 39x )

	    $a = $reference->getColumns();
	    $b = $reference->getReferencedColumns();
            $initialize[] = sprintf(
                $templateRelation,
                'belongsTo',
                $a[0],
                $entityNamespace . ucfirst($reference->getReferencedTable()),
                $b[0],
                "array('alias' => '" . ucfirst($reference->getReferencedTable()) . "')"
            );

will temporary fix this issue.
