### ISSUE TITLE
Migration filename failed with default empty value (multy module app)

### ISSUE THREAD

**Issue by alexglue** [phalcon/phalcon-devtools#319]
0) Make phalcon project $PROJECT_NAME modules --enable-webtools
0.5) fix directory bug (hardcoded app/migration path changed to apps/migration).
1) Open /webtools.php?_url=/migrations/generate
2) Run Generate (without typing everything).
3) Got error:

```
Warning: Invalid arguments supplied for camelize() in /home/glue/phalcon-devtools/scripts/Phalcon/Mvc/Model/Migration.php on line 285
```

Filename is _.php_ without name part.
Classname is "Migration_100".

**Comment by sergeysviridenko** [comment]
I can't reproduce.
Phalcon DevTools Version: 3.2.0
Phalcon Version: 3.1.2
