### ISSUE TITLE
Any reason for bootstrap 2.3 still and not updated to 3+?

### ISSUE THREAD

**Issue by BonnieDoug** [phalcon/phalcon-devtools#321]
Any reason for bootstrap 2.3 still and not updated to 3.3.2 (current version).

Have just spent around an hour working out why my NavBar wasn't working, till I realized it was using the old Bootstrap files.

I have no problem creating a PR updating the classes etc, but don't want to do it if there is a legit reason not to.

**Comment by phalcon** [comment]
I think it must be updated

**Comment by sergeyklay** [comment]
@BonnieDoug Done. See 2.0.x branch
