### ISSUE TITLE
phalcon create-all-models wrong room

### ISSUE THREAD

**Issue by haniefhan** [phalcon/phalcon-devtools#322]
I use this project builder
" phalcon project new micro"

then I use "phalcon create-all-models"
the result is
" Phalcon DevTools (1.3.4)

Warning: include(app/config/config.php): failed to open stream: No such file or directory in D:\new_xampp\phalcon-tools\scripts\Phalcon\Commands\Builtin\AllModels.php on line 83

Warning: include(): Failed opening 'app/config/config.php' for inclusion (include_path='.;D:\new_xampp\php\PEAR') in D:\new_xampp\phalcon-tools\scripts\Phalcon\Commands\Builtin\AllModels.php on line 83

Notice: Trying to get property of non-object in D:\new_xampp\phalcon-tools\scrip
ts\Phalcon\Commands\Builtin\AllModels.php on line 87

Notice: Trying to get property of non-object in D:\new_xampp\phalcon-tools\scrip
ts\Phalcon\Commands\Builtin\AllModels.php on line 87

Notice: Use of undefined constant APP_PATH - assumed 'APP_PATH' in D:\new_xampp\
htdocs\jadwaldoc-api\config\config.php on line 15

Notice: Use of undefined constant APP_PATH - assumed 'APP_PATH' in D:\new_xampp\
htdocs\jadwaldoc-api\config\config.php on line 16

Notice: Use of undefined constant APP_PATH - assumed 'APP_PATH' in D:\new_xampp\
htdocs\jadwaldoc-api\config\config.php on line 15

Notice: Use of undefined constant APP_PATH - assumed 'APP_PATH' in D:\new_xampp\
htdocs\jadwaldoc-api\config\config.php on line 16

  Success: Model "day" was successfully created. "

it works, but the file is in folder 'views'.
can you please fix this bug?

**Comment by rzZzv** [comment]
try this fix that i made https://github.com/phalcon/phalcon-devtools/pull/317
it worked for me

**Comment by sergeyklay** [comment]
@haniefhan Can u test now?
