### ISSUE TITLE
all-models --extends breaks on second run

### ISSUE THREAD

**Issue by agustinsaldias** [phalcon/phalcon-devtools#323]
For some reason, when trying to generate all models after running the --extends parameter on the first run, devtools won't work as it can't include, for some reason, the extends class.

For example, if I had this in my model:
```php
<?php
class ModelTwo extends \Phalcon\Mvc\Model
{
```
And then run 
```bash
phalcon all-models --extends=ModelOne
```
I get this as result
```php
<?php
class ModelTwo extends ModelOne
{
```
So everything seems to be running just fine...but...next time I try to run the generator with --force to override the models
```bash
phalcon all-models --extends=ModelOne --force
```
I get a fatal error:
>Fatal Error: Class 'ModelOne' not found in ModelTwo.php line X

As soon as I manually revert the extends line on each model to \Phalcon\Mvc\Model, it works just fine again. (only one extra time, as I have to manually change them every time)

Is there something I'm missing here? Or is this a problem? I'm on windows, if that makes a difference.

**Comment by 7thcubic** [comment]
i have a similar issue with model but its when i already generated the model once and made changes to the database so when i used --force it gave me 2 column map and getsource methods.

I believe its because the model builder is inheriting them from the previous files.

Could you post the files generated so i can better judge where its breaking.

**Comment by 7thcubic** [comment]
well do you have a ModelOne anywhere?
Is your model namespaced?

As you can see if you have loaded Model one in a namespace you are required to provide the full class declaration.

Eg.
```php
namespace Common\Models {
class ModelBase extends \Phalcon\Mvc\Model {
}
}
```

During run time of your phalcon web you would require a loader that has already loaded that model using the auto loaders.

And when you run the generate model you have to use --extends=Common\Model\ModelBase

**Comment by sergeyklay** [comment]
@agustinsaldias Can you test now please?
