### ISSUE TITLE
webtools config causing blank screen and missing directories

### ISSUE THREAD

**Issue by cgfix** [phalcon/phalcon-devtools#329]
I found the following bugs in webtools that prevented it from working at all
symptoms:
Controller page: "Please specify a controller directory"
Model page: "Database configuration cannot be loaded from your config file"
scaffold page :"Adapter was not found in the config. Please specify a config variable [database][adapter]"
migration page: blank screen

Solution I found:
1:  migrations config path not correct in migrationController
    in phalcon\devtools\scripts\Phalcon\Web\Tools\controllers\migrationController.php
   I had to change line 32 to $migrationsDir = '../app/migrations';

2:  _getConfig not returning correct path
   in phalcon\devtools\scripts\Phalcon\Builder\Component.php
   I had to change line 60 to 
        foreach (array('/../app/config/','../app/config/','app/config/', 'config/') as $configPath) {

**Comment by sergeyklay** [comment]
Fixed in 2.0.x
