### ISSUE TITLE
Migration fails for immediate predecessor/successor version

### ISSUE THREAD

**Issue by vbojan** [phalcon/phalcon-devtools#334]
Migration doesn't execute correctly to an immediate previous/next version and only updates the current version, but doesn't make any changes to the database.
For example, rolling back from 1.0.3 to 1.0.2 will just update current version to 1.0.2, but will not execute database update. Same goes from 1.0.3 to 1.0.4.
However, migrating from 1.0.3 to 1.0.1, to 1.0.4, or any other version works fine.

It looks like the culprit is inside \scripts\Phalcon\Version\Item.php on line #166 where this:

```            if (($version->getStamp() > $initialVersion->getStamp()) && ($version->getStamp() <= $finalVersion->getStamp())) {```

should be replaced with this (which includes the immediate previous/next version):

```            if (($version->getStamp() >= $initialVersion->getStamp()) && ($version->getStamp() <= $finalVersion->getStamp())) {```

**Comment by sergeyklay** [comment]
Can u send PR please?

**Comment by sergeyklay** [comment]
@vbojan Can you try again please? It seems now works fine

**Comment by vbojan** [comment]
I tested new version and incremental upgrades are now working fine, but incremental downgrades are still broken (i.e. 1.0.2 goes fine to 1.0.3, but doesn't do anything if you want to get from 1.0.2 down to 1.0.1).

**Comment by sergeyklay** [comment]
@vbojan Can you test now `master` please?

**Comment by vbojan** [comment]
Still the same :(
Upgrading works fine, but incremental downgrading doesn't.

**Comment by sergeyklay** [comment]
@vbojan Can you please test now `2.0.1` branch?

**Comment by sergeyklay** [comment]
@vbojan ping

**Comment by vbojan** [comment]
I tested it in 2.0.7 when it came out, but it still behaves the same.

**Comment by sergeyklay** [comment]
@vbojan Can you please check `2.0.x` branch?

**Comment by vbojan** [comment]
@sergeyklay This doesn't appear to be an issue anymore.
However, I noticed several other issues which I understand are limitation on the migration side, but can you include support for comments?

**Comment by sergeyklay** [comment]
Yes, create separated issue
