### ISSUE TITLE
nginx php-fpm new project error

### ISSUE THREAD

**Issue by pro100master** [phalcon/phalcon-devtools#368]
there r some errors 
-1- try
root: /home/user/www
#cd /home/user
#phalcon project test
/home/user/test/ and /home/user/test/public/ - outside server root

-2- try
root: /home/user/www
#cd /home/user/www
#phalcon project test
created /home/user/www/test/ inside server root - ok, but project public directory not in www-root
ok, try 3rd variant

-3-
root: /home/user/test/public/
#cd /home/user
#phalcon project test
created /home/user/test/ ok, /home/user/test/public is a valid webroot, uri is /, project root is /home/user/test/
#phalcon webtools --action=enable
ok
lets open www.domain.tld/webtools.php 
ok
but all assets and links hrefs looking for uri - /test/ wtf?

**Comment by sergeyklay** [comment]
```sh
$ cd /home/user
$ phalcon project --name myapp
$ cd /home/user/myapp
$ sed -i.bak -e "s/myapp\///g" app/config/config.php
```

You need to change the baseUri to your needs. See `baseUri` in config file.
