### ISSUE TITLE
Create model in Micro project ERROR: Use of undefined constant APP_PATH 

### ISSUE THREAD

**Issue by xerron** [phalcon/phalcon-devtools#407]
create project:

    phlacon project myproject --type=micro

and when I create a model:

    phalcon model user

Bug!

PHP Notice:  Use of undefined constant APP_PATH - assumed 'APP_PATH' in /Users/xerrron/Documents/Projects/Web/jobs-api/config/config.php on line 15
PHP Notice:  Use of undefined constant APP_PATH - assumed 'APP_PATH' in /Users/xerrron/Documents/Projects/Web/jobs-api/config/config.php on line 16
PHP Notice:  Use of undefined constant APP_PATH - assumed 'APP_PATH' in /Users/xerrron/Documents/Projects/Web/jobs-api/config/config.php on line 17

My config.php

<?php

return new \Phalcon\Config(array(

    'database' => array(
        'adapter'    => 'Mysql',
        'host'       => '127.0.0.1',
        'username'   => 'root',
        'password'   => '',
        'dbname'     => 'db_jobboard',
        'charset'    => 'utf8',
    ),

    'application' => array(
        'modelsDir'      => APP_PATH . '/models/',
        'migrationsDir'  => APP_PATH . '/migrations/',
        'viewsDir'       => APP_PATH . '/views/',
        'baseUri'        => '/phalcontest/',
    )
));

Solve the problem temporarily with the following code.

define('APP_PATH2', realpath('.'));

return new \Phalcon\Config(array(

    'database' => array(
        'adapter'    => 'Mysql',
        'host'       => '127.0.0.1',
        'username'   => 'root',
        'password'   => '',
        'dbname'     => 'db_jobboard',
        'charset'    => 'utf8',
    ),

    'application' => array(
        'modelsDir'      => APP_PATH2 . '/models/',
        'migrationsDir'  => APP_PATH2 . '/migrations/',
        'viewsDir'       => APP_PATH2 . '/views/',
        'baseUri'        => '/phalcontest/',
    )
));

but should correct the template of micro project.

thank you.!

**Comment by sergeyklay** [comment]
Can you create PR please to 2.0.x?

**Comment by xerron** [comment]
I use Devtools 2.0.0 and not --version exits.

    > phalcon project

    Phalcon DevTools (2.0.0)

    Help:
    Creates a project

    Usage:
    project [name] [type] [directory] [enable-webtools]

    Arguments:
    help	Shows this help text

    Example
    phalcon project store simple

    Options:
    --name               Name of the new project
    --enable-webtools    Determines if webtools should be enabled [optional]
    --directory=s        Base path on which project will be created [optional]
    --type=s             Type of the application to be generated (cli, micro, simple, modules)
    --template-path      Specify a template path [optional]
    --use-config-ini     Use a ini file as configuration file [optional]
    --trace              Shows the trace of the framework in case of exception. [optional]
    --help               Shows this help

I guess it is for the version 2.0.x?

**Comment by xerron** [comment]
work in the branch 2.0.x

add line in config.php in micro template:

    defined('APP_PATH') || define('APP_PATH', realpath('.'));

thank you!,,     muchas gracias por la respuesta.
