### ISSUE TITLE
[BUG] [2.0.x] using template-path when creating project 

### ISSUE THREAD

**Issue by le51** [phalcon/phalcon-devtools#408]
Hi,

phalcon project test4 --template-path=tata --directory=toto

var_dump($this->options) returns in Phalcon\Builder\Project\Simple

```
class Phalcon\Builder\Options#22 (7) {
  public $name => string(5) "test4"
  public $type => string(6) "simple"
  public $directory => string(4) "toto"
  public $enableWebTools => bool(false)
  public $templatePath => bool(true) // Here parameter is not passed to $config 
  public $useConfigIni => NULL
  public $projectPath => string(11) "toto/test4/"
}
```

"tata or 'tat' doesn't work as well.

**Comment by le51** [comment]
Solution:

in Phalcon\Commands\Builtin\Project

'template-path=s'   => 'Specify a template path [optional]',    // add the "s"

**Comment by le51** [comment]
But now

PHP Warning:  file_get_contents(tata/project/simple/.htrouter.php): failed to open stream

Right now tata folder and its content is in "templates" folder.

**Comment by sergeyklay** [comment]
@le51 copy to template `.htrouter.php`

**Comment by sergeysviridenko** [comment]
I couldn't reproduce.
You should use absolute path or relative path from your location, then template-path works well.
Phalcon DevTools Version: 3.2.0
Phalcon Version: 3.1.2
