### ISSUE TITLE
Function columnMap is added twice to the model

### ISSUE THREAD

**Issue by osse76** [phalcon/phalcon-devtools#414]
Same problem - #276
Create model with force, the function columnMap is added twice to the model

**Comment by sergeyklay** [comment]
Can you please try 2.0.x branch?

**Comment by osse76** [comment]
In this branch, the method columnMap is not generated anytime. But the methods find, findFirst and getSource be generated. This three methods were not generated in master branch.

**Comment by sergeyklay** [comment]
The `master` branch is freezed. All improvements, fixes and new features appear in `2.0.x` first.
After release of Phalcon 2.0.2 we merge phalcon-devtools `2.0.x` into `master`.

**Comment by sergeyklay** [comment]
@osse76 Check now in `master` please

**Comment by osse76** [comment]
Works. :thumbsup:
