### ISSUE TITLE
Phalcon migration Generate/Run error with Postgresql

### ISSUE THREAD

**Issue by kimthangatm** [phalcon/phalcon-devtools#419]
Generate and run success with MySql but error on Postgres with SCHEMA.

I think team add new video demo for Postgres sample as Mysql (Youtube: https://www.youtube.com/watch?v=Vx-9GiZt68I)

**Comment by whdigger** [comment]
What manifest error ?

**Comment by kimthangatm** [comment]
Command error
```
zaichi$ phalcon migration run

Phalcon DevTools (2.0.3)

1436242153.4626: SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END FROM information_schema.tables WHERE table_schema = 'cms_old' AND table_name='bug_tracking'  => 1436242153.473 (0.010378122329712)
1436242153.4736: SELECT DISTINCT c.column_name AS Field, c.data_type AS Type, c.character_maximum_length AS Size, c.numeric_precision AS NumericSize, c.numeric_scale AS NumericScale, c.is_nullable AS Null, CASE WHEN pkc.column_name NOTNULL THEN 'PRI' ELSE '' END AS Key, CASE WHEN c.data_type LIKE '%int%' AND c.column_default LIKE '%nextval%' THEN 'auto_increment' ELSE '' END AS Extra, c.ordinal_position AS Position, c.column_default FROM information_schema.columns c LEFT JOIN ( SELECT kcu.column_name, kcu.table_name, kcu.table_schema FROM information_schema.table_constraints tc INNER JOIN information_schema.key_column_usage kcu on (kcu.constraint_name = tc.constraint_name and kcu.table_name=tc.table_name and kcu.table_schema=tc.table_schema) WHERE tc.constraint_type='PRIMARY KEY') pkc ON (c.column_name=pkc.column_name AND c.table_schema = pkc.table_schema AND c.table_name=pkc.table_name) WHERE c.table_schema='cms_old' AND c.table_name='bug_tracking' ORDER BY c.ordinal_position  => 1436242153.5224 (0.048776149749756)
                                                        
Error: Trying to call method getname on a non-object
```

**Comment by whdigger** [comment]
Add please dump table bug_tracking or table_schema  cms_old

**Comment by kimthangatm** [comment]
You need create new phalcon project with Postgres Dev Tool and Test migrate.

Sample:
Step 1: Create Db and create table
```sql
CREATE SCHEMA test;

CREATE TABLE test.bug_tracking (
    id integer NOT NULL,
    bug_tracking_priority_id integer,
    bug_tracking_type_id integer,
    bug_tracking_status_id integer DEFAULT 1,
    role_id integer,
    description text,
    image text,
    fixed_at timestamp without time zone,
    fixed_by integer,
    created_at timestamp without time zone,
    created_by integer,
    updated_at timestamp without time zone,
    updated_by integer
);
```
Step 2: generate migrate => version 1.0.0
```
phalcon migration generate
```

Step 3: Add column and generate
```
ALTER TABLE test.bug_tracking ADD COLUMN column1 VARCHAR(32)
phalcon migration generate
```

Step 4: Remove column1 AND run migration
```
ALTER TABLE test.bug_tracking DROP column1;
phalcon migration run
```

**Comment by mtxr** [comment]
How is it going? Is there anyone fixing it?

**Comment by sergeyklay** [comment]
Hi. I'll try to deal with this in the near future

**Comment by Green-Cat** [comment]
fixed in #614 #615.

**Comment by rLoka** [comment]
Hi there,
I encountered same as @kimthangatm khimgathm and applied fix #614  and now I get this upon migration:
`Warning: file(C:\xampp\htdocs\project\.phalcon/migration-version): failed to open stream: No such file or directory in C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Migrations.php on line 420

Call Stack:
    0.0003     133336   1. {main}() C:\Users\Skywalker\Documents\phalcon-devtools\phalcon.php:0
    0.0076     531632   2. Phalcon\Script->run() C:\Users\Skywalker\Documents\phalcon-devtools\phalcon.php:86
    0.0076     531904   3. Phalcon\Script->dispatch() C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Script.php:150
    0.0082     533728   4. Phalcon\Commands\Builtin\Migration->run() C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Script.php:125
    0.0096     611944   5. Phalcon\Migrations::run() C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Commands\Builtin\Migration.php:130
    0.0311     813712   6. Phalcon\Migrations::getCompletedVersions() C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Migrations.php:219
    0.0311     813744   7. file() C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Migrations.php:420


Warning: array_flip() expects parameter 1 to be array, boolean given in C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Migrations.php on line 423

Call Stack:
    0.0003     133336   1. {main}() C:\Users\Skywalker\Documents\phalcon-devtools\phalcon.php:0
    0.0076     531632   2. Phalcon\Script->run() C:\Users\Skywalker\Documents\phalcon-devtools\phalcon.php:86
    0.0076     531904   3. Phalcon\Script->dispatch() C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Script.php:150
    0.0082     533728   4. Phalcon\Commands\Builtin\Migration->run() C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Script.php:125
    0.0096     611944   5. Phalcon\Migrations::run() C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Commands\Builtin\Migration.php:130
    0.0311     813712   6. Phalcon\Migrations::getCompletedVersions() C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Migrations.php:219
    0.0764     814440   7. array_flip() `C:\Users\Skywalker\Documents\phalcon-devtools\scripts\Phalcon\Migrations.php:423`

**Comment by sergeyklay** [comment]
@rLoka Try please latest `2.1.x`

**Comment by rLoka** [comment]
@sergeyklay It works now. Thanks much :)
