### ISSUE TITLE
\Phalcon\Db\ColumnInterface Type: BLOB?

### ISSUE THREAD

**Issue by mattvb91** [phalcon/phalcon-devtools#424]
Have just noticed that when I am generating migrations on a table that includes a field of type BLOB/MEDIUMBLOB/LONGBLOB there is no such column on ColumnInterface.

Currently it looks like it will just default it to varchar. Am I missing something obvious?

**Comment by Green-Cat** [comment]
Phalcon does not have support for non-standard SQL types.
BLOB is MySQL specific.
Not sure if there is a work around.

**Comment by mattvb91** [comment]
Would it be possible for me to write my own \Phalcon\Db\ColumnInterface\Mysql adapter and that then be included in the project? 

The dev tools are written in php so I shouldn't need any C level coding?

**Comment by mattvb91** [comment]
For anyone else that comes across this issue I have added a pull request to the main cphalcon repo. 

https://github.com/phalcon/cphalcon/pull/10506

If this goes in I will also push an update for migration generation blob support to this repo. 
What is the procedure for updating IDE stubs?

**Comment by sergeyklay** [comment]
Run 
```sh
zephir stubs
```
