### ISSUE TITLE
default value not being set up

### ISSUE THREAD

**Issue by stefanchiriac** [phalcon/phalcon-devtools#429]
Hello,

If I set a default value doesn't seems to be considered when I run the migration

```php
new Column('status', [
    'type'    => Column::TYPE_INTEGER,
    'notNull' => true,
    'size'    => 1,
    'default' => 0,
    'after'   => 'role_id'
]);
```

There are any plans to add support for bigint, tinyint, timestamp?

Thanks

**Comment by mattvb91** [comment]
I have just recently added pull request to the main phalcon repo because I needed to support blob types.

When I get time I will push bigint,tinyint and timestamp too. Hopefully they will make it into the 2.0.4 release.

**Comment by stefanchiriac** [comment]
@mattvb91 That sounds nice. Do you have problems with default value not being set up or is just me?

**Comment by mattvb91** [comment]
I seem to be having the same issue as you. Running v2.0.3 of the devtools.

I will look into this the same time as adding support for the new datatypes. I will update this issue if I have a branch you can test on.

**Comment by stefanchiriac** [comment]
any news about this issue?

**Comment by sergeyklay** [comment]
@stefanchiriac Curently we can add only `Column::TYPE_BIGINTEGER` because tinyint and timestamp isn't supported in Phalcon.

Can you explain please about "default values" related issue?

**Comment by stefanchiriac** [comment]
the problem is with mysql/mariadb when you have a default value on a column.
If you generate a migration from a table, all default values are ignored and don't appear in your migration code.
If you run a migration the column default value is ignored and is not set in db. For running a migration and missing types a work around is defining everything on type

                    new Column('created_at', array(
                            'type' => "TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP",
                        )
                    ),

**Comment by sergeyklay** [comment]
I tried to fix this behaviour. Can you please check it now on 2.0.x branch? But note currently Phalcon does not support Columt::TYPE_TIMESTAMP

**Comment by stefanchiriac** [comment]
now seems to work to generate and apply a migration with default value, except when 'default' => 0. In this case the value is being ignored

**Comment by sergeyklay** [comment]
I'll try to deal with it

**Comment by sergeyklay** [comment]
@stefanchiriac Now Phalcon supports `Columt::TYPE_TIMESTAMP` (in  2.0.x branch)

**Comment by sergeyklay** [comment]
@stefanchiriac I tried to fix "default value" related issue. Can you please check it now in 2.0.x branch?

**Comment by stefanchiriac** [comment]
I did some debugging myself and seems like the problem comes from the framework.
I ran directly modifyColumn and createTable functions and no luck

    self::$_connection->modifyColumn($tableName, $tableColumn->getSchemaName(), $tableColumn);
    self::$_connection->createTable($tableName, $defaultSchema, $definition);

**Comment by sergeyklay** [comment]
@stefanchiriac I've fixed default value in Phalcon (2.0.x branch) https://github.com/phalcon/cphalcon/pull/10849. Can you please build Phalcon from 2.0.x branch and check now?

**Comment by sergeyklay** [comment]
@stefanchiriac You can try now with Phalcon 2.0.x

```php
new Column('created_at', [
    'type'    => Column::TYPE_TIMESTAMP,
    'notNull' => true,
    'default' => 'CURRENT_TIMESTAMP'
]);
```

**Comment by stefanchiriac** [comment]
all works fine now. Thanks

**Comment by sergeyklay** [comment]
:+1:
