### ISSUE TITLE
Declaration of Models\Paginate::__construct() must be compatible with Phalcon\Paginator\AdapterInterface::__construct

### ISSUE THREAD

**Issue by ilyaskorik** [phalcon/phalcon-devtools#434]
https://github.com/phalcon/cphalcon/issues/10521

**Comment by sergeyklay** [comment]
Can you please create a PR fixes this?

**Comment by ilyaskorik** [comment]
No, I am not competent. If you are the mainteiner of the project, you can add all-just one word in a single file to correct this problem.

**Comment by sergeyklay** [comment]
Thanks. Fixed
