### ISSUE TITLE
"Notice: Indirect modification of overloaded element..." and doubling relations

### ISSUE THREAD

**Issue by jrafaelg** [phalcon/phalcon-devtools#440]
When I generate models, with namespace setted, a get this error:

```
Notice: Indirect modification of overloaded element of Phalcon\Config has no effect in D:\phalcon-devtools\scripts\Phalcon\Builder\Model.php on line 321
```

![sem titulo](https://cloud.githubusercontent.com/assets/4106965/8554053/d3a32fae-24bd-11e5-9a23-380764c80167.png)

line 321:

```
$relation['options']['alias'] = $entityName;
```

in the real file, [this line](https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Builder/Model.php#L272)

doubling of code:

``` php
$this->belongsTo('id_usuario', 'sicop\Pessoa', 'id_pessoa', array('alias' => 'Pessoa'));
$this->belongsTo('id_usuario', 'sicop\Pessoa', 'id_pessoa', array('foreignKey' => true,'alias' => 'Pessoa')); // add a foreignKey parameter, but kept the previous line
```

**Comment by drodriguezgood** [comment]
He tenido el mismo problema al utilizar la ultima version de phalcon-devtools con el comando
 $ phalcon all-models --directory=apps/seguridad --config=config/config.php --models=models --schema=seguridad --namespace=Lacteos\\Seguridad\\Models --force --relations


me genera este error 
PHP Notice:  Indirect modification of overloaded element of Phalcon\Config has no effect in /home/daniel/phalcon-devtools/scripts/Phalcon/Builder/Model.php on line 297
PHP Fatal error:  Call to a member function toArray() on a non-object in /home/daniel/phalcon-devtools/scripts/Phalcon/Builder/Model.php on line 305

puedo obviar el parametro --relations para el comando all-models y funciona bien pero el Codigo generado no me hace las referencias en los modelos lo que puedo resolver de momentos es volver a la version que tenia de phalcon-devtools espero que solucionen esto pronto.

**Comment by sergeysviridenko** [comment]
I couldn't reproduce both of these situations.
Phalcon DevTools Version: 3.2.0 ALPHA 1
Phalcon Version: 3.1.2
