### ISSUE TITLE
Old versions make devtools bulky

### ISSUE THREAD

**Issue by salarmehr** [phalcon/phalcon-devtools#441]
When is simple command `php gen-stubs.php` can generate all stubs, is there any reason to keeping old versions stub on repository? I hvae to manually remove all of them so phpstorm can use the last version only.

**Comment by sergeyklay** [comment]
Done

**Comment by sergeyklay** [comment]
@salarmehr  about old versions https://github.com/phalcon/phalcon-devtools/pull/398
