### ISSUE TITLE
Problem running dev tools

### ISSUE THREAD

**Issue by pavlovt** [phalcon/phalcon-devtools#45]
Hi,

I received the following error with dev tools on command:
phalcon commands
ERROR: Phalcon extension isn't installed, follow these instructions to install it: http://phalconphp.com/documentation/install

I use Ubuntu Linux server, PHP 5.3, Phalcon 0.9
I have the invo app installed and it works without any problem

Regards,
Todor

**Comment by lukaszmargielewski** [comment]
I have the same problem on Mac Yosemite using MAMP webserver. phpinfo() shows phalcon extension loaded, but dev tools sclaims no extension loaded. What to do?

**Comment by sergeyklay** [comment]
@lukaszmargielewski Can you please provide output of command?:
```sh
php -m | grep phalcon
```

**Comment by andresgutierrez** [comment]
@lukaszmargielewski or to locate the php.ini

```
php -i | grep Loaded
```

**Comment by DDhawan** [comment]
this works thank you.
