### ISSUE TITLE
Missing functions in Phalcon\Session\BagInterface

### ISSUE THREAD

**Issue by dParadiz** [phalcon/phalcon-devtools#456]
Shouldn't following function be defined in Phalcon\Session\BagInterface?

```
public function remove($index) {}

public function __unset($index) {}
```

**Comment by sergeyklay** [comment]
What do you mean?

**Comment by dParadiz** [comment]
Well Phalcon\Session\Bag has thus functions implemented, but they are not declared in interface.
So you need to depend on concrete implementation of Session\Bag to ensure that functions are available. Maybe it is just me but I don't see any reason why this functions are not part of BagInterface.

**Comment by sergeyklay** [comment]
This is not devtools issue. Please create a new feature request on https://github.com/phalcon/cphalcon repo
