### ISSUE TITLE
Remove the IDE stubs for every version and sync with versions

### ISSUE THREAD

**Issue by virgofx** [phalcon/phalcon-devtools#457]
Please remove the included every version of the IDE stubs. This makes it very annoying within the IDEs to have 20+ copies for autocomplete as well as duplicating code which is very bad practice -- this defeats the whole purpose of version control.

If I wanted phalcon-devtools for 1.3.5 I would checkout or pull via composer the specific version.

The version in source control should correspond to the same version branch/tag as the /phalcon/cphalcon repository.

**Comment by rianorie** [comment]
+1

**Comment by sergeyklay** [comment]
Possible refs #398
