### ISSUE TITLE
the error about Build .phar

### ISSUE THREAD

**Issue by qetee** [phalcon/phalcon-devtools#459]
<img width="1440" alt="qq20150731-1 2x" src="https://cloud.githubusercontent.com/assets/2811986/8989918/bf115b4e-3721-11e5-9be8-fa38e7125cc8.png">
I used box to build phalcon.phar successfully, but when i excute "phalcon.phar project xxx", the error bellow shows:

PHP Warning:  file_get_contents(phar:///Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar/templates/project/simple/config.php): failed to open stream: phar error: "templates/project/simple/config.php" is not a file in phar "/Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar" in phar:///Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar/scripts/Phalcon/Builder/Project/ProjectBuilder.php on line 124

Warning: file_get_contents(phar:///Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar/templates/project/simple/config.php): failed to open stream: phar error: "templates/project/simple/config.php" is not a file in phar "/Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar" in phar:///Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar/scripts/Phalcon/Builder/Project/ProjectBuilder.php on line 124
PHP Warning:  file_get_contents(phar:///Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar/templates/project/simple/loader.php): failed to open stream: phar error: "templates/project/simple/loader.php" is not a file in phar "/Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar" in phar:///Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar/scripts/Phalcon/Builder/Project/ProjectBuilder.php on line 124

Warning: file_get_contents(phar:///Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar/templates/project/simple/loader.php): failed to open stream: phar error: "templates/project/simple/loader.php" is not a file in phar "/Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar" in phar:///Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar/scripts/Phalcon/Builder/Project/ProjectBuilder.php on line 124
PHP Warning:  file_get_contents(phar:///Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar/templates/project/simple/services.php): failed to open stream: phar error: "templates/project/simple/services.php" is not a file in phar "/Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar" in phar:///Users/viggo/Desktop/phalcon-devtools 2/phalcon.phar/scripts/Phalcon/Builder/Project/ProjectBuilder.php on line 124

etc...

**Comment by denji** [comment]
box.json:
```json
{
  "directories": [
    "resources",
    "scripts",
    "templates"
  ],
  "files": "webtools.php",
  "finder": [
    {
      "exclude": [
        "CONTRIBUTING.md",
        "README.md",
        "LICENSE",
        "phalcon.bat",
        "phalcon.sh"
      ]
    }
  ],
  "git-version": "git_tag",
  "main": "phalcon.php",
  "output": "phalcon.phar",
  "stub": true
}
```

**Comment by sergeyklay** [comment]
now this fixed?
