### ISSUE TITLE
Scaffold creation error

### ISSUE THREAD

**Issue by SelimSalihovic** [phalcon/phalcon-devtools#468]
I have tried to do "phalcon scaffold bears" and I got this error:

Phalcon DevTools (2.0.6)

PHP Parse error:  syntax error, unexpected '[', expecting ')' in /home/vagrant/vendor/phalcon/devtools/scripts/Phalcon/Generator/Snippet.php on line 118

**Comment by sergeyklay** [comment]
what version of php?

**Comment by hasannawaz** [comment]
@SelimSalihovic please use php5.4 or higher for short array syntax.
@andresgutierrez : we need to fix https://docs.phalconphp.com/en/latest/reference/install.html#linux-solaris as it shows requirement php5.3 and below MacOS shows php5.4

**Comment by sergeyklay** [comment]
@hasannawaz Phalcon 2.0.x still require PHP 5.3.x. From Phalcon 2.1.x onwards we are deprecating support for PHP 5.3.  

@SelimSalihovic I've fixed this issue. Can you please check it now in 2.0.x branch?
