### ISSUE TITLE
Script::DOC_INSTALL_URL used before loading class

### ISSUE THREAD

**Issue by lajosbencz** [phalcon/phalcon-devtools#469]
At the check if Phalcon extension is loaded, the Script class is used before actually loading it:

[https://github.com/phalcon/phalcon-devtools/blob/c0ba79d2bd1e915730421c86a5b27d72533bd4f3/phalcon.php#l39](https://github.com/phalcon/phalcon-devtools/blob/c0ba79d2bd1e915730421c86a5b27d72533bd4f3/phalcon.php#l39)

**Comment by sergeyklay** [comment]
Thanks. Fixed
