### ISSUE TITLE
tool generated code got wrong

### ISSUE THREAD

**Issue by hakur** [phalcon/phalcon-devtools#473]
I am new to Phalcon framework,I am worked on windows, by use phalcon.bat ,download from release 2.0.7,and I use "phalcon create-project phalcon --type=modules"

the router got wrong in /config/routes.php

In first line the code is 
```
$router = $di->get("router");
```
and it not worked on url 
```
http://localhost/phalcon/frontend
```
so I change to
```
$router = $application->router;
```
it worked on url 
```
http://localhost/phalcon/frontend
http://localhost/phalcon/frontend/index
http://localhost/phalcon/frontend/index/index
```

in /public/index.php first create application and then include /config/routes.php

did i got somthing wrong ? or another should attention?

hope you can understand my chinglish

**Comment by sergeyklay** [comment]
Fixed. Thanks
