### ISSUE TITLE
Problem installing via composer with php fcgi

### ISSUE THREAD

**Issue by Izopi4a** [phalcon/phalcon-devtools#483]
Hello,

I have problems installing phalcon-devtools with composer, i get this message

 - Installation request for phalcon/devtools dev-master -> satisfiable by phalcon/devtools[dev-master].
- phalcon/devtools dev-master requires ext-phalcon ~2.0 -> the requested PHP extension phalcon is missing from your system.

So.. on my server I use different php versions for every host.

the php version i use for phalcon is working fine, since i see it in phpinfo, and the website is working :) 

composer.json file:

```
{
    "require": {
        "phalcon/devtools": "dev-master"
    }
}
```

what i do is : /opt/php/php5612/bin/php composer install

Could anyone assist me with this issue please ?

**Comment by sergeyklay** [comment]
Hello @Izopi4a 
We only accept bug reports, new feature requests and pull requests. For questions regarding the usage of the Phalcon Developer Tools or support requests please visit the [official forums](http://forum.phalconphp.com/).
