### ISSUE TITLE
Database migrations missing multiple features.  Source and destination schemas do not match on various features.

### ISSUE THREAD

**Issue by hi2u** [phalcon/phalcon-devtools#487]
I'm using devtools 2.0.7 with a MySQL database.

When I generate database migrations from my tables on my development server, it doesn't seem to store any info about the "ON UPDATE" and "ON DELETE" ... "RESTRICT / CASCADE / SET NULL / NO ACTION" settings for the foreign keys in the migration files.  

So obviously when running the migrations on the live server, it has no way to know that I've got some ON UPDATE/DELETE settings on my foreign keys, so it just leaves them on the default of "RESTRICT".

Is this just something that hasn't been implemented yet?

I assume it's the same for PostgreSQL migrations.

**Comment by hi2u** [comment]
I've discovered a couple more issues with migrations...

1. A SMALLINT column on the source database gets set up an INT column on the destination.  There doesn't seem to be any differentiator, as the migration file just considers records that it is a 'type' => Column::TYPE_INTEGER  -  I haven't put any more research into this, but I assume there may be similar issues with other MySQL specific column types.

2. Unique Indexes are just set up as regular non-unique indexes on the destination.

I appreciate all the effort that has gone into the migrations functionality, however I don't think Phalcon's internal data classes (e.g: "Column::TYPE_INTEGER") are suitable for accurately handling SQL migrations, because they're not aware of differences such as a SMALLINT vs an INT and a regular index vs a unique one etc.  And it is kind of out-of-scope for Phalcon itself to be aware of every single MySQL and PostgreSQL schema feature.

Maybe this is something where we shouldn't be re-inventing the wheel?  If some of these features mentioned above don't work, I assume there's more missing functionality that is getting lost in translation, especially for anybody using some of the more advanced SQL features.

For now I'll continue to use https://github.com/mmatuson/SchemaSync for my "dev to live" schema migrations.  It hasn't been updated since 2012, but it seems to cover all the MySQL features I'm using and has served me well over the last few years.

**Comment by OakBehringer** [comment]
I am running into this, too, with the foreign key ON UPDATE/DELETE stuff. Bummer. Good to know about SchemaSync!

**Comment by sergeysviridenko** [comment]
As to ON UPDATE/DELETE, it was fixed and works fine now.

As to column type - Phalcon uses types that are general for several DB, not just for MySQL.
And #178 is for this issue.
I assume this issue can be closed.

Phalcon DevTools Version - 3.2.0
Phalcon Version - 3.2.1
