### ISSUE TITLE
IDE stubs - getMessages from model

### ISSUE THREAD

**Issue by Jurigag** [phalcon/phalcon-devtools#491]
On 2.0.7 when i getMessages() from my model, and then loop it, it doesnt detect getField and getMessage method, on 2.0.3 it was working fine. What changed ?

**Comment by sergeyklay** [comment]
Because in phpdoc `Model::getMessages()` returns `\Phalcon\Mvc\Model\MessageInterface` instead `\Phalcon\Mvc\Model\MessageInterface[]`.
