### ISSUE TITLE
Migration "run" doesn't work after #492

### ISSUE THREAD

**Issue by DroneZzZko** [phalcon/phalcon-devtools#496]
Once #492 (https://github.com/phalcon/phalcon-devtools/commit/c6308c861e7024151a9d0ffd17cc2137035a9ad1#diff-6a5696107288f5bf2220fe586bf6954bR202) was merged impossible to run migration if there is only one generated migration version (1.0.0). And --force also doesn't work.
How to reproduce:
1. Generate a migration (.phalcon and migrations dirs are empty): 
*./vendor/phalcon/devtools/phalcon.php migration generate --config=common/config/config.php --migrations=migrations --data=always*
2. On the server (DB and .phalcon are empty) try to run the migration from step 1:
*./vendor/phalcon/devtools/phalcon.php migration run --config=common/config/config.php --migrations=migrations*
4. It was expected that the migration ran successfully, but nothing happened.

**Comment by sergeyklay** [comment]
@DroneZzZko Can you please check now  on `2.0.x` branch?

**Comment by DroneZzZko** [comment]
Checked. The issue seems to be fixed.
