### ISSUE TITLE
Generate migration with --data option adds unwanted single quotation marks

### ISSUE THREAD

**Issue by DroneZzZko** [phalcon/phalcon-devtools#497]
Generate migration with --data option wraps values by unwanted single quotation marks (https://github.com/phalcon/phalcon-devtools/blob/66b628cde63a00ec30c75b2f4ace0c0ca38edbcd/scripts/Phalcon/Mvc/Model/Migration.php#L366):

>1|'male'
>2|'female'

If try to run migration after that we get values in table wrapped by single quotes.

**Comment by sergeyklay** [comment]
@DroneZzZko Can you please check now by using `2.0.x` branch?

**Comment by DroneZzZko** [comment]
The issue seems to be fixed. No more quotes in tables.
