### ISSUE TITLE
Migration: Default null fields sets to '0'

### ISSUE THREAD

**Issue by DroneZzZko** [phalcon/phalcon-devtools#504]
Generated .dat files contents '0' values for null fields (by default):
>'220'|'Ukraine'|'0'

Even change '0' to '' and run migration (by "run" command) will be inserted 0.

**Comment by sergeyklay** [comment]
@DroneZzZko Can you please provide table schema?

**Comment by DroneZzZko** [comment]
I cannot reproduce this bug.
