### ISSUE TITLE
model generation of getters/setters not correctly using camel case

### ISSUE THREAD

**Issue by GavinMcL** [phalcon/phalcon-devtools#505]
Generating a model with the `--get-set` option, the get/set methods are generated but with incorrect camel case.

e.g.
```php
protected $userId;

public function setUserid($userId)
{
   // ...
}

public function getUserid($userId)
{
   // ...
}
```

ideally these should be `setUserId` and `getUserId` - small issue I know!

**Comment by GavinMcL** [comment]
I think it is working ok; if the database table name is, say user_address, and contains a field user_id, model generation is properly camelcase.

However, I'm working against a (mysql) database which is using camelcase for it's field names, so table useraddress with a field name userId, so the model generator (quite rightly) has no way of determining where the capitalisation should take place.

your code is fine, this isn't a bug, it's my problem!

**Comment by GavinMcL** [comment]
Sorry for being a pain, I'm re-opening, I overlooked something in the generated model.

Our schema has camelcase field names, the model generator is correctly creating the protected member variables in the same camel case as the db field (eg userId, profileAddressId), so it obviously can 'see' the camel case, but it flattens it for get/set methods; maybe the get/set creation isn't figuring out the variable is already camelcase and just want's to use underscore?

thanks.

**Comment by sergeyklay** [comment]
@GavinMcL 

This is Zephir issue https://github.com/phalcon/zephir/issues/1090
I've tried to fix this behavior in DevTools. Can you please check now `2.0.x` branch?

**Comment by sergeyklay** [comment]
@GavinMcL
