### ISSUE TITLE
model generation file and classname incorrect if table name is camelcase

### ISSUE THREAD

**Issue by GavinMcL** [phalcon/phalcon-devtools#511]
Generating a model from a table which has a camel case name produces a php file (and classname) in title case.

e.g.
`table profileAddress`

will generate
`Profileaddress.php`, with `class Profileaddress`

instead of `ProfileAddress.php` with `class ProfileAddress`

works ok if table name is underscore separated (profile_address)

**Comment by sergeyklay** [comment]
@GavinMcL Can you please check now `2.0.x` branch?
