### ISSUE TITLE
Bad phpDoc in documentation

### ISSUE THREAD

**Issue by michalkniotek** [phalcon/phalcon-devtools#514]
phalcon-devtools/ide/2.0.7/Phalcon/http/Request.php

public function getUploadedFiles($onlySuccessful = false) {}

ACTUAL:
@return \Phalcon\Http\Request\File

SHOULD BE ARRAY OF:
@return \Phalcon\Http\Request\File[ ]

**Comment by Green-Cat** [comment]
Nice catch. I'll submit a fix :+1:

**Comment by sergeyklay** [comment]
Fixed in Phalcon `2.0.x`. Next stubs must contains the proper fix. If not, the issue will be opened.
