### ISSUE TITLE
Support for Mysql timestamp

### ISSUE THREAD

**Issue by evan-mark4s** [phalcon/phalcon-devtools#519]
Mysql TIMESTAMP type is not supported. Hope it will be added.

**Comment by sergeyklay** [comment]
Already supported. See #429

**Comment by evan-mark4s** [comment]
Ok, but when I do `phalcon migration generate` all `TIMESTAMP` columns are converted to `Column::TYPE_DATETIME`, please check.

**Comment by sergeyklay** [comment]
Tell please you Phalcon version

**Comment by evan-mark4s** [comment]
Phalcon 2.0.6, installed it using brew. Should I install the latest version?

**Comment by sergeyklay** [comment]
Yes. Phalcon 2.0.6 don't support TIMESTAMP

**Comment by evan-mark4s** [comment]
Ok, thanks for the confirmation.
