### ISSUE TITLE
Incorrect migration on DB with different name

### ISSUE THREAD

**Issue by DroneZzZko** [phalcon/phalcon-devtools#521]
There is a migration file "user.php" containing "'referencedSchema' => 'develop'".
Now I try to run generated migration on another DB with name "production" .
In result all references was created incorrectly (at the table there is no referenced fields).
After removal of  "'referencedSchema' => 'develop'" works well.
Maybe you should add the option to ignore schema?

**Comment by sergeysviridenko** [comment]
@DroneZzZko It works fine for me. I've `'referencedSchema' => 'vokuro'`.
Could you try latest stable version?

Phalcon DevTools Version: 3.2.5
Phalcon Version: 3.2.1
