### ISSUE TITLE
"Operation not permitted" while creating symbolic link on os x el capitan

### ISSUE THREAD

**Issue by mstoelzle** [phalcon/phalcon-devtools#527]
Hi,
I get the error message "Operation not permitted", when I try to create the symbolic link via "ln -s phalcon.php /usr/bin/phalcon". "sudo" doesn't help either. I installed the phalcon-devtools via composer install. I have os x el capitan running. 
Thanks for your help

**Comment by sergeyklay** [comment]
Hi!
Use [Phalcon Vagrant](https://github.com/phalcon/vagrant) setup for Mac:
```sh
$ git clone git@github.com:phalcon/vagrant.git
$ cd vagrant
$ vagrant up
$ vagrant ssh
```

**4** commands, and you are inside pure linux (I mean Ubuntu) with PHP, Phalcon  [etc](https://github.com/phalcon/vagrant#packages-included).

**Comment by mstoelzle** [comment]
Thank you for the answer. I just cloned vagrant, but the "vagrant up" command doesn't work (bash command not found). What did I do wrong?

**Comment by sergeyklay** [comment]
Have you installed [Vagrant for Mac](https://www.vagrantup.com/downloads.html)?

**Comment by mstoelzle** [comment]
Thanks that was the problem

**Comment by sergeyklay** [comment]
Issue can be closed?
