### ISSUE TITLE
Webtools issues with PATH (nginx setup w/o public dir visible)

### ISSUE THREAD

**Issue by stamster** [phalcon/phalcon-devtools#543]
If you use Nginx (or other web server), and tend to configure an dedicated instance in a way to target `your/path/project/public` directly i.e. without the need to redirect `/` requests to `/public/` , your Webtools might fail with things such as Scaffolding since the logic to find a real path is wrong for this setup.

In order to fix Webtools, go for a change in a:
`/path_to/vendor/phalcon/devtools/scripts/Phalcon/Builder`
**File: Path.php**

Method:
```php
public function getConfig($type = null)
```

Find this line at the end of the method:
```php
return new ConfigIni($this->rootPath . $configPath . 'config.ini');
```

Change to:
```php
return new ConfigIni($this->rootPath . $configPath . 'config_tools.ini'); 
```

And setup the new 'config_tools.ini' file in a config directory according to your needs. 

I had to remove all the 'go up directory' from entire application block:
```ini
[application]
controllersDir = ../app/controllers
modelsDir      = ../app/models
migrationsDir  = ../app/migrations
viewsDir       = ../app/views
pluginsDir     = ../app/plugins
libraryDir     = ../app/library
cacheDir       = ../app/cache
```

So the new file looks like:
```ini
controllersDir = app/controllers
modelsDir      = app/models
etc..
```

Afterwards, the Webtools are working just fine.

Hope this will put some light to other nginx users with phalcon :)

**Comment by mjenki03** [comment]
Hi, I am having a similar problem. I am trying to follow a book called Getting Started with Phalcon and neither the webtools nor the command line dev tools work completely.

The webtools can generate the model, the devtools can generate the controller, neither can generate the scaffold. 

"Error: Unable to write to /home/web/phalconBlog/../app/models/Posts.php"

the file directory is not properly resolved and this is using a default generated phalcon project with no changes from the file structure or config so far. :(

**Comment by mjenki03** [comment]
My solution was to just change my config to not use relative paths and everything generated then.

**Comment by sergeyklay** [comment]
So, what do you suggest guys?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
