### ISSUE TITLE
Phalcon-devtools/ide/2.0.2/Phalcon/Http/RequestInterface.php has no comments

### ISSUE THREAD

**Issue by issy123** [phalcon/phalcon-devtools#555]
The file in the title([RequestInterface.php](https://github.com/phalcon/phalcon-devtools/blob/master/ide/2.0.2/Phalcon/Http/RequestInterface.php)) has no comments so the auto-complete in my IDE (netbeans) does not work.

In [version 2.0.0](https://github.com/phalcon/phalcon-devtools/blob/master/ide/2.0.0/Phalcon/http/RequestInterface.php) it has, and also the newer versions (like 2.0.3)

I don't know if it counts for other files too..

**Comment by sergeyklay** [comment]
This was fixed in later versions.
