### ISSUE TITLE
Error in migration creating foreign key with different name

### ISSUE THREAD

**Issue by pavlospap** [phalcon/phalcon-devtools#557]
I am using 2.0.8.
The following code in migrations 

``` php
self::$_connection->addForeignKey(
    'dm_product_module',
    self::getDbName(),
    new Reference('fk_dm_product_module_01', [
        'referencedTable'   => 'dm_product',
        'columns'           => ['product_id'],
        'referencedColumns' => ['id'],
        'onUpdate'          => 'RESTRICT',
        'onDelete'          => 'RESTRICT',
    ])
);
```

produces a foreign key with different name...
In this case the different name is dm_product_module_ibfk_2
MySQL also creates an index with the correct name fk_dm_product_module_01

**Comment by sergeysviridenko** [comment]
I couldn't reproduce.
Phalcon DevTools Version: 3.2.0
Phalcon Version: 3.1.2
