### ISSUE TITLE
[2.1] - phalcon scaffold - Validator::isSetOption() - Deprecated

### ISSUE THREAD

**Issue by rydzyk** [phalcon/phalcon-devtools#559]
Hi

when I want to use scaffold with params:

phalcon scaffold xxxxx --ns-models=admin --ns-control
lers=admin --template-engine=volt --template-path=admin 

i get:
Phalcon DevTools (2.1.0 BETA 2)

Deprecated: Function Phalcon\Validation\Validator::isSetOption() is deprecated i
n C:\SERVER\phalcon\devtools\scripts\Phalcon\Validation\Validator\Namespaces.php
 on line 59

Fatal error: Class 'admin\JobGroups' not found in C:\SERVER\phalcon\devtools\scr
ipts\Phalcon\Builder\Scaffold.php on line 184

reg
GM

**Comment by sergeyklay** [comment]
Will be fixed in Devtools 2.1.x

**Comment by luckamin** [comment]
hi i have problem when load webtools.... help me please
![captura de pantalla 71](https://cloud.githubusercontent.com/assets/14943739/13190942/bf5116e8-d736-11e5-9d4c-26756e62bc47.png)

**Comment by sergeyklay** [comment]
@luckamin
1. Create separated issue
2. Provide please Phalcon version
3. Provide please Devtools version

**Comment by alexbusu** [comment]
Done in #612
