### ISSUE TITLE
migration generate dumps mysql timestamp and enums to wrong types and size

### ISSUE THREAD

**Issue by Dublerq** [phalcon/phalcon-devtools#561]
On my PC Windows instance of Phalcon and Devtools mirgration generates `TIMESTAMP` as `VARCHAR(1)`:
```php
new Column(
    'time',
    array(
        'type' => Column::TYPE_VARCHAR,
        'default' => 'CURRENT_TIMESTAMP',
        'notNull' => true,
        'size' => 1,
        'after' => 'ip'
    )
);
```
and `enum(str1,str,2,str3,str4)` as `char(1)`:
```php
new Column(
    'type',
    array(
        'type' => Column::TYPE_CHAR,
        'notNull' => true,
        'size' => 1,
        'after' => 'id'
    )
);
```

Same happened to friend of mine on his VPS with Debian. On the other hand on my private VPS with Debian 7 and in my office on Windows 7 works great. No idea what causes the problem. 

We're using the newest versions of software on our devices.

**Comment by Dublerq** [comment]
Same happened to other people even a year ago for instance there: https://github.com/phalcon/cphalcon/issues/2580

**Comment by sergeyklay** [comment]
Can you please provide your Phalcon version?

**Comment by Dublerq** [comment]
The issue was present both on Phalcon 2.0.8 and Phalcon 2.0.7. I checked again my office environment and the issue is also present, so I made a mistake before. The easiest way is to reproduce the problem is to migrate a mysql enum with a few strings.

**Comment by sergeyklay** [comment]
Double check with Phalcon `2.0.x` and Devtools `2.0.x`. I've fixed TIMESTAMP issue https://github.com/phalcon/phalcon-devtools/issues/429#issuecomment-135962317

**Comment by Dublerq** [comment]
I'll investigate the timestamp, but what about enum?

**Comment by sergeyklay** [comment]
`enum` is not implemented yet

**Comment by sergeyklay** [comment]
For `enum` create separated issue

**Comment by sergeyklay** [comment]
#562
