### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by gmendonca** [phalcon/phalcon-devtools#563]
Not sure if I should report this here, but I was installing the phalcon-devtools referencing the [website documentation](https://docs.phalconphp.com/en/latest/reference/mactools.html) and there is an error that is actually fixed here in the README.

In the website is showing:
```bash
ln -s ~/phalcon-tools/phalcon.sh ~/phalcon-tools/phalcon
chmod +x ~/phalcon-tools/phalcon
```
But it should be ```~/phalcon-tools/phalcon.php```. This took me a lot of time and I saw a few threads on google with people facing the same problem.

**Comment by sergeyklay** [comment]
Thanks. Fixed
