### ISSUE TITLE
Fatal error when create model with --extend option

### ISSUE THREAD

**Issue by mzf** [phalcon/phalcon-devtools#571]
I create model with this command
```
phalcon model pages2 \
  --name=pages  \
  --output=app/core/Models 
  --extends=Base 
  --namespace=Core\Models 
  --force
```

First time model created successfully. 
If i run second time with existed file i get error
```
Fatal error: Class 'Core\Models\Base' not found in Z:\OpenServer\domains\project\client\trunk\app\core\Models\Pages2.php on line 6

Call Stack:
    0.0000     274976   1. {main}() Z:\OpenServer\domains\phalcon\phalcon-devtools-2\vendor\phalcon\devtools\phalcon.php:0
    0.0070     835712   2. Phalcon\Script->run() Z:\OpenServer\domains\phalcon\phalcon-devtools-2\vendor\phalcon\devtools\phalcon.php:82
    0.0070     836056   3. Phalcon\Script->dispatch() Z:\OpenServer\domains\phalcon\phalcon-devtools-2\vendor\phalcon\devtools\scripts\Phalcon\Script.php:152
    0.0080     840168   4. Phalcon\Commands\Builtin\Model->run() Z:\OpenServer\domains\phalcon\phalcon-devtools-2\vendor\phalcon\devtools\scripts\Phalcon\Script.php:127
    0.0100    1100128   5. Phalcon\Builder\Model->build() Z:\OpenServer\domains\phalcon\phalcon-devtools-2\vendor\phalcon\devtools\scripts\Phalcon\Commands\Builtin\Model.php:98
    0.0480    1153176   6. require('Z:\OpenServer\domains\project\client\trunk\app\core\Models\Pages2.php') Z:\OpenServer\domains\phalcon\phalcon-devtools-2\vendor\phalcon\devtools\scripts\Phalcon\Builder\Model.php:339
```

**Comment by sergeyklay** [comment]
What version of Devtools did you use?

**Comment by web777** [comment]
Devtools downloaded as zip 02.12.2015

**Comment by sergeyklay** [comment]
2.0.9 ?
https://github.com/phalcon/phalcon-devtools/archive/v2.0.9.zip

**Comment by mzf** [comment]
Yes. I used this too.

**Comment by Hodes** [comment]
I have changed devtools to be able to find custom classes, refers to #641. Here's in my repo https://github.com/hodes/phalcon-devtools/tree/2.1.x.

**Comment by alexbusu** [comment]
@mzf Have you tried to use fully qualified name for your base class? Something like `--extends=\\Base`.

**Comment by sergeyklay** [comment]
It is not an bug. Devtools trying to create an instance of a class using reflection. This is necessary in order to re-generate the class and return back all comments, custom methods etc. But it can't create the object because Class `Core\Models\Base` not found.

**Comment by alexbusu** [comment]
I think the problem here is that the namespace Core\Models is not registered in loader, so maybe we could improve the model generator by automatically register user namespace, if any, or to register user dir otherwise.
@sergeyklay, what do you think?

**Comment by sergeyklay** [comment]
Of course. Mb we need add support of cusom loader here: https://github.com/phalcon/phalcon-devtools/blob/3.0.x/bootstrap/autoload.php#L117

**Comment by Hodes** [comment]
So, if the 3.0.x will have the auto-load behavior, the code I have created for previous versions ( #641) are not needed anymore. It still in 3.0.x, see https://github.com/phalcon/phalcon-devtools/blob/3.0.x/scripts/Phalcon/Builder/Model.php#L184, that three lines will have no sense, what do you think ?
