### ISSUE TITLE
Migration rollback doesn't work properly

### ISSUE THREAD

**Issue by raymercb** [phalcon/phalcon-devtools#584]
I have a MySQL database with some data, in a production environment. My first migration is: 
```
class SampleMigration_101 extends Migration {
    public function up() {
        self::$_connection->execute("ALTER TABLE `phalcon`.`sample` DROP INDEX `login`;");
    }
    public function down() {
        self::$_connection->execute("ALTER TABLE `phalcon`.`sample` ADD INDEX `login` (`login`)");
    }
}
```
Then, I create another migration for the same table with something like this:
```
class SampleMigration_102 extends Migration {
    public function up() {
        self::$_connection->execute("ALTER TABLE `phalcon`.`sample` ADD INDEX `login` (`login`)");
    }
    public function down() {
        self::$_connection->execute("ALTER TABLE `phalcon`.`sample` DROP INDEX `login`;");
    }
}
```
But if I want to rollback to 101 (>phalcon migration run --version=1.0.1), I lose my sample table. 

Why do I need to always call a morph function?,
Why is the table deleted if I don't have a morph function? 
Why does each migration need to have a lot of information?

Thanks in advance!

**Comment by sergeyklay** [comment]
@raymercb Can you please check `2.0.x` branch?

**Comment by sergeyklay** [comment]
see #584
