### ISSUE TITLE
Migration generate FULLTEXT index error

### ISSUE THREAD

**Issue by tobispace** [phalcon/phalcon-devtools#585]
Using Phalcon Devtools 2.0.7 with MySql adapter. MySql Server version: 5.7.9.

I have a table with this definition:

```
+-----------------+------------------+------+----------+---------+----------------+
| Field           | Type             | Null | Key      | Default | Extra          |
+-----------------+------------------+------+----------+---------+----------------+
| search_index_id | int(10) unsigned | NO   | PRI      | NULL    | auto_increment |
| origin_table    | varchar(255)     | NO   | MUL      | NULL    |                |
| origin_id       | int(11)          | NO   | MUL      | NULL    |                |
| search_text     | text             | NO   | FULLTEXT | NULL    |                |
+-----------------+------------------+------+----------+---------+----------------+
```

search_text has a FULLTEXT index.

Running:

> phalcon migration generate --config='.phalcon/config.ini' --migrations='migrations'

generates this migration Class:

``` php
/* ... */

new Column(
    'search_text',
    array(
        'type' => Column::TYPE_TEXT,
        'notNull' => true,
        'size' => 1,
        'after' => 'origin_id'
    )
)

/* ... */

'indexes' => array(
    new Index('PRIMARY', array('search_index_id'), null),
    new Index('origin_id', array('origin_id'), null),
    new Index('origin_table', array('origin_table'), null),
    new Index('search_text', array('search_text'), null)
),

/* ... */
```

The Index for search_text must be a `'FULLTEXT'` type index, not a default one (the code says `null` as the third parameter of `new Index()`).
This causes an error when running the migration on other working copies:

> BLOB/TEXT column 'search_text' used in key specification without a key length

I fixed this by altering the migration Class definition replacing `null` with `'FULLTEXT'`, but actually this is definitely a bug.

**Comment by mattvb91** [comment]
The 3 other indexes having null too is also incorrect im assuming?

**Comment by tobispace** [comment]
Actually it's correct, because running the migrations on a new db the indexes are correctly created. Maybe "null" indicates the default MySql "Index" type.

**Comment by mattvb91** [comment]
Ok, this might actually be an issue coming from cPhalcon as thats where it returns the getType() from for the index. Will do a bit of digging.

**Comment by mattvb91** [comment]
Think I found it. Looks like a wrong value is being referenced within cPhalcon. Will do some testing and add pull request if it is that.

**Comment by tobispace** [comment]
Thank you vero much!

**Comment by mattvb91** [comment]
PR is open and tests are passing:
https://github.com/phalcon/cphalcon/pull/11265

By the way is there a reason your using 2.0.7 devtools?

**Comment by tobispace** [comment]
No one actually. I first tried with a 2.0.7 installation in a test VM with an older version but then I found out the same problem surfaced even with the newest one (2.0.9). Thank you again very much.

**Comment by sergeysviridenko** [comment]
It works fine for me. I created table
```
CREATE TABLE `issue585` (
  `search_index_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `origin_table` varchar(255) NOT NULL,
  `origin_id` int(11) NOT NULL,
  `search_text` text NOT NULL,
  PRIMARY KEY (`search_index_id`),
  FULLTEXT KEY `search_text` (`search_text`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```
I've had in migration file
```
'indexes' => [
     new Index('PRIMARY', ['search_index_id'], 'PRIMARY'),
     new Index('search_text', ['search_text'], 'FULLTEXT')
],
```

Phalcon DevTools Version: 3.2.3
Phalcon Version: 3.2.1

**Comment by sergeyklay** [comment]
Closing, this is implemented/fixed. If there are bugs, we can follow up in separate issues.
