### ISSUE TITLE
Migration generate VARCHAR column types in place of DATE ones

### ISSUE THREAD

**Issue by tobispace** [phalcon/phalcon-devtools#586]
Using Phalcon Devtools 2.0.7 with MySql adapter. MySql Server version: 5.7.9.

The problem impacts on all **TIMESTAMP**, **DATE** and **DATETIME** columns.

Running:

> phalcon migration generate --config='.phalcon/config.ini' --migrations='migrations'

Generates this code:

```php
/* ... */

new Column(
	'date_updated',
	array(
		'type' => Column::TYPE_VARCHAR,
		'size' => 1,
		'after' => 'user_id_updated'
	)
),

/* ... */
```

The correct type should **not** be `Column::TYPE_VARCHAR`. It should be `Column::TYPE_TIMESTAMP`, `Column::TYPE_DATE` or `Column::TYPE_DATETIME`.

How can I fix this?

**Comment by le51** [comment]
try to update phalcon to its newer version (2.0.9)

**Comment by tobispace** [comment]
2.0.9 fixed the issue.
