### ISSUE TITLE
Migration generate INT column type instead POINT

### ISSUE THREAD

**Issue by vip9** [phalcon/phalcon-devtools#588]
When running migration generate on MySQL database, tool generates Column::TYPE_INTEGER type instead of spatial "Point".

**Comment by sergeyklay** [comment]
Supported types https://github.com/phalcon/cphalcon/blob/master/phalcon/db/column.zep#L53-L173

**Comment by vip9** [comment]
Shouldn't phalcon return TYPE_UNKNOWN for not supported fields then?

**Comment by sergeyklay** [comment]
In any case this is Phalcon issue not Devtools.
