### ISSUE TITLE
[NFR]Annotations doc

### ISSUE THREAD

**Issue by Jurigag** [phalcon/phalcon-devtools#590]
Well. How about adding IDE stubs with ```@Annotation``` docs to support Php Annotation plugin for PHPStorm ?

Any idea where to put it ? IDE Stubs are generated from code/zephir ? So where i should put it if i want to do PR ?

**Comment by sergeyklay** [comment]
https://github.com/phalcon/phalcon-devtools/issues/430

**Comment by sergeyklay** [comment]
http://phalcontip.com/discussion/56/how-to-rename-all-generated-by-zephir-zepphp-stubs-to-php

**Comment by Jurigag** [comment]
So just add final(or abstract, can it be both) classes to phalcon ? Which namespace ?

**Comment by sergeyklay** [comment]
https://github.com/phalcon/zephir/issues/304

**Comment by Jurigag** [comment]
What about this ? Or maybe Phalcon\Config\Annotations ?

**Comment by sergeyklay** [comment]
I don't understand what you have in mind and what you're asking me
