### ISSUE TITLE
Migrations: add tables to migrate only those with a certain prefix.

### ISSUE THREAD

**Issue by oscarmolinadev** [phalcon/phalcon-devtools#595]
If is possible, add that you can choose tables with a certain prefix.

Thanks!

**Comment by wmathes** [comment]
How about adding wildcard support? 

`phalcon migration generate --table=users*`

**Comment by sergeysviridenko** [comment]
I propose close this issue.

**Comment by sergeyklay** [comment]
The wildcard support has been introduced in v3.2.6
