### ISSUE TITLE
Service 'Module' wasn't found in the dependency injection container - windows 7 - 64bit

### ISSUE THREAD

**Issue by joeltejdeep** [phalcon/phalcon-devtools#597]
In my Windows 7, I'm facing the issue, after adding a new module from devtool.
Phalcon version 2.0.9 (latest). please help.

Steps I done:
- I created project name as "test_project", type=module using devtool
- Then I created a new module called "Admin", using devtool
- I created IndexController and view in the Admin module 
- When I tried to run admin module, I'm getting the error
```
Service 'Test_project\Admin\Module' wasn't found in the dependency injection container
#0 [internal function]: Phalcon\Di->get('Test_project\\Admin\\...')
#1 D:\wamp\www\test_project\public\index.php(36): Phalcon\Mvc\Application->handle()
#2 {main}
```

**Comment by sergeyklay** [comment]
@joeltejdeep Did you register `Admin` module?

```php
    $application = new \Phalcon\Mvc\Application($di);

    $application->registerModules([
        'admin', [
            'className' => 'Test_project\Admin',
            'path'      => $config->application->modulesDir . 'Admin',
        ]
    ]);

    echo $application->handle()->getContent();
```

Could you please provide a small script to reproduce?
