### ISSUE TITLE
Model generated from dev tools puts wrong setSource

### ISSUE THREAD

**Issue by davidgrenier** [phalcon/phalcon-devtools#598]
Hello,

When generating a model from the phalcon dev tools 2.0.9, it defines both getSource():

```php
    public function getSource()
    {
        return 'Accounts';
    }
```

And setSource in initialize:

```php
    public function initialize()
    {
        $this->setSource("'Accounts'");
    }
```

Notice how Accounts in setSource is surrounded by single quote.

It eventually generates the following query:

```sql
SELECT IF(COUNT(*) > 0, 1, 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME` = ''accounts'' AND `TABLE_SCHEMA` = DATABASE()
```

Where you can see that the table name is surrounded by single quotes as well. Now I tested this after removing what I believe was a redundant getSource and not with it so I don't know if it would behave correctly with getSource.

David

**Comment by sergeyklay** [comment]
@davidgrenier Can you please test now Devtools `2.0.x` branch?

**Comment by davidgrenier** [comment]
Not sure I got this right... what I did is modify my composer.json for phalcon dev tools to the following:

```php
{
    "require": {
        "phalcon/devtools": "2.0.x"
    }
}
```

Instead of dev-master.

Composer update seems to have updated to the same version 2.0.9.

Generating the model gave me the same result.

Probably doing this wrong?

**Comment by sergeyklay** [comment]
```json
{
    "require": {
        "phalcon/devtools": "dev-master"
    }
}
```

**Comment by davidgrenier** [comment]
Yeah that's pulling the following commit: https://github.com/phalcon/phalcon-devtools/commit/64cef4a849a19a479174abf05d3d833e3dd1884d

Which is on dev-master branch, while your commit is on 2.0.x branch.

**Comment by sergeyklay** [comment]
I just used `composer require phalcon/devtools:dev-master` and received Devtools with these changes #599

**Comment by sergeyklay** [comment]
Try please with these changes https://github.com/phalcon/phalcon-devtools/commit/6a093921e572f9bf25b65a25d72f5330cc5706ac

**Comment by davidgrenier** [comment]
Yes it worked... really helps.

Should I stick to that branch or is this kind of changes quickly merged to the master branch?

**Comment by sergeyklay** [comment]
I think during the week. Maybe even earlier.
Well issue may be closed?

**Comment by davidgrenier** [comment]
Of course, much appreciated.
