### ISSUE TITLE
Migrations - INT instead of SMALLINT

### ISSUE THREAD

**Issue by Zaszczyk** [phalcon/phalcon-devtools#603]
I have a little problem with columns different than INT, for example with SMALLINT. I have column table.activity_type_id SMALLINT(6), which references in foreign key and migration creates SQL with INT(6):

```
CREATE TABLE `table` (
  `id`               INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `activity_type_id` INT(6),
   ...
  KEY `table_foreign_key` (`activity_type_id`),
  CONSTRAINT `table_foreign_key` FOREIGN KEY (`activity_type_id`) REFERENCES `activity_type` (`id`)
)
```
But column activity_type.id is SMALLINT(6) and at this situation I got error:
errno: 150 "Foreign key constraint is incorrectly formed"
because of column types are different: SMALLINT(6) VS INT(6).

I know, that column types arrive from Phalcon, but maybe it is possible to fix?

**Comment by sergeyklay** [comment]
Phalcon does nor support SMALLINT. See https://github.com/phalcon/cphalcon/blob/master/phalcon/db/column.zep#L52-L139

In any case this is not Devtools issue.
