### ISSUE TITLE
Need phalcon 2.1 stubs

### ISSUE THREAD

**Issue by mzf** [phalcon/phalcon-devtools#604]
Need phalcon 2.1 stubs

**Comment by sergeyklay** [comment]
After release 2.1

**Comment by mzf** [comment]
@sergeyklay Сергей, а что делать тем, кто уже разрабатывает на 2.1? Может не разрабатывать, а ждать релиза тоже?

**Comment by sergeyklay** [comment]
```
$ git clone git@github.com:phalcon/cphalcon.git
$ git checkout 2.1.x
$ zephir stubs
$ cd ide/2.1.0
$ find . -type f -name "*.zep.php" | sed -e 'p' -E -e "s/.zep.php/.php/g" | xargs -n2 mv
```

2.1 is quite stable. But of course, before the release it will be further amended. We already use 2.1 for internal Phalcon sites
