### ISSUE TITLE
Inconsistent Template File Generation

### ISSUE THREAD

**Issue by netblue** [phalcon/phalcon-devtools#61]
Create project creates a skeleton based on volt templates.  
The config/services.php is setup to load the volt engine.
The main view is index.volt

Running the scaffold command generates .phtml files and not .volt files.  Thus, the layouts don't really work unless manually converting all the files to .volt templates, or disabling the volt engine and converting the main layout to a .phtml file.

A user should probably have the option to generate .volt or .phtml in commands that generate template files.

**Comment by rianorie** [comment]
lets have create project add a file to `.phalcon` with the template engine in it. Then scaffold can read this

**Comment by sergeysviridenko** [comment]
It works in latest stable version. I suggest close this issue.
