### ISSUE TITLE
phalcon migrate run General error 1347

### ISSUE THREAD

**Issue by Michal-St** [phalcon/phalcon-devtools#625]
Hi evryone,

I'm using MySql Db and I have some views, Using devtools I generate migrations and evrythink looks fine. The problem is when I woudlike run this migration. 

```
ALTER TABLE `**********` MODIFY `added_date` DATEERROR: SQLSTATE[HY000]:
General error: 1347 '***********' is not BASE TABLE
```

all views is i normal php file but it's different config 

```php
             'options' => array(
                    'TABLE_TYPE' => 'VIEW',
                    'AUTO_INCREMENT' => '',
                    'ENGINE' => '',
                    'TABLE_COLLATION' => ''
                ),
```

It's possible to generate migration without views?

**Comment by Michal-St** [comment]
after migration genarating I call

`find assets/migrations -type f -exec egrep -Il "'TABLE_TYPE' => 'VIEW'," {} \;|xargs rm -fv`

and migration-run work fine

**Comment by sergeyklay** [comment]
@Michal-St Coul you please provide a small script to reproduce? E.g. table schema, view schema, migration class
