### ISSUE TITLE
IDE support - tag or branches for "phalcon-devtools/ide/"

### ISSUE THREAD

**Issue by KASTINpl** [phalcon/phalcon-devtools#632]
Hey
Now all directories from https://github.com/phalcon/phalcon-devtools/tree/master/ide have the same tag and branch, so when we include 
`"phalcon/devtools": "2.0.0",` into our composer, then IDE will load all versions of phpdoc, from 0.4.0 to 2.0. What about create tag for each version-directory? Or create new branch for each dir to include only one selected phpdoc version?

**Comment by sergeyklay** [comment]
See #398
