### ISSUE TITLE
[2.1.x] Scaffolds should produce code using short array format

### ISSUE THREAD

**Issue by dschissler** [phalcon/phalcon-devtools#644]
Phalcon 2.1 will be dropping PHP 5.3 so the scaffolds should produce code using the new shorthand array format.

**Comment by dschissler** [comment]
So you would take pull requests for this?  It sounds like easy enough mindless work at the end of a long day.

**Comment by sergeyklay** [comment]
Okay

**Comment by sergeyklay** [comment]
Fixed

**Comment by dschissler** [comment]
@sergeyklay I just realized that Phalcon 2.1 is only deprecating PHP 5.3.  Is this still the case?  Just giving a heads up that this change may need to be reverted.  I think though that you guys should consider just dropping the ancient PHP 5.3 though even if you were considering to not do that.

**Comment by sergeyklay** [comment]
Devtools 2.1.x requires PHP >= 5.4
I've fixed issue in 2.1.x branch

**Comment by dschissler** [comment]
Ok so Phalcon 2.1 supports >= 5.3 and Dev Tools >= 5.4 ??

**Comment by sergeyklay** [comment]
Phalcon 2.1 does not support PHP 5.3

**Comment by dschissler** [comment]
Ok well lookup "Deprecation for PHP 5.3" on https://blog.phalconphp.com/.
Perhaps this will be evident enough on release but there is Phalcon Team
published updates out there that are contradictory to this.  I think that
it should be clarified.  Also +1 on removing 5.3.

**Comment by sergeyklay** [comment]
Yeah. But this is not Devtools issue
