### ISSUE TITLE
[2.1.x] Installation by composer error

### ISSUE THREAD

**Issue by fantua** [phalcon/phalcon-devtools#645]
Problem 1
    - Installation request for phalcon/devtools 2.1.x-dev -> satisfiable by phalcon/devtools[2.1.x-dev].
    - phalcon/devtools 2.1.x-dev requires ext-phalcon ~2.1 -> the requested PHP extension phalcon has the wrong version (2.1.0r) installed.

From master
Problem 1
    - Installation request for phalcon/devtools dev-master -> satisfiable by phalcon/devtools[dev-master].
    - phalcon/devtools dev-master requires ext-phalcon ~2.0 -> the requested PHP extension phalcon has the wrong version (2.1.0r) installed.

**Comment by sergeyklay** [comment]
Because Phalcon 2.1.0 is not release yet. Use `composer install --ignore-platform-reqs`

**Comment by fantua** [comment]
Thx.

How to use phalcon on OS X with phpstorm? After install by composer.

```
 phalcon
bash: phalcon: command not found
```

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests. For questions regarding the usage of the Phalcon Developer Tools or support requests please visit the [official forums](http://forum.phalconphp.com/).
