### ISSUE TITLE
Configured 'url' service doesn't take into account a deep directory

### ISSUE THREAD

**Issue by dschissler** [phalcon/phalcon-devtools#647]
So say that I have a setup on my localhost root that looks something like this:

```
phalcon_projects
  - project1
  - project2
  - project3
```

So that a index-index URL looks like this: `http://localhost:8000/phalcon_projects/project1`.   The problem with this is that the `url` service will return URL paths without "phalcon_projects" on it.

I'm familiar with the full blown domain vhost setup but in this case I just want to play with the dev-tools for simple tests of different technologies.  Is there a simple way that I can improve this or is there a way that the builtin `url` service can be changed to account for this?

**Comment by Jeckerson** [comment]
Closing for no interest for any another person during 3 years counting from now to current feature.
