### ISSUE TITLE
Composer Installation Problems

### ISSUE THREAD

**Issue by rochapablo** [phalcon/phalcon-devtools#654]
First I'm sorry but... always that I have to install Phalcon I get stuck in this kind of problem and right now I'm trying to understand what is the really problem.

So, I have configured the Phalcon and now I'm trying to run ```composer install + composer update``` and this is the error.

```
Problem 1
    - Installation request for phalcon/incubator >=2.0.10 -> satisfiable by phalcon/incubator[v2.0.10].
    - phalcon/incubator v2.0.10 requires ext-phalcon >=2.0.4 -> the requested PHP extension phalcon has the wrong version (2.1.0r) installed.
  Problem 2
    - Installation request for phalcon/devtools >=2.0.10 -> satisfiable by phalcon/devtools[v2.0.10].
    - phalcon/devtools v2.0.10 requires ext-phalcon ~2.0 -> the requested PHP extension phalcon has the wrong version (2.1.0r) installed.
```

Well I know that my extension is 2.1.0r and also I know that I want the last version of incubator and devtools which is v2.0.10. Am I right?

And if my composer file have this:

```
{
	"require": {
		"php": ">=5.5",
		"phalcon/incubator": ">=2.0.10",
		"phalcon/devtools": ">=2.0.10",
		"phpmailer/phpmailer": ">=5.2"
  	},
	"require-dev": {
		"phpunit/phpunit": "^4.8"
	}
}
```

Shouldn't this install without problems?

**Comment by sergeyklay** [comment]
You have to install Phalcon first. Or use `composer install --ignore-platform-req`

**Comment by rochapablo** [comment]
But I have Phalcon already installed =/

**Comment by sergeyklay** [comment]
could you please provide output from
```
php --ri phalcon
```

**Comment by rochapablo** [comment]
Yes, I'll try to provide that tonight.

**Comment by rochapablo** [comment]
Sorry for the delay, follow the output of ```php --ri phalcon```

```
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 2.1.0r
Build Date => Mar 23 2016 00:43:53
Powered by Zephir => Version 0.9.2a-dev

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
```

**Comment by sergeyklay** [comment]
For Phalcon 2.1.x you have to use Devtools 2.1.x

**Comment by shadyueh** [comment]
I'm with similar problem.
composer.json:
```
{
    "require": {
		"phalcon/devtools": ">=2.1.0"
    }
}
```

console output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package phalcon/devtools >=2.1.0 is satisfiable by phalcon/devtools[2.1.x-dev, dev-master] but these conflict with your requirements or minimum-stability.
```

php --ri phalcon exit:

```

phalcon


Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 2.1.0r
Build Date => Mar 23 2016 00:36:58
Powered by Zephir => Version 0.9.2a-dev

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
```
I already have apache, php, phalcon, etc installed. I just need phalcon dev at moment.

**Comment by sergeyklay** [comment]
> "phalcon/devtools": ">=2.1.0"

Devtools 2.1.0 is not release yet. You have to use `2.1.x-dev`

**Comment by sergeyklay** [comment]
@rochapablo 
> Version => 2.1.0r

Composer expect something like `2.1.0-RC1`, but Phalcon uses `2.1.0r`. This is why you have to use `--ignore-platform-req`.

See https://github.com/phalcon/cphalcon/issues/11783 and https://github.com/composer/composer/issues/5331

**Comment by charbelmhanna** [comment]
hello, 

my xamp show that falcon is enabled but when i use composer to install it show 

------
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phalcon/devtools v4.0.1 requires ext-phalcon ^4.0.0 -> the requested PHP extension phalcon is missing from your system.
    - phalcon/devtools v4.0.0 requires ext-phalcon ^4.0.0 -> the requested PHP extension phalcon is missing from your system.
    - Installation request for phalcon/devtools ^4.0 -> satisfiable by phalcon/devtools[v4.0.0, v4.0.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - C:\wamp64\bin\php\php7.3.5\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
-----

now when I run php --ri phalcon I get extension 'phalcon' not present 

-> I added in php.ini extension=php_phalcon |tried both| extension=php_phalcon.dll

I don't understand why it is so hard with this framework to work

**Comment by Jeckerson** [comment]
@charbelmhanna Probably you included `extension=phalcon.dll` in incorrect `.ini` file.

If you are in CLI env, use one of this:
* `php -i | grep php.ini`
* `php --ini`

and add it there the extension
