### ISSUE TITLE
Sqlite Migrations dbname appended on queries

### ISSUE THREAD

**Issue by Caffe1neAdd1ct** [phalcon/phalcon-devtools#665]
Trying to run db migrations:

```
php56 vendor/bin/phalcon.php migration run --migrations=app/migrations config=app/config/app.ini
```

Gives the following:
```sql
 CREATE TABLE "app.db"."users" (  `id` INTEGER NOT NULL,  `username` VARCHAR(1) NOT NULL,  `password` VARCHAR(1) NOT NULL,  `email` VARCHAR(1) NOT NULL,  `token` VARCHAR(1),  `valid` INTEGER DEFAULT "0" NOT NULL,  `created` VARCHAR(1) DEFAULT "0000-00-00 00:00:00" NOT NULL,  `deleted` VARCHAR(1) )
```
```
 ERROR: SQLSTATE[HY000]: General error: 1 unknown database "app.db"
```

Looks like the dbname from the app.ini is being put into the queries before the table... not right for sqlite?

app.ini:

```ini
[database]
adapter   = Sqlite
;host      = localhost
;username  = root
;password  =
dbname    = data/app.db
;metaCache = memory
;metaCacheOptions.lifetime = 86400
;metaCacheOptions.prefix = metaCache
;charset   = uft8

[url]
host    = localhost:8000
baseUri = /

[application]
controllersDir = /controllers/
modelsDir      = /models/
viewsDir       = /views/
pluginsDir     = /plugins/
formsDir       = /forms/
validatorsDir  = /validators/
libraryDir     = /library/
vendorDir      = /../vendor/
migrationsDir  = /migrations/
cacheDir       = /cache/

[mail]
server   = localhost
username = 
password = 
port     = 1025
security = none
from     = app@localhost
name     = App Name
```

**Comment by Caffe1neAdd1ct** [comment]
To update I've just tried generating the same table migration from MySQL, dropping the table and running the migration, works correctly as MySQL copes with the schema specification:

```
Phalcon DevTools (2.0.11)

1463042073.396: SELECT IF(COUNT(*) > 0, 1, 0) FROM `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_NAME`= 'users' AND `TABLE_SCHEMA` = 'test'  => 1463042073.4013 (0.0052869319915771)
1463042073.4017: CREATE TABLE `test`.`users` (  `id` INT(11) NOT NULL AUTO_INCREMENT,  `username` VARCHAR(45) NOT NULL,  `password` VARCHAR(45) NOT NULL,  `email` VARCHAR(45) NOT NULL,  `valid` VARCHAR(45) DEFAULT "0" NOT NULL,  `token` VARCHAR(45) NOT NULL,  `created` DATETIME DEFAULT "0000-00-00 00:00:00" NOT NULL,  `deleted` DATETIME,  PRIMARY KEY (`id`),  UNIQUE KEY `id_UNIQUE` (`id`),  UNIQUE KEY `username_UNIQUE` (`username`) ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci  => 1463042073.4196 (0.017881155014038)
                                                    
  Success: Version 1.0.0 was successfully migrated 
```

**Comment by sergeyklay** [comment]
Fixed in 2.0.x branch

**Comment by Caffe1neAdd1ct** [comment]
@sergeyklay thanks for the quick fix, I'll give the branch a test

**Comment by phackwer** [comment]
Guys, it's happening again on 3.0! Check the CREATE TABLE clause bellow.

Phalcon DevTools (3.0.1)

1479126612.436: DELETE FROM "pessoa"1479126612.4362: DELETE FROM "endereco"1479126612.4362: DELETE FROM "bairro"1479126612.4362: DELETE FROM "cidade"1479126612.4362: DELETE FROM "estado"1479126612.4363: DELETE FROM "genero_filme"1479126612.4363: SELECT CASE WHEN COUNT(*) > 0 THEN 1 ELSE 0 END FROM sqlite_master WHERE type='table' AND tbl_name='pessoa'  => 1479126612.4364 (5.1021575927734E-5)
1479126612.4364: CREATE TABLE "/home/phackwer/Projects/sample-phalcony/db.sqlite"."pessoa" (  `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,  `nome` VARCHAR(255) NOT NULL,  `cpf` VARCHAR(11) NOT NULL,  `rg` VARCHAR(50),  `telefone` VARCHAR(11),  `dataNascimento` DATE,  `descricao` VARCHAR(500),  `curriculo` TEXT,  `peso` FLOAT,  `sexo` VARCHAR(1) )                                                                                                                 
  Error: SQLSTATE[HY000]: General error: 1 unknown database "/home/phackwer/Projects/sample-phalcony/db.sqlite"

**Comment by Caffe1neAdd1ct** [comment]
I've been using `"phalcon/devtools": "dev-master",` and the migrations are working ok, can you try with master?

**Comment by phackwer** [comment]
That's the one I'm using. Did you tried SQLite?

**Comment by phackwer** [comment]
Wil try it now. I thought I was using it. Just saw that actually I'm using version 2.0.1.

**Comment by Caffe1neAdd1ct** [comment]
Ah try dev-master, i'm currently using `58e6b6582b8ae351e57078efe1182b85e99f0802` looking in composer.lock.
