### ISSUE TITLE
[2.1] Migration run without version file causes error

### ISSUE THREAD

**Issue by staticall** [phalcon/phalcon-devtools#673]
Good day!

I updated Phalcon to v2.1 (dev) and when tried to run migrations (version file does not exists, empty database), it throws following error:

> $ vendor/bin/phalcon.php migration run
> 
> Phalcon DevTools (2.1.0 RC 1)
> 
> Warning: file(<project>/.phalcon/migration-version): failed to open stream: No such file or directory in <project>/vendor/phalcon/devtools/scripts/Phalcon/Migrations.php on line 524
> 
> Warning: array_flip() expects parameter 1 to be array, boolean given in <project>/vendor/phalcon/devtools/scripts/Phalcon/Migrations.php on line 527
> 
> Error: Migration class cannot be found OrganizationMigration_1000000000 at <project>/apps/migrations/1.0.0/organization.php

I'm using Windows, so permissions should not be an issue here, folder "<project>/.phalcon/" already exists. Should i create this file manually before running migrations?
Also, result migration class name seems to be extra long, not sure if it's my setup or new class format, right now, my migration classes look like this: OrganizationMigration_100

Thanks in advance!

**Comment by sergeysviridenko** [comment]
@staticall could you try to use latest version?

**Comment by sergeyklay** [comment]
I'm think it works in latest stable release. If there are bugs, we can follow up in separate issues.
