### ISSUE TITLE
Standalone model generation (feature request)

### ISSUE THREAD

**Issue by Paradoxis** [phalcon/phalcon-devtools#680]
Could it be made possible to generate models without having to be inside a project by passing the database credentials through the command line? This is due to the fact that my project doesn't use the default `/app/config/config.php` file to load configurations, which made it impossible for me to use the devtools.

Example of how this could be used:

```
phalcon model Products --driver=mysql --username=root --password=mysecretpassword
```

**Comment by alexbusu** [comment]
Hi @Paradoxis 
It's not a good practice to use passwords in command line. Maybe a `--dbConfig=path/to/dbconfig` option would be better. What do you think?

**Comment by sergeysviridenko** [comment]
@Paradoxis actually you can use  `--directory=s` option if you aren't inside project. @alexbusu is right - good practice would be added `--config=s` option for `phalcon model` command
