### ISSUE TITLE
[2.1] DevTools $e->getTrace line in the cli.php bootstrap file causes PHP Notice

### ISSUE THREAD

**Issue by dschissler** [phalcon/phalcon-devtools#683]
https://github.com/phalcon/phalcon-devtools/blob/05b343a6df930c89ba9cb6f9cbcdb40cfe74b294/templates/project/cli/cli.php#L64

I get a lot of this: `PHP Notice:  Array to string conversion in ...`.

Done with Phalcon 2.1 and Dev Tools 2.1 snapshot.

**Comment by sergeyklay** [comment]
This should be getTraceAsString

**Comment by sergeyklay** [comment]
Could you please provide these notices? 
@dschissler

**Comment by sergeyklay** [comment]
Fixed in `2.1.x` branch
