### ISSUE TITLE
Model Validation needs to be updated

### ISSUE THREAD

**Issue by jakzodiac** [phalcon/phalcon-devtools#688]
Model Validation is still using the old validation classes and needs to be updated to use Phalcon\Validation and it's Validator classes.

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.

**Comment by jhaoheng** [comment]
hello @sergeyklay 
So i need to pull from 3.0.x or master????

**Comment by jhaoheng** [comment]
phalcon dev-tools : 3.0.1 -> 3.0.2(branch 3.0.x)

when i use `phalcon model {my_tableName} --force`
and model re-generated
but this model lost `use Phalcon\Validation;`
i am not sure whether it is an issue.

**Comment by sergeyklay** [comment]
@jhaoheng Could you please try `3.0.x` branch?
