### ISSUE TITLE
Column collation is not migrated

### ISSUE THREAD

**Issue by udarkness** [phalcon/phalcon-devtools#689]
in mysql, we can specify a collation for a column.
Example:
```sql
ALTER TABLE `languageint`.`lang` 
CHANGE COLUMN `id` `id` VARCHAR(7) CHARACTER SET 'ascii' NOT NULL ;
```

After migrate and run the migration in other machine, I got utf8 (table collation)
Migration file:
```php
// ...
new Column(
    'lang',
    [
        'type' => Column::TYPE_VARCHAR,
        'default' => "en",
        'notNull' => true,
        'size' => 7,
        'after' => 'domain'
    ]
),
// ...
'options' => [
    'TABLE_TYPE' => 'BASE TABLE',
    'AUTO_INCREMENT' => '1973',
    'ENGINE' => 'InnoDB',
    'TABLE_COLLATION' => 'utf8_unicode_ci'
],
// ...
```

**Comment by sergeyklay** [comment]
@udarkness

This is mostly [Phalcon](https://github.com/phalcon/cphalcon) issue. Devtools uses [`Phalcon\Db\Column`](https://github.com/phalcon/cphalcon/blob/master/phalcon/db/column.zep) class which currently does not support custom collation. 

You have to open a new feature request in the [Phalcon repository](https://github.com/phalcon/cphalcon).
