### ISSUE TITLE
Migration doesn't support custom adapters

### ISSUE THREAD

**Issue by phackwer** [phalcon/phalcon-devtools#694]
The code at Mvc\Model\Migration.php line 91, doesn't allow us to create custom adapters. It assumes only the Phalcon\Db\Adapters should be used. Changing it to 

```
    if (!class_exists($database->adapter)) {
        $adapter = '\\Phalcon\\Db\\Adapter\\Pdo\\' . $database->adapter;
    } else {
        $adapter = $database->adapter;
    }

    if (!class_exists($adapter)) {
        throw new DbException('Invalid database Adapter!');
    }
```

Will allow people to write custom adapters outside de Phalcon namespace. This change is kind of important for us, right now.

**Comment by sergeyklay** [comment]
@phackwer What exactly do you suggest? To look at `adapterClass` config parameter? We need Fully Qualified Class Name  here

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
