### ISSUE TITLE
[2.1] Command "phalcon model" dont work with last phalcon dll

### ISSUE THREAD

**Issue by mzf** [phalcon/phalcon-devtools#697]
I update my phalcon to last dll from site
```
Phalcon 2.1.0.RC1 - Windows x64 for PHP 5.5.0 NTS (vc11)
June 07 2016 08:40:52 EDT / sha1: 78f1cad62275c28d1673e65d9072de13d9a85b45
```

When i running command
```
phalcon model server --output=app\modules\servers\models\Generated --force --get-set
```
i get nothing. 
I see only title - Phalcon DevTools (2.1.0 RC 1)
And then no error messages, no any messages. 
It looks as the hanged process

**Comment by sergeyklay** [comment]
@mzf Have you tried Devtools from 2.1.x branch?

**Comment by mzf** [comment]
Yes, i use 2.1.dev
my composer source
```
{
    "require": {
        "phalcon/devtools": "^2.1"
    },
	"minimum-stability": "dev"
} 
```

**Comment by emiliodeg** [comment]
I have the same problem.
Create project works ok but then when I try to make models or any other actions didn't happend

**Comment by sergeyklay** [comment]
@mzf @emiliodeg Could you please try `3.0.x` branch?

**Comment by mzf** [comment]
3.0.0 all ok
