### ISSUE TITLE
Yaml config extension

### ISSUE THREAD

**Issue by sotebuy** [phalcon/phalcon-devtools#702]
Can we agree to use .yaml and .yml extensions. I know that yaml recommends the .yaml extension still for me the .yml extension is more handy and faster to write.
https://github.com/phalcon/phalcon-devtools/blob/2.1.x/scripts/Phalcon/Commands/Command.php#L135

**Comment by sergeyklay** [comment]
@sotebuy Could you lease send PR?

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
