### ISSUE TITLE
DOUBLE columns can not be migrated.

### ISSUE THREAD

**Issue by miyabi** [phalcon/phalcon-devtools#704]
I generated a migration like below:
```
$ phalcon migration generate
...
Success: Version 1.0.0 was successfully generated
```
and then just run it and I got an error:
```
$ phalcon migration run
...
1467618991.0166: ALTER TABLE `prefecture` MODIFY `lat` DOUBLE(1) NOT NULL AFTER `name`ERROR:
SQLSTATE[42000]: Syntax error or access violation: 1064
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server
version for the right syntax to use near ') NOT NULL AFTER `name`' at line 1
```

Phalcon DevTools v2.0.13
Phalcon v2.0.13
PHP 5.5.9-1ubuntu4.17
mysql  Ver 14.14 Distrib 5.5.49
Ubuntu 14.04.4 LTS x86_64

**Comment by sergeyklay** [comment]
You have to use
```sql
DOUBLE (M,D)
```

```php
new Column(
    'lat',
    [
        'type'  => Column::TYPE_DOUBLE,
        'size'  => 1,
        'scale' => 1,
        'after' => 'name'
    ]
),
```

Also note for `float(M,D)`, `double(M,D)` or `decimal(M,D)`, `M` must be >= `D`.

**Comment by valorize** [comment]
I'm quite confused why this is not a bug in devtools??? If I run `migration generate` I would assume that the script itself created the `DOUBLE` or `DOUBLE(M, D)` for me.
