### ISSUE TITLE
Intellij IDEA says the Phalcon\Mvc\Model is an abstract class and I should implement some methods

### ISSUE THREAD

**Issue by balthild** [phalcon/phalcon-devtools#709]
Models classes extends the Phalcon\Mvc\Model according the documenation. I think it's right since the program runs normally, but errors the IDE shows is annoying.

![qq20160715-0](https://cloud.githubusercontent.com/assets/2662758/16843674/cd6791d4-4a14-11e6-9707-fb4e9ec34fe0.png)

**Comment by sergeyklay** [comment]
This is IDE issue
