### ISSUE TITLE
 Warning: Cannot bind an instance to a static closure in 

### ISSUE THREAD

**Issue by isstack** [phalcon/phalcon-devtools#717]
Always error： Warning: Cannot bind an instance to a static closure in 
I use phalcon-devtoole 3.0.x, Version 2.0 phalcon also have this problem.
phalcon version 3.0phalcon version 3.0

**Comment by andresgutierrez** [comment]
Phalcon now binds DI to closures used as service definition, however if the closure was created in a static context PHP raises that warning, that only happens in PHP5, it seems that in PHP7 that warning was disabled or removed. 

https://github.com/phalcon/cphalcon/issues/11029#issuecomment-200612702

**Comment by acv-anhlx** [comment]
Hi @andresgutierrez ,
I use Phalcon 3 and PHP 5.6.21. 
I create project test --enable-webtools, i visit webtools page and see 2 errors : 
1. Warning: Cannot bind an instance to a static closure in C:\phalcon-devtools\scripts\Phalcon\Web\Tools.php on line 356
2. Warning: Cannot bind an instance to a static closure in C:\phalcon-devtools\scripts\Phalcon\Web\Tools\views\index.phtml on line 15
Please help me :( I dont know why

**Comment by GBraL** [comment]
Using Phalcon 3 and PHP 5.6 I can't remove this message?

**Comment by Dave3o3** [comment]
Same here with PHP 5.6.25... switching to PHP 7 eliminates this issue.

**Comment by sergeyklay** [comment]
Will be fixed soon

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.

**Note:** You have disable and enable WebTools again

**Comment by temuri416** [comment]
@sergeyklay any chance linking the commit that fixed it?

Thanks!

**Comment by sergeyklay** [comment]
https://github.com/phalcon/phalcon-devtools/commit/a420929214d8b89befaeb9efedf34d9528529aa1
