### ISSUE TITLE
phalcon-devtools/scripts/Phalcon/Web/JQuery.php not updated for new jquery version

### ISSUE THREAD

**Issue by silverdr** [phalcon/phalcon-devtools#728]
You seem to have forgotten to update things there. Hardcoding specific files there doesn't seem like a good idea anyway.

**Comment by sergeyklay** [comment]
@dschissler Could you please take a look?

**Comment by dschissler** [comment]
@silverdr Try the 3.0.x branch.

**Comment by silverdr** [comment]
@dschissler The 3.0.x branch fixes the version numbers but still refers to 'min' file, which is not provided in the resources.

**Comment by silverdr** [comment]
Here the fix should be to replace the static jquery file with a minimised variant in the resources.

**Comment by sergeyklay** [comment]
@silverdr Could you please try 3.0.x now?

**Comment by silverdr** [comment]
The basic functionality seem to work in the 3.0.x branch now. At least I don't see any critical issues like missing CSSs or JSs anymore. Still - in the longer run it would IMHO be better to remove the hardcoded filenames completely and just copy over whatever is present in the respective resources directories. That way resources updates will become far less error prone.

**Comment by dschissler** [comment]
We need to remove the hard coded names and also to not use both local and remote resources for different parts of the tools.  Its just double the maintenance.

**Comment by dschissler** [comment]
So close issue?

**Comment by silverdr** [comment]
> We need to remove the hard coded names and also to not use both local and remote resources for different parts of the tools. Its just double the maintenance.

Precisely, noticed that too. Closing then.
