### ISSUE TITLE
phalcon migration run can't run twice

### ISSUE THREAD

**Issue by jhaoheng** [phalcon/phalcon-devtools#731]
- phalcon 3.0.0

I generate my db by `phalcon migration generate`
and it is build v1.0.0

and then when i run first `phalcon migration run`
it work

but when i do this cmd twice, it no response
![2016-08-05 5 54 11](https://cloud.githubusercontent.com/assets/1822475/17433169/a9ec378c-5b35-11e6-899d-9e7289eb51a5.png)

and i must to delete `rm .phalcon/migration-version`
then the cmd work
![2016-08-05 5 53 24](https://cloud.githubusercontent.com/assets/1822475/17433144/8c79ba94-5b35-11e6-91f7-ffc89785e86b.png)

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
