### ISSUE TITLE
Composer phalcon devtools 3.0 with phalcon 3.0 minimun stability

### ISSUE THREAD

**Issue by Surt** [phalcon/phalcon-devtools#732]
The requested package phalcon/devtools (locked at v2.0.8, required as ~3.0) is satisfiable by phalcon/devtools[v2.0.8] but these conflict with your requirements or minimum-stability.

**Comment by sergeyklay** [comment]
Could you please provide your composer.json

**Comment by Surt** [comment]
It was during a composer require with other library. I did a ```composer update``` before installing the new one and devtools was sucessfully updated. Sorry, and thank you!
