### ISSUE TITLE
DB cloumn 'Allow Null' & 'Default' was changed when migration

### ISSUE THREAD

**Issue by jhaoheng** [phalcon/phalcon-devtools#734]
When i use `phalcon migration run`
and my column[time] attributes was changed by migration.

[before]
Type : timestamp
Allow Null : YES
Default : null

[after]
Type : timestamp
Allow Null : NO
Default : 0000-00-00 00:00:00

**Comment by therosco** [comment]
Same problem

**Comment by sergeyklay** [comment]
@jhaoheng @therosco Could you please provide migration script, DB version and table schema?
