### ISSUE TITLE
master branch is broken

### ISSUE THREAD

**Issue by free6k** [phalcon/phalcon-devtools#736]
Guys, I certainly understand that it is open source ... But a master branch is broken. Migrations do not work more than 5 days.

It is normal?

**Comment by chilimatic** [comment]
could you reference the issue ? or you just want to point out that you're unsatisfied ?

**Comment by sergeyklay** [comment]
@free6k Could you please try `3.0.x` branch?

**Comment by free6k** [comment]
I sent pull request to https://github.com/phalcon/phalcon-devtools/pull/720 in 3.0.x

**Comment by sergeyklay** [comment]
Well, now is all ok?
