### ISSUE TITLE
Initial Migration Timestamp Based problem

### ISSUE THREAD

**Issue by dcosta-ptc** [phalcon/phalcon-devtools#750]
Hi,

If we create a timestamp based migrations and we try to run the first one, exemple:

```
./phalcon migration run --log-in-db --ts-based
```

We get this error:
```
ERROR: Wrong version number provided
```

Because since there is nothing on database on getCurrentVersion it tries to create a `VersionCollection::createItem(null);` this uses default value `000` that does not match the expected regex.

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
