### ISSUE TITLE
PTOOLSPATH be a unexpected value in some cases.

### ISSUE THREAD

**Issue by yiivon** [phalcon/phalcon-devtools#753]
![image](https://cloud.githubusercontent.com/assets/1287165/17618735/f524bd9a-60b3-11e6-83d8-d03f3dd21250.png)

Windows 10 x64, cmd run at Administrator privilege, environment key PTOOLSPATH's value return a unexpected value, just like above.

**Comment by yiivon** [comment]
This issue exists also in branch **3.0.x**
![image](https://cloud.githubusercontent.com/assets/1287165/17621547/8cfc2de4-60c6-11e6-9eaa-99adc8839386.png)

**Comment by sergeyklay** [comment]
@yiivon Could you please try 3.0.x branch?

**Comment by yiivon** [comment]
@sergeyklay Sure, result:
![image](https://cloud.githubusercontent.com/assets/1287165/17692573/f14eb970-63cc-11e6-9055-d06fd0286686.png)

**Comment by sergeyklay** [comment]
@yiivon Could you please try 3.0.x branch?

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
