### ISSUE TITLE
Non-existent class "IncrementalItem" (the latest devtools 3.0 version)

### ISSUE THREAD

**Issue by DroneZzZko** [phalcon/phalcon-devtools#757]
If run migration always get:
`PHP Fatal error:  Uncaught Error: Class 'Phalcon\Version\IncrementalItem' not found in vendor/phalcon/devtools/scripts/Phalcon/Version/ItemCollection.php:76
`
In fact there is no such class. The file is, but the class is called "item".

**Comment by sergeyklay** [comment]
@DroneZzZko Could you please try 3.0.x branch?

**Comment by DroneZzZko** [comment]
I get devtools via composer: `"phalcon/devtools": "~3.0.0"`
Is that not enough?

**Comment by sergeyklay** [comment]
@DroneZzZko Are you sure?

Current `master`: https://github.com/phalcon/phalcon-devtools/blob/master/scripts/Phalcon/Version/IncrementalItem.php#L32
Current `3.0.x`: https://github.com/phalcon/phalcon-devtools/blob/3.0.x/scripts/Phalcon/Version/IncrementalItem.php#L32

**Comment by DroneZzZko** [comment]
I think the issue can be closed.
