### ISSUE TITLE
PHP 5.6.21 & Phalcon 3 : Warning: Cannot bind an instance to a static closure

### ISSUE THREAD

**Issue by anhlx412** [phalcon/phalcon-devtools#758]
I use php 5.6 & phalcon 3.0. When I create project and --enable-webtools, visit webtools.php page, i see some errors :
1. Warning: Cannot bind an instance to a static closure in C:\phalcon-devtools\scripts\Phalcon\Web\Tools.php on line 359
=> echo $app->handle()->getContent();
2. Warning: Cannot bind an instance to a static closure in C:\phalcon-devtools\scripts\Phalcon\Web\Tools\views\index.phtml on line 15
=> <?php echo $this->tag->stylesheetLink('css/bootstrap/bootstrap.min.css') ?>
3. Fatal error: Using $this when not in object context in C:\phalcon-devtools\scripts\Phalcon\Web\Tools.php on line 306
=> $config = $this->getConfig();

I dont know why ? please help. Thank you so much

**Comment by sergeyklay** [comment]
Phalcon now binds DI to closures used as service definition, however if the closure was created in a static context PHP raises that warning, that only happens in PHP5, it seems that in PHP7 that warning was disabled or removed. 

https://github.com/phalcon/cphalcon/issues/11029#issuecomment-200612702
https://github.com/phalcon/phalcon-devtools/issues/717

**Comment by GBraL** [comment]
Using Phalcon 3 and PHP 5.6 I can't remove this message?

**Comment by sergeyklay** [comment]
@GBraL See please response here https://github.com/phalcon/cphalcon/issues/11029

**Comment by GBraL** [comment]
Thank you.
