### ISSUE TITLE
There are number of Warning in Webtools about static closure's binding of instance, version 3.0.x

### ISSUE THREAD

**Issue by yiivon** [phalcon/phalcon-devtools#760]
![image](https://cloud.githubusercontent.com/assets/1287165/17726352/141f4ac4-6485-11e6-9ef6-821e3e6d7f55.png)

Refer to PHP manual [here](http://php.net/manual/en/functions.anonymous.php):
![image](https://cloud.githubusercontent.com/assets/1287165/17726420/70ab432e-6485-11e6-8c5d-ce7845c13d2f.png)

I don't know whether there would be any issue on these warning, i just report them as an user, and thanks.

**Comment by sergeyklay** [comment]
https://github.com/phalcon/phalcon-devtools/issues/717

https://github.com/phalcon/cphalcon/issues/11029
