### ISSUE TITLE
Wrong Folder with data migration 

### ISSUE THREAD

**Issue by Rajeshr34** [phalcon/phalcon-devtools#771]
CMD: phalcon migration generate --data=oncreate

For Example:
phalcon Create Folder Called "1.0.0" and it stores all table structure. 
but for table data (*.dat files) it trying to put content in "100" folder which folder is not exists
```
PHP Warning:  fclose() expects parameter 1 to be resource, boolean given in /root/phalcon-devtools/scripts/Phalcon/Mvc/Model/Migration.php on line 430
```

and phalcon migration run trying to find (*.dat) in "1.0.0" 

I hope you get it. Sorry for my English :)

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
