### ISSUE TITLE
Framework code does not match with Phalcon site tutorial

### ISSUE THREAD

**Issue by rogervila** [phalcon/phalcon-devtools#774]
Hello,

I'm new in Phalcon PHP. I installed phalcon devtools 3.0.0 but the files content is not the same as the [Phalcon site tutorial](https://docs.phalconphp.com/en/latest/reference/tutorial.html)

Am I missing something?

Thank you!

P.D.  The [Phalcon site tutorial about devtools is outdated](https://docs.phalconphp.com/en/latest/reference/tools.html), but I understand that this is not an issue for this repository.

**Comment by sergeyklay** [comment]
Hello @rogervila 

This is [docs](https://github.com/phalcon/docs) issue.
Could you please open a issue in the corresponding repo?

**Comment by rogervila** [comment]
Yes, no problem.
Now that I know that the docs are outdated and there is no problem with devtools, where can I read/view the updated docs for phalcon 3?

Thank you.

**Comment by sergeyklay** [comment]
It seems to me outdated mostly Devtools doc.
Anyway fell free to create a issue in the [Phalcon Docs](https://github.com/phalcon/docs) repo.

The most recent documentation is here: https://docs.phalconphp.com/en/latest/index.html

Thanks.
