### ISSUE TITLE
How to generate a migration of multiple tables?

### ISSUE THREAD

**Issue by DannyFeliz** [phalcon/phalcon-devtools#775]
I need to generate a migration of two tables with this command 
`phalcon migration generate --table=tableA tableB` 
but the dev-tool only takes the last specified table, there is a way to get this working?

**Comment by lenrsmith** [comment]
@sergeyklay I'm thinking about ways to handle this as it would be nice to have for one of my projects. It seems we are grabbing options with $argv and could make use of some more robust options handling. Any thoughts here? I can make this work for CLI, but I don't want to break the Web Tools.

**Comment by sergeyklay** [comment]
It seems to me we can check for string/array type of argument to handle multiple tables

**Comment by lenrsmith** [comment]
I'll dig into this a bit. I'm just getting my head into how the dev-tools work, so bear with me.
