### ISSUE TITLE
hasOne relations not recognized

### ISSUE THREAD

**Issue by cbichis** [phalcon/phalcon-devtools#834]
Hello,

DevTools, when generating a model it doesnt seems to recognize the hasOne relations.

Table1: PK id
Table2: PK id

with referential integrity set between them.

is creating rather hasMany/belongsTo relation....

**Comment by sergeyklay** [comment]
Could you please steps to reproduce

**Comment by sergeyklay** [comment]
@cbichis

**Comment by cbichis** [comment]
I need a bit of time to do a sample demo as I noticed this into a complex database.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
