### ISSUE TITLE
1 memory leaks detected when using "./phalcon-devtools/phalcon.php"

### ISSUE THREAD

**Issue by farwish** [phalcon/phalcon-devtools#836]
/home/xxx/Downloads/cphalcon/build/php5/64bits/phalcon.zep.c(23687) :  Freeing 0x7FE5FC7E1590 (32 bytes), script=/home/xxx/Downloads/phalcon-devtools/phalcon.php
=== Total 1 memory leaks detected ===

Note: v3.0.1

**Comment by sergeyklay** [comment]
Could you please provide steps to reproduce

**Comment by farwish** [comment]
ok, i will describe as detailed as possible.

Environment : besides some generic options，I had compile php with --enable-debug and --enable-maintainer-zts options in php5.6.23 before.

```
Configure Command =>  './configure'  '--with-libdir=lib64' '--prefix=/usr/local/php5.6.23' '--with-mysql' '--with-mysqli' '--with-pdo-mysql' '--enable-inline-optimization' '--enable-fpm' '--with-freetype-dir=/usr/local/freetype' '--with-gd' '--with-zlib' '--with-png-dir' '--with-jpeg-dir' '--enable-mbstring' '--with-iconv' '--enable-sockets' '--with-curl' '--with-mcrypt' '--with-openssl' '--enable-pcntl' '--enable-soap' '--enable-opcache' '--enable-maintainer-zts' '--enable-bcmath' '--enable-debug'
```

My operation steps as root :
1. installed cphalcon extension in the way "compile-from-source". ( and installed success. )
2. install phalcon-devtools. ( and installed success. )

a complete shell contents used is here : https://raw.githubusercontent.com/farwish/MyShell/master/installPhalcon.sh

Then i run phalcon command, it will show that memory leaks detected.

**Comment by sergeyklay** [comment]
This is not DevTools issue. For Phalcon related issues use the [phalcon/cphalcon](https://github.com/phalcon/phalcon-devtools).
