### ISSUE TITLE
Incorrect model names generated in relations

### ISSUE THREAD

**Issue by cbichis** [phalcon/phalcon-devtools#846]
Hello,

I have 2 models:

`Ad\Models\Ad` (with source been table `ad`): `id`, `model_id`  where make_id is a FK to second model:
`Ad\Models\Model` (with source been table `ad_model`): `id`, `name`

```
phalcon model ad \
    --name=ad \
    --namespace=Ad\\Models \
    --output=apps/ad/models \
    --get-set \
    --force \
    --camelize \
    --mapcolumn \
    --annotate \
    --doc

phalcon model model \
    --name=ad_model \
    --namespace=Ad\\Models \
    --output=apps/ad/models \
    --get-set \
    --force \
    --camelize \
    --mapcolumn \
    --annotate \
    --doc
```
The relations are defined incorrectly:
```php
        $this->belongsTo('modelId', 'Ad\Models\AdModel', 'id', ['alias' => 'AdModel']);
```

But it should be:
```php
        $this->belongsTo('modelId', 'Ad\Models\Model', 'id', ['alias' => 'Model']);
```

**Comment by cbichis** [comment]
The relationship is defined correctly on the other side:
        $this->hasMany('id', 'Ad\Models\Ad', 'modelId', ['alias' => 'Ad']);

**Comment by sergeyklay** [comment]
@cbichis Could you please provide table schema?

**Comment by sergeyklay** [comment]
It is not possible to change this behavior. At least the number of changes and additions is not proportional with what you need to do in this case:

1. Open the `Ad` model in your text editor
2. Change the `'Ad\Models\AdModel'` to the `'Ad\Models\Model'`

If you find an elegant solution - you are always welcome with your PRs.
