### ISSUE TITLE
PostgreSQL migrations - default values in double quotes 

### ISSUE THREAD

**Issue by radeczo** [phalcon/phalcon-devtools#859]
Hi.

Phalcon DevTools (3.0.0)

Default values in PostgreSQL should be in single quotes (for strings) or as an number (for int, bigint, etc.). Double quoted values Postgres interprets as column names.

Error example: 

Column definition:

    new Column(
        'status',
        [
            'type' => Column::TYPE_INTEGER,
            'default' => "1",
            'after' => 'order'
        ]
    ),

Generated SQL:

    CREATE TABLE "public"."table" (
        ...
        "status" INT DEFAULT "1",
        ...
    );

Postgres error:
`ERROR: SQLSTATE[42703]: Undefined column: 7 ERROR:  column "1" does not exist`

**Comment by sergeyklay** [comment]
@radeczo 

I've [fixed this issue](https://github.com/phalcon/cphalcon/issues/12276) in the Phalcon `3.0.x` branch. You need to update Phalcon:

```sh
git clone git@github.com:phalcon/cphalcon.git
cd cphalcon
git checkout 3.0.x

zephir fullclean
zephir build
```

Thank you for contributing!
