### ISSUE TITLE
Quick Server ?

### ISSUE THREAD

**Issue by HudsonNicoletti** [phalcon/phalcon-devtools#871]
Can somthing like 'artisan serv' be created for phalcon to quickly spin up a phalcon application?

**Comment by sergeyklay** [comment]
https://docs.phalconphp.com/en/latest/reference/built-in.html

We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
