### ISSUE TITLE
Scaffolding a model with FK's to the same table creates similarly named aliases

### ISSUE THREAD

**Issue by juanreynolds** [phalcon/phalcon-devtools#888]
I have a table in a database that has two FK's that point to the same table:

field user_created is a FK to user table
field user_modified is a FK to user table

When I scaffold the model using Devtools I get a model with relationships with these aliases:

``` php
$this->hasMany('id', 'PhalconRest\Models\User', 'created_by', ['alias' => 'UsersCreated']);
$this->hasMany('id', 'PhalconRest\Models\User', 'modified_by', ['alias' => 'UsersModified']);
```

In cases like this is would be preferable to append the Camelised field name to the alias as well so as to ensure unique aliases.

**Comment by sergeyklay** [comment]
@juanreynolds Thanks for reporting. I'll try to sort out ASAP.

**Comment by sergeysviridenko** [comment]
@juanreynolds could you provide a little bit more information and example what you'd like to have?

**Comment by Jeckerson** [comment]
I don't see any problem with current aliases. Closing for now...
