### ISSUE TITLE
How to create project phalcon with structure "multiple-service-layer-model"

### ISSUE THREAD

**Issue by ideasvn** [phalcon/phalcon-devtools#893]
I like structure 
https://github.com/phalcon/mvc/tree/master/multiple-service-layer-model

But I don't know create project with structure below, I try run command

$>phalcon project papacms --type=modules --template-path=C:/multiple-service-layer-model

not working.

**Comment by sergeyklay** [comment]
Hello @ideasvn

Unfortunately, Phalcon Developer Tools doesn't allow to create projects by a custom template at the moment. I mean, you can't just make it take as an example something you wish. We'll add to Phalcon Developer Tools something like this in future, but right now you can solve this problem only by copy-and-paste job.

When you specify explicitly the Project Template by passing `--template-path=...` you have to provide fully compatible template with the required placeholders, etc. Notice: the Phalcon Developer Tools need to know the exact location of all files of this template and its structure. Right now fully compatible templates located here https://github.com/phalcon/phalcon-devtools/tree/master/templates.

And lastly. We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the Phalcon Developer Tools, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
