### ISSUE TITLE
[project] favicon

### ISSUE THREAD

**Issue by jhaoheng** [phalcon/phalcon-devtools#903]
Hi

use `save()` will insert two record, the reason is `NO favicon`
<https://forum.phalconphp.com/discussion/274/model-save-create-two-records>

When `phalcon project {name}` will create a new one, but this no include 
`<link rel="shortcut icon" type="image/png" href="{{ url('img/favicon.png') }}"/>`

I think , maybe could add this line to avoid this issue and to help develop.

**Comment by sergeyklay** [comment]
Could you please submit PR?

**Comment by sergeyklay** [comment]
Fixed in the `3.2.x` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
