### ISSUE TITLE
How to use migrations generate/run ?

### ISSUE THREAD

**Issue by yangqiphp** [phalcon/phalcon-devtools#905]
When I enter: phalcon migration run, I get this error message.                  
  Error: Migration class cannot be found UsersMigration_101 at /home/yangqi/www/compass/apps/rollingscreen/config/../migrations/1.0.1/users.php  

And how to use the migrations? up and down functions ?

    /**
     * Run the migrations
     *
     * @return void
     */
    public function up()
    {

    }

    /**
     * Reverse the migrations
     *
     * @return void
     */
    public function down()
    {

    }

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).

For documentation please refer to https://docs.phalconphp.com/en/3.0.1/reference/tools.html
