### ISSUE TITLE
Configurable log location

### ISSUE THREAD

**Issue by phackwer** [phalcon/phalcon-devtools#911]
Greetings,

In working on Phalcony (a Symfony modularized organization approach for rest backends based on Phalcon - phalcony/phalcony on packagist - still under heavy development)  and I would like to be able to set the migration version for each module individually. For that, I needed to be able to set the log file location, since I scan all Modules and search for migration for each one. Can I just fork the phalcon devtools and add this feature to make it possible or you guys prefer I create a new phalcony-devtools extending the original phalcon devtools?

Let me know which one would be the better approach. Thanks.

**Comment by sergeyklay** [comment]
@phackwer https://github.com/phalcon/phalcon-devtools/blob/3.0.x/CONTRIBUTING.md :)

Use `3.0.x` please

**Comment by sergeysviridenko** [comment]
@phackwer could you provide more information about your suggestion? For realize this proposition it very helpful.
