### ISSUE TITLE
AllModels doesnt have --camelize

### ISSUE THREAD

**Issue by victorhramos** [phalcon/phalcon-devtools#913]
![image](https://cloud.githubusercontent.com/assets/9410768/20491270/fa80bac6-aff7-11e6-8ab6-165eaf452864.png)

**Comment by sergeysviridenko** [comment]
`phalcon all-model` doesn't have `--camelize` command.
`phalcon model` has `--camelize` command.
You can use `phalcon all-models --help` to get list of commands.

Phalcon DevTools Version - 3.2.0
Phalcon Version - 3.2.1

**Comment by sergeyklay** [comment]
@sergeysviridenko Is it possible to implement `--camelize` feature for the `all-model` command?

**Comment by sergeysviridenko** [comment]
I guess it's possible.

**Comment by sergeyklay** [comment]
Implemented in the 3.2.x branch.
