### ISSUE TITLE
Incorrect View->render() method signature in generated IDE stub View->render() 

### ISSUE THREAD

**Issue by stamster** [phalcon/phalcon-devtools#927]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

* Incorrect View->render() method signature in generated IDE stub View->render() 

> In file: `phalcon-devtools-3.0.2/ide/stubs/Phalcon/mvc/View.php`

```php
 /**
     * Executes render process from dispatching data
     * <code>
     * // Shows recent posts view (app/views/posts/recent.phtml)
     * $view->start()->render("posts", "recent")->finish();
     * </code>
     *
     * @param string $controllerName 
     * @param string $actionName 
     * @param array $params 
     * @return bool|View 
     */
    public function render($controllerName, $actionName, $params = null) {}
```

The issue is second parameter does not exist in current Phalcon source code, so the signature should be:
`public function render($controllerName, $params = null) {}`
### Details

* Phalcon Framework version: 
```
Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.2
Build Date => Nov 28 2016 13:48:20
Powered by Zephir => Version 0.9.4a-dev
```

* Phalcon DevTools (3.0.2)

Note: this was also the case with previous 3.0.x releases.

**Comment by sergeyklay** [comment]
As you can see this is not true:

https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view.zep#L768
```zep
public function render(string! controllerName, string! actionName, params = null) -> <View> | boolean
```

**Comment by stamster** [comment]
Ouch. Sorry, my bad!
God damn PhpStorm with loaded Phalcon IDE stub lied to me on this.
I'm actually using Simple view component: https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/view/simple.zep#L301

Alles goed!
