### ISSUE TITLE
Multi DB Migrations - PDO connection closure unreachable

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/phalcon-devtools#936]
It is good that with version 3 came DB support, but there is problem with multi database update. PDO don't close connection so it use the same connection ID.

I was trying to reach current property, but in whole class all methods are private, so even impossible to extend it.
```
    /**
     * Filename or db connection to store migrations log
     * @var mixed|Adapter\Pdo
     */
    private static $_storage;
```

Unique solution that worked is to comment "return", but it's dirty and unstable while using composer. Also it will spam many requests from another methods...

```
    /**
     * Initialize migrations log storage
     *
     * @param array $options Applications options
     * @throws DbException
     */
    private static function connectionSetup($options)
    {
        if (self::$_storage) {
            //return;
        }
    }
```

I suggest to close session at the end of run() method if it use $options['migrationsInDb'].

```
public static function run(array $options)
```

**Comment by rudiservo** [comment]
Solution on #981 maybe simpler, just change type to protected so it can be extended

Another way would be to have a resetConnection function that would simply put $_storage = null;
