### ISSUE TITLE
Generated migrations don't adhere to unsigned fields

### ISSUE THREAD

**Issue by slogsdon** [phalcon/phalcon-devtools#94]
Suppose a table is created locally with `unsigned` fields similar to this:
```
CREATE TABLE `accounts` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(25) NOT NULL DEFAULT '',
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
```
The resulting migration that is generated for that table will try to create/alter the same table, but the `id` field would not be set as `unsigned`, i.e.:
```
CREATE TABLE `accounts` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(25) NOT NULL DEFAULT '',
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
``` 

For the most part, this would not cause issues, but say if the tables were initially imported from a schema file, subsequent migrations will fail when foreign keys are used with the table.

**Comment by sergeyklay** [comment]
Fixed
