### ISSUE TITLE
[RECOMMENDATION] Installation via Git Problem

### ISSUE THREAD

**Issue by forddyce** [phalcon/phalcon-devtools#941]
Your installation via git says the symbolic link is:

> ln -s /home/[USERNAME]/phalcon-devtools/phalcon.php /usr/bin/phalcon

I have a problem with my machine, it says "phalcon: command not found". Even after I added the chmod. I have to add an alias:

> alias phalcon=/home/[USERNAME]/phalcon-devtools/phalcon.php

Only after then I can use phalcon.
Please add that to your documentation for future reference. My machine is 16.04 Ubuntu.

Thank you.

**Comment by sergeyklay** [comment]
@forddyce Could you please send a PR with doc improvements?

**Comment by forddyce** [comment]
@sergeyklay How do you do that?

**Comment by sergeyklay** [comment]
@forddyce https://github.com/phalcon/phalcon-devtools/blob/master/CONTRIBUTING.md#contributions

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
