### ISSUE TITLE
Phalcon Developer Tools and Validation are incompatible

### ISSUE THREAD

**Issue by cbichis** [phalcon/phalcon-devtools#951]
Hi,

It seems the model validation generated by PDT is not compatible with the new validation.

More details here:
https://forum.phalconphp.com/discussion/8793/generated-orm-and-validation-is-not-compatible-to-itself

**Comment by flyingbono** [comment]
I confirm.

**Comment by sergeyklay** [comment]
I'll fix it asap

**Comment by someson** [comment]
ping! The BUG is getting pesky

**Comment by mzf** [comment]
+1 not fixed yet in 3.1.1

**Comment by sergeyklay** [comment]
Fixed in the 3.2.x branch
