### ISSUE TITLE
camelCase keys for application config

### ISSUE THREAD

**Issue by arnoldbird** [phalcon/phalcon-devtools#953]
In the core/config.php generated by the project command, why are the keys for 'application' array in camelCase, but the keys for the 'database' are all lowercase?

**Comment by Jurigag** [comment]
I think zephir on some point is adding properties to Config object as camelcased anyway. There will be no difference if using lowercase with dashes or camelCase.

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
