### ISSUE TITLE
Remove .php extension from the binary alias

### ISSUE THREAD

**Issue by rogervila** [phalcon/phalcon-devtools#954]
On `.composer/vendor/bin`, the `phalcon` alias should not have the `.php` extension, so commands can be written like `phalcon project blog simple` instead of ``phalcon.php project blog simple``

### Details

* Phalcon Framework version: 3.0.2
* PHP Version: 7.0.14
* Operating System: OS X El Capitan
* Server: Nginx (with Laravel Valet)

**Comment by sergeyklay** [comment]
as workaround you can create an alias like:
```
$ sudo ln -s $(which phalcon.php) /usr/local/bin/phalcon
```

**Comment by rogervila** [comment]
@sergeyklay yes, that's a way to solve it, thank you very much.

Anyway, reducing the amount of deployment steps always helps IMO.

**Comment by sergeysviridenko** [comment]
@rogervila for installation with github there is step by step instruction for using command `phalcon` instead `phalcon.php`. Could you try latest stable version?

**Comment by sergeyklay** [comment]
Actually this is fixed in latest stable release.
