### ISSUE TITLE
Migration - Escapes field and not reverse after run

### ISSUE THREAD

**Issue by victorhramos** [phalcon/phalcon-devtools#956]
I'm trying to use migrations, but got some issues:
- When generate migrations with --data=always the output fields being escaped:
![image](https://cloud.githubusercontent.com/assets/9410768/21691344/56bf14f6-d35f-11e6-9645-a5caba866f3f.png)

It's ok but when i'm running the migration that field stays escaped and after each generation it adds one more escape
![image](https://cloud.githubusercontent.com/assets/9410768/21691426/a7b8584a-d35f-11e6-9d9d-282fd334a2af.png)

### Details

* System info and versions (if possible):
Environment::                                                                             
  OS: Linux scotchbox 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64
  PHP Version: 7.0.14-2+deb.sury.org~trusty+1                                             
  PHP SAPI: cli                                                                           
  PHP Bin: /usr/bin/php7.0                                                                
  PHP Extension Dir: /usr/lib/php/20151012                                                
  PHP Bin Dir: /usr/bin                                                                   
  Loaded PHP config: /etc/php/7.0/cli/php.ini                                             
Versions::                                                                                
  Phalcon DevTools Version: 3.0.4                                                         
  Phalcon Version: 3.0.2                                                                  
  AdminLTE Version: 2.3.6                                                                 

* Phalcon Framework version: 3.0.2
* PHP Version: PHP 7.0.14-2+deb.sury.org~trusty+1 (cli) ( NTS )
* Server: Nginx

**Comment by sergeysviridenko** [comment]
I couldn't replicate. I've generated and run migration. All is ok.
Phalcon DevTools Version: 3.2.0
Phalcon Version: 3.1.2

**Comment by YujiShen** [comment]
I also got this problem...

dat file
```
1,3,1,"{\"title\":\"Timeline\"}",
2,3,2,"{\"title\":\"\\u53d1\\u5c55\\u5386\\u7a0b\"}",
...
```
will become this in database:
```
1	3	1	{\"title\":\"Timeline\"}	
2	3	2	{\"title\":\"\\u53d1\\u5c55\\u5386\\u7a0b\"}	
...
```

Phalcon DevTools (3.2.8)
Phalcon Version: 3.2.4
PHP 7.1.9
Databse: Mariadb
OS: Docker (Alpine Linux)

**Comment by sergeyklay** [comment]
@YujiShen Could you please open new issue with steps to reproduce

**Comment by YujiShen** [comment]
@sergeyklay I open a new one #1137
