### ISSUE TITLE
Implement Phalcon router file

### ISSUE THREAD

**Issue by rogervila** [phalcon/phalcon-devtools#957]
It would be nice to have a [router file](https://docs.phalconphp.com/en/latest/reference/routing.html) by default.

If you agree, I can make a PR. I'm not sure which path is the most appropiated, but could be something like `app/config/routes.php`.

The should not have predefined routes. The file would look like this:

```php
<?php

use Phalcon\Mvc\Router;

// Create the router
$router = new Router();

// Define a route...

$router->handle();

```

What do you think?

**Comment by sergeyklay** [comment]
@rogervila Could you please send PR?

**Comment by rogervila** [comment]
@sergeyklay yes. Which is the best location for the router file?

**Comment by sergeyklay** [comment]
`app/config/routes.php` :)
why not?

**Comment by rogervila** [comment]
Now that [the pull request is merged](https://github.com/phalcon/phalcon-devtools/pull/958) I can close the issue.
