### ISSUE TITLE
ERROR: The environment variable PTOOLSPATH is outdated! 

### ISSUE THREAD

**Issue by mzf** [phalcon/phalcon-devtools#960]
Devtools install from composer
```
Revision: d4aaa3c927a2b09566264005f00c61645d80f5ff
Author: Serghei Iakovlev <sergeyklay@users.noreply.github.com>
Date: 15.11.2016 3:25:20
```

get error when run `phalcon` in work dir

```
ERROR: The environment variable PTOOLSPATH is outdated! Current value: "z:\OpenServer\domains\server\trunk\vendor\phalcon\devtools\\". New value: Z:\OpenServer\domains\server\trunk\vendor\phalcon\devtools
```

### Details

* System info and versions (if possible): (`phalcon info`)
* Phalcon Framework version:3.0.3
* PHP Version: 7.0.14
* Operating System: Win7
* Server: Nginx

**Comment by sergeyklay** [comment]
This tells you that you have an outdated value of a `PTOOLSPATH` variable. See `echo $PTOOLSPATH`. You have to update `PTOOLSPATH` variable as follows: 
```sh
set PTOOLSPATH=Z:\OpenServer\domains\server\trunk\vendor\phalcon\devtools
```

or something like that.
