### ISSUE TITLE
Error: Phalcon extension isn't installed. (Phalcon 3 - PHP 7 - Centos 7)

### ISSUE THREAD

**Issue by olliefx** [phalcon/phalcon-devtools#962]
While trying to install Phalcon Dev Tools I receive the error:
Error: Phalcon extension isn't installed. 
I am running (Phalcon 3 - PHP 7 - Centos 7).

When I check to see if the extension is installed it is clear that it is not installed as it is not seen under the php info page. (viewing the php info. http://localhost/info.php). I also checked what extensions are running using ( php -m ) and listing all extensions that have loaded, phalcon was not to be seen. 
When following the installation instructions for this extension during initial installation, it tells me it all installed correctly. 
> **I am trying to install Phalcon 3 on Centos 7 and am following the installation as per the phalcon Documentation. I have already installed phalcon on Ubuntu and all was fine but cant seem to get things going under Centos 7.**

I have viewed the existing forum for info regarding this issue and there were mentions of checking the php.ini file. making sure that:  phalcon.ini in /etc/php.d/ was added with extension=phalcon.so. I have checked this file under etc/php.d/phalcon.ini.

Steps by step Install
Installing Lamp centos 7 and Phalcon 3

0. Update 
 sudo yum update
 sudo yum install nano

1. Install Apache
 sudo yum install httpd

Enable Apache to start at boot
 sudo systemctl enable httpd.service

2. Install the MariaDB-server
to install the latest version of mariadb we can use the mariadb repository.
https://downloads.mariadb.org/mariadb/repositories/#mirror=aarnet_pty_ltd&distro=CentOS&distro_release=centos7-amd64--centos7&version=10.1
 sudo yum install MariaDB-server MariaDB-client

Enable MariaDB to start at boot
sudo systemctl enable mariadb.service

3. install PHP 7 
Have used IUS repository. for php70u which is the same version listed under phalcon website. Dont know wheather to use a different php7 from another repository eg. EPEL Repository, Remi Repository, Webtatic Repository etc.

Install the new PHP 7 packages from IUS
Install repository:
 cd ~
 curl 'https://setup.ius.io/' -o setup-ius.sh
 run the script
 sudo bash setup-ius.sh

Install PHP 7 + additional required packages.
 sudo yum install php70u php70u-cli php70u-devel php70u-mysqlnd

Restart apache:
 sudo apachectl restart

Additional PHP packages
 sudo yum install git
 sudo yum install gcc
(Dont know if i need mcrypt or any other packages?)

Test PHP: 
 php -v
 yum info php
 Created an info.php file in webroot
 nano /var/www/info.php
 <?php
 phpinfo();
 ?>
 Test php in browser using url:
 http://localhost/info.php

4. Lastly Restart apache server:
 sudo systemctl restart httpd.service

5. Install Phalcon:
phalcon repository
 curl -s https://packagecloud.io/install/repositories/phalcon/stable/script.rpm.sh | sudo bash

6. Install Phalcon:
 sudo yum install php70u-phalcon
(Installed phalcon to home directory not sure if this is a problem)

7. Creating the extension:
git clone git://github.com/phalcon/cphalcon.git
cd cphalcon/build
sudo ./install

8. Install Devtools
Receive error trying to install phalcon devtools.

	=====Error: Phalcon extension isn't installed.=====

### Details

* Centos 7 (if possible): (`phalcon info`)
* Phalcon 3: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Apache

**Comment by sergeyklay** [comment]
This is install issue/question related to the Phalcon, not to the Devtools. 
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the Phalcon framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
