### ISSUE TITLE
installation issue `"identifier (T_STRING)"' or `"variable (T_VARIABLE)"' or `'{'' or `'$''

### ISSUE THREAD

**Issue by AstmDesign** [phalcon/phalcon-devtools#965]
Dear All,
I'm trying to install the Phalcon command on my Mac OSX 10.9.4, After run the  commands

```
cd ~
git clone https://github.com/phalcon/phalcon-devtools.git
cd phalcon-devtools
ln -s ~/phalcon-devtools/phalcon.php /usr/bin/phalcon
chmod ugo+x /usr/bin/phalcon
```

and when I typing the command ` $Phalcon`  I'm usually got this issue on the terminal

`Parse error: parse error, expecting `"identifier (T_STRING)"' or `"variable (T_VARIABLE)"' or `'{'' or `'$'' in /Users/astm/phalcon-devtools/phalcon.php on line 53
`

BTW, I'm using PHP Version 5.6.7 and I can see the Phalcon installed from the phpinfo page and this is my Phalcon details

```
Author: Phalcon Team and contributors
Version: 3.0.0
Build Date: Aug 1 2016 08:27:18
Powered by Zephir: Version 0.9.3a-dev-e716dbe641
```

and my composer version is : 
`1.4-dev (64b9423df3cf04034809781cb034470e61225190) 2017-01-19 12:39:26
` 
so why I got this error and how I can fix it to run Phalcon command from my terminal

**Comment by sergeyklay** [comment]
Dear Abd El Sameia Talaat,

First of all I need to notice the phrases:

> I'm trying to install the Phalcon

What exactly do you need to do? To install **Phalcon Framework** or **Developer Tools**? Note: the command `git clone https://github.com/phalcon/phalcon-devtools.git` will clone Developer Tools not Phalcon Framework.

> and when I typing the command $Phalcon

There is no `$Phalcon` command. After installing Developer Tools you will be able to use "`/usr/bin/phalcon`” command (or just “`phalcon`”) but not “`$Phalcon`”. 

So in general I not fully understand what exactly you need to do. Could you please explain a bit more?

Have a nice day

**Comment by AstmDesign** [comment]
Hi @sergeyklay,
First I would like to thank you for replaying me and let me discripe to you what I mean
I'm usually got this error with the phalcon devtools if I tried to run it for example if I want to create new Phalcon application and tried to type in my terminal this command

`$ phalcon create-project my_app_name `  
 
it's alert me 

`Parse error: parse error, expecting `"identifier (T_STRING)"' or `"variable (T_VARIABLE)"' or `'{'' or `'$'' in /Users/astm/phalcon-devtools/phalcon.php on line 53 `

so if i'm trying to type any more commands start with `phalcon` from my terminal such as 

$ phalcon create-controller --name test
$ phalcon model products
$ phalcon model --name tablename
$ phalcon scaffold --table-name products
$ phalcon gen-migration

I got the same previous issue, so how I can fix it?

**Comment by sergeyklay** [comment]
Provide please PHP version

**Comment by Green-Cat** [comment]
Is your phalcon dev tools version matching your phalcon version?

**Comment by AstmDesign** [comment]
@sergeyklay my PHP Version is: 5.6.7 and my Phalcon version is 3.0.0

**Comment by sergeyklay** [comment]
@AstmDesign Could you please provide output from:

`/usr/bin/phalcon info `

**Comment by AstmDesign** [comment]
@sergeyklay  when I'm typing the command `/usr/bin/phalcon info` I get the same error

`Parse error: parse error, expecting `"identifier (T_STRING)"' or `"variable (T_VARIABLE)"' or `'{'' or `'$'' in /Users/astm/phalcon-devtools/phalcon.php on line 53`

**Comment by sergeyklay** [comment]
Could you please provide output of:
```
php --ri phalcon
```

and

```
php-config
```

and

```
php --version
```

**Comment by AstmDesign** [comment]
@sergeyklay 
```
$php --ri phalcon

Extension 'phalcon' not present.
```

```
$ php-config

Usage: /usr/bin/php-config [OPTION]
Options:
  --prefix            [/usr]
  --includes          [-I/usr/include/php -I/usr/include/php/main -I/usr/include/php/TSRM -I/usr/include/php/Zend -I/usr/include/php/ext -I/usr/include/php/ext/date/lib]
  --ldflags           [  -L/BinaryCache/FreeType/FreeType-18~1619/Root/usr/local/lib]
  --libs              [-lresolv  -lz -lexslt -ltidy -lresolv -ledit -lncurses -lldap -llber -liconv -liconv -lpng -lz -ljpeg -lcrypto -lssl -lcrypto -lcurl -lbz2 -lz -lpcre -lcrypto -lssl -lcrypto -lm  -lxml2 -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lcurl -lxml2 -lfreetype -lz -lxml2 -lnetsnmp -lcrypto -lxml2 -lxml2 -lxml2 -lxml2 -lxml2 -lxml2 -lxml2 -lxslt ]
  --extension-dir     [/usr/lib/php/extensions/no-debug-non-zts-20100525]
  --include-dir       [/usr/include/php]
  --man-dir           [/usr/share/man]
  --php-binary        [/usr/bin/php]
  --php-sapis         [ apache2handler cli fpm]
  --configure-options [--prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --disable-dependency-tracking --sysconfdir=/private/etc --with-apxs2=/usr/sbin/apxs --enable-cli --with-config-file-path=/etc --with-config-file-scan-dir=/Library/Server/Web/Config/php --with-libxml-dir=/usr --with-openssl=/usr --with-kerberos=/usr --with-zlib=/usr --enable-bcmath --with-bz2=/usr --enable-calendar --disable-cgi --with-curl=/usr --enable-dba --enable-ndbm=/usr --enable-exif --enable-fpm --enable-ftp --with-gd --with-freetype-dir=/usr/local --with-jpeg-dir=/usr/local --with-png-dir=/usr/local --enable-gd-native-ttf --with-icu-dir=/usr --with-ldap=/usr --with-ldap-sasl=/usr --with-libedit=/usr --enable-mbstring --enable-mbregex --with-mysql=mysqlnd --with-mysqli=mysqlnd --without-pear --with-pdo-mysql=mysqlnd --with-mysql-sock=/var/mysql/mysql.sock --with-readline=/usr --enable-shmop --with-snmp=/usr --enable-soap --enable-sockets --enable-sqlite-utf8 --enable-sysvmsg --enable-sysvsem --enable-sysvshm --with-tidy --enable-wddx --with-xmlrpc --with-iconv-dir=/usr --with-xsl=/usr --enable-zend-multibyte --enable-zip --with-pcre-regex=/usr]
  --version           [5.4.24]
  --vernum            [50424]
```

```

$ php --version

PHP 5.4.24 (cli) (built: Jan 19 2014 21:32:15) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
```

**Comment by sergeyklay** [comment]
> PHP 5.4.24

We don't support PHP 5.4

> Extension 'phalcon' not present.

You have to install Phalcon extension
