### ISSUE TITLE
Problem installing devtools on mac osx

### ISSUE THREAD

**Issue by Bobyblanco** [phalcon/phalcon-devtools#968]
After some troubles with the phalcon installation, this part is now done and seems to work perfectly
Now I am working on the devtools installation. I am going to explain step by step what i have done:

As the documentation say:
First, i created a folder Phalcon in my documents, from here with the terminal i execute this commande:
`git clone git://github.com/phalcon/phalcon-devtools.git`

This creates me a phalcon-devtools directory with the content within
then:
`cd phalcon-devtools/`
`. ./phalcon.sh`

It tells me that the devtools are correctly installed and directly after:
segmentation fault : 11

if i try the next commands
`ln -s ~/phalcon-tools/phalcon.php ~/phalcon-tools/phalcon`
`chmod +x ~/phalcon-tools/phalcon`
or even
`phalcon`

I always have segmentation fault:11

My expectation, regarding what i have seen on the web is because of the php.ini modifications (maybe)

I tried also the installation using composer and same again segmentation fault

Any Idea

### Details

* Phalcon Framework version: Phalcon 3
* PHP Version: 7.1.0
* Operating System: Mac OSX Sierra
* Server: Apache

**Comment by sergeysviridenko** [comment]
@Bobyblanco as I understand the problem was solved on the [forum](https://forum.phalconphp.com/discussion/15405/problem-installing-webtools-on-mac-osx) and we can close this issue?
