### ISSUE TITLE
phalcon create-controller --name="hep" --directory="app\frontend\controllers"  Phalcon DevTools (3.0.2)  **Error: This command should be invoked inside a Phalcon project directory.**

### ISSUE THREAD

**Issue by VijayTanikella** [phalcon/phalcon-devtools#973]
phalcon create-controller --name="hep" --directory="app\frontend\controllers"

Phalcon DevTools (3.0.2)

**Error: This command should be invoked inside a Phalcon project directory.**

shows up.

Details
I am in the project directory and I want the controller to create in app\frontend\controllers.
Phalcon version: (php --ri phalcon)
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.0.1
Build Date => Aug 24 2016 10:49:16
Powered by Zephir => Version 0.9.4a-dev-7e304ba18c

PHP Version: (php -v) 5.5.12

Operating System: Windows 10

Installation type: Compiling from source || installing via package manager

Zephir version (if any): 

Server: Nginx | Apache | Other: Apache

Other related info (Database, table schema): mysql

**Comment by sergeyklay** [comment]
You have to use this command inside a Phalcon project directory.

* https://forum.phalconphp.com/discussion/1143/error-this-command-should-be-invoked-inside-a-phalcon-project-di

**Comment by VijayTanikella** [comment]
Thanks for the link. 
But,  Before I posted, I read through the forum and I have .phalcon folder  already existing. But it did not help. So, I posted this issue for a solution from the team.
I also had updated the phalcon dll before posting for help.

To clarify again, I am in the project directory.
Am I missing anything inadvertently ?

**Comment by Chuvisco88** [comment]
Same problem here. I have a `.phalcon` directory in my project and I get the error when using `--name` and `--directory`.
Interestingly when I don't use double dashes I get `Error: Please specify a controller directory.`

**Comment by sergeyklay** [comment]
Actually you have to use `--output`, not `--directory`. Please double check the help.
