### ISSUE TITLE
windows phalcon commands 

### ISSUE THREAD

**Issue by duchao1990** [phalcon/phalcon-devtools#974]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related

```php
// paste output here
```
> Provide minimal script to reproduce the issue

```php
// paste code
```

### Details

* System info and versions (if possible): (`phalcon info`)
* Phalcon Framework version: (`php --ri phalcon`)
* PHP Version: (`php -v`)
* Operating System:
* Server: Nginx | Apache | Other
* Other related info (Database, table schema): 

ERROR: The environment variable PTOOLSPATH is outdated! Current value: "D:\phalcon-devtools\\". New value: D:\phalcon-devtools

**Comment by sergeyklay** [comment]
As described in error message you have to modify `PTOOLSPATH` environment variable  from `D:\phalcon-devtools\` to `D:\phalcon-devtools`
