### ISSUE TITLE
ERROR: Phalcon extension isn't installed

### ISSUE THREAD

**Issue by vladimirprieto** [phalcon/phalcon-devtools#975]
### Expected and Actual Behavior

error came up after running ./phalcon.sh

```php
➜  phalcon-devtools git:(master) ./phalcon.sh                                           

Phalcon Developer Tools Installer

Make sure phalcon.sh is in the same dir as phalcon.php
and that you are running this with sudo or as root.

Installing Devtools...
Working dir is: /root/download/phalcon-devtools
Generating symlink...

Done. Phalcon Developer Tools installed!
Thank you for using Phalcon Developer Tools!
We hope that Phalcon Developer Tools helps to make your life easier.

In case of problems: https://github.com/phalcon/phalcon-devtools/issues 
                and: https://forum.phalconphp.com

To start using Phalcon Developer Tools you need to run 'source /root/.bashrc'

ERROR: Phalcon extension isn't installed, follow these instructions to install it: https://docs.phalconphp.com/en/latest/reference/install.html
```
> i edit phalcon.sh to get it working:

from this:

```php
....
if check_install; then
        devtools=${PTOOLSPATH%/}
        php "$devtools/phalcon.php" $*
fi
```

to this

```php
....
if check_install; then
        devtools=${PTOOLSPATH%/}
        php7.0 "$devtools/phalcon.php" $*
fi
```

### Details

* Phalcon Framework version: 3.0.3
* PHP Version: 5.5 && 5.6 && 7.0 && 7.1  <<<<----here is the problem!
* Operating System: ubuntu 16.10
* Server: Nginx

the problem is that i only install Phalcon on PHP 7.0.  so, php (that point to 7.1) not recognize phalcon.

suggestion:

try to get how many PHP versions are installed and test phalcon on every of them, and install Phalcon Dev Tools on every PHP version.

thanks!

**Comment by vladimirprieto** [comment]
same goes to phalcon.php

change this 
```
#!/usr/bin/env php
<?php
```  

to this

```
#!/usr/bin/env php7.0
<?php

```

**Comment by sergeyklay** [comment]
> i edit phalcon.sh to get it working:

Instead of this you can create symlink from `php7.0` to the `php`. Isn't it?

**Comment by vladimirprieto** [comment]
that would fix **this** problem, but will create others: i have those versions of PHP but my main PHP line is 5.6.  another one: Ubuntu by default put 7.1.

i think the correct way would be what i said.

**Comment by vladimirprieto** [comment]
i got another problem here and i think is what i did to get this working:

as a user, i get this:

```
$ phalcon create-project test
zsh: permission denied: phalcon
```

as root, got no problems.  i check permissions on symlink /usr/bin/phalcon and is 777.  i also check the downloaded scripts wich point that symlink and is 755.  so don't now what to do to fix that.
