### ISSUE TITLE
\Phalcon\Builder\Options usage of constant "key"

### ISSUE THREAD

**Issue by cottton** [phalcon/phalcon-devtools#979]
I think this is a typo: https://github.com/phalcon/phalcon-devtools/blob/3.0.x/scripts/Phalcon/Builder/Options.php#L55

    public function has($key)
    {
        return (isset($this->key) || array_key_exists($key, $this->toArray()));
    }

`$this->key` should be `$this->$key`.
I also would suggest using `$this->{$key}`. We then would have seen an fatal error at typo `$this->{key}` like `undefined constant key`.

PR: https://github.com/phalcon/phalcon-devtools/pull/978

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch. Thanks
