### ISSUE TITLE
phalcon.bat sets wrong PTOOLSPATH

### ISSUE THREAD

**Issue by wmathes** [phalcon/phalcon-devtools#987]
Just a quick find after updating to current master. I haven't updated probably since 3.0.2 so i can't pinpoint the origin quickly (it's friday after all... :P)

### Expected and Actual Behavior

On windows (aka using the phalcon.bat) will always result in
`ERROR: The environment variable PTOOLSPATH is outdated! Current value: "<path with extra slash>".`

### Details

Environment::
  OS: Windows NT RUFFRUFF 10.0 build 14393 (Windows 10) i586
  PHP Version: 7.0.15
  PHP SAPI: cli
  PHP Bin: C:\xampp\php\php.exe
  PHP Extension Dir: C:\php\ext
  PHP Bin Dir: C:\php
  Loaded PHP config: C:\xampp\php\php.ini
Versions::
  Phalcon DevTools Version: 3.0.5
  Phalcon Version: 3.0.4
  AdminLTE Version: 2.3.6

### Recommended fix

Change [phalcon.bat:3](https://github.com/phalcon/phalcon-devtools/blob/master/phalcon.bat#L3) from
`set PTOOLSPATH="%~dp0\"`
to
`set PTOOLSPATH=%~dp0`

Have a look at this old article concerning [%~dp0](http://stackoverflow.com/questions/5034076/what-does-dp0-mean-and-how-does-it-work). The ending \ is already part of the output, no need for extras. It's important though to remove the "" as well. :)

PS: I can provide a one-line PR if it's helpful ^_^

**Comment by sergeyklay** [comment]
@wmathes Could you please send PR to the 3.1.x branch?

**Comment by sergeyklay** [comment]
Fixed, thank you
